In [3]:
# !pip install optuna

In [4]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [8]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-06-12 19:42:50,424] A new study created in memory with name: no-name-c1941bc7-6f2e-4d73-a566-82e6fa02c181
[I 2025-06-12 19:42:51,398] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 112, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-06-12 19:42:52,696] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 153, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-06-12 19:42:53,735] Trial 2 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 115, 'max_depth': 10}. Best is trial 2 with value: 0.7709497206703911.
[I 2025-06-12 19:42:55,246] Trial 3 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 176, 'max_depth': 6}. Best is trial 2 with value: 0.7709497206703911.
[I 2025-06-12 19:42:56,519] Trial 4 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 158, 'max_depth': 3}. Best is trial 2 with value: 0.7709497206703911.
[I 2025-06-12 19:42:58,356] Trial 5 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 200, 'max_depth': 8}. Best is trial 2 with value: 0.7709497206703911.
[I 2025-06-12 19:42:59,214] Trial 6 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 93, 'max_depth': 10}. Best is trial 2 with value: 0.7709497206703911.
[I 2025-06-12 19:43:00,127] Trial 7 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 101, 'max_depth': 13}. Best is trial 7 with value: 0.7746741154562384.
[I 2025-06-12 19:43:00,792] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 77, 'max_depth': 13}. Best is trial 7 with value: 0.7746741154562384.
[I 2025-06-12 19:43:02,393] Trial 9 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 187, 'max_depth': 16}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:02,901] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 19}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:04,119] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 138, 'max_depth': 16}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:06,010] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 193, 'max_depth': 14}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:06,841] Trial 13 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 88, 'max_depth': 17}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:08,094] Trial 14 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 135, 'max_depth': 20}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:09,399] Trial 15 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 137, 'max_depth': 20}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:11,334] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 173, 'max_depth': 17}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:13,246] Trial 17 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 182, 'max_depth': 19}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:14,869] Trial 18 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 157, 'max_depth': 15}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:16,308] Trial 19 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 132, 'max_depth': 18}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:16,938] Trial 20 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 52, 'max_depth': 20}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:18,130] Trial 21 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 102, 'max_depth': 13}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:18,919] Trial 22 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 73, 'max_depth': 12}. Best is trial 9 with value: 0.7765363128491619.
[I 2025-06-12 19:43:20,294] Trial 23 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 122, 'max_depth': 15}. Best is trial 23 with value: 0.7783985102420857.
[I 2025-06-12 19:43:21,618] Trial 24 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 15}. Best is trial 23 with value: 0.7783985102420857.
[I 2025-06-12 19:43:22,868] Trial 25 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 118, 'max_depth': 15}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:24,188] Trial 26 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 124, 'max_depth': 15}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:25,457] Trial 27 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 119, 'max_depth': 11}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:26,582] Trial 28 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 106, 'max_depth': 15}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:27,664] Trial 29 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 102, 'max_depth': 17}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:29,226] Trial 30 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 146, 'max_depth': 14}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:30,392] Trial 31 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 109, 'max_depth': 15}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:31,744] Trial 32 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 125, 'max_depth': 16}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:32,947] Trial 33 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 113, 'max_depth': 18}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:34,327] Trial 34 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 128, 'max_depth': 18}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:35,519] Trial 35 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 116, 'max_depth': 18}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:37,098] Trial 36 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 148, 'max_depth': 16}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:38,023] Trial 37 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 90, 'max_depth': 8}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:39,752] Trial 38 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 166, 'max_depth': 12}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:40,958] Trial 39 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 114, 'max_depth': 14}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:42,460] Trial 40 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 145, 'max_depth': 10}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:43,592] Trial 41 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 108, 'max_depth': 16}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:44,472] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 81, 'max_depth': 17}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:45,503] Trial 43 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 97, 'max_depth': 14}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:46,586] Trial 44 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 108, 'max_depth': 4}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:47,818] Trial 45 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 120, 'max_depth': 19}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:49,196] Trial 46 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 132, 'max_depth': 16}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:50,419] Trial 47 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 112, 'max_depth': 13}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:51,445] Trial 48 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 97, 'max_depth': 18}. Best is trial 25 with value: 0.7802607076350093.
[I 2025-06-12 19:43:52,896] Trial 49 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 140, 'max_depth': 8}. Best is trial 25 with value: 0.7802607076350093.

In [9]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 118, 'max_depth': 15}

In [10]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

## Sampler in optuna

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [11]:
# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [12]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-06-12 19:43:53,492] A new study created in memory with name: no-name-7e4b8fe9-c429-44cb-ac26-eea953a10aee
[I 2025-06-12 19:43:55,462] Trial 0 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 190, 'max_depth': 15}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-06-12 19:43:56,243] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 75, 'max_depth': 14}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-06-12 19:43:58,256] Trial 2 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 179, 'max_depth': 9}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-06-12 19:43:58,884] Trial 3 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 59, 'max_depth': 3}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-06-12 19:43:59,737] Trial 4 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 59, 'max_depth': 15}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-06-12 19:44:01,319] Trial 5 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 120, 'max_depth': 6}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-06-12 19:44:03,081] Trial 6 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 118, 'max_depth': 20}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-12 19:44:05,057] Trial 7 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 199, 'max_depth': 11}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-12 19:44:05,945] Trial 8 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 79, 'max_depth': 11}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-12 19:44:07,420] Trial 9 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 144, 'max_depth': 12}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-12 19:44:09,192] Trial 10 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 184, 'max_depth': 8}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-12 19:44:10,403] Trial 11 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 119, 'max_depth': 20}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:12,124] Trial 12 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 172, 'max_depth': 16}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:13,601] Trial 13 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 159, 'max_depth': 11}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:15,030] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 142, 'max_depth': 10}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:16,235] Trial 15 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 113, 'max_depth': 12}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:17,154] Trial 16 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 94, 'max_depth': 7}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:17,839] Trial 17 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 70, 'max_depth': 4}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:19,030] Trial 18 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 124, 'max_depth': 8}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:19,510] Trial 19 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 50, 'max_depth': 6}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:20,248] Trial 20 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 80, 'max_depth': 9}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:22,160] Trial 21 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 192, 'max_depth': 13}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:23,716] Trial 22 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 166, 'max_depth': 20}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:25,334] Trial 23 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 173, 'max_depth': 11}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:26,912] Trial 24 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 172, 'max_depth': 16}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:27,987] Trial 25 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 115, 'max_depth': 12}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:28,678] Trial 26 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 74, 'max_depth': 13}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:29,654] Trial 27 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 111, 'max_depth': 8}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:30,210] Trial 28 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 63, 'max_depth': 5}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:31,272] Trial 29 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 115, 'max_depth': 8}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:32,904] Trial 30 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 186, 'max_depth': 4}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:33,445] Trial 31 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 62, 'max_depth': 18}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:34,773] Trial 32 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 146, 'max_depth': 17}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:36,551] Trial 33 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 192, 'max_depth': 10}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:38,175] Trial 34 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 174, 'max_depth': 12}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:39,528] Trial 35 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 145, 'max_depth': 11}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:41,048] Trial 36 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 171, 'max_depth': 20}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:42,030] Trial 37 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 115, 'max_depth': 6}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:43,709] Trial 38 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 187, 'max_depth': 9}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:44,659] Trial 39 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 110, 'max_depth': 20}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:45,162] Trial 40 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 53, 'max_depth': 12}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:45,774] Trial 41 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 63, 'max_depth': 14}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:46,330] Trial 42 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 60, 'max_depth': 20}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:47,690] Trial 43 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 160, 'max_depth': 6}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:48,702] Trial 44 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 129, 'max_depth': 3}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:49,760] Trial 45 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 118, 'max_depth': 15}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:50,920] Trial 46 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 126, 'max_depth': 14}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:52,418] Trial 47 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 175, 'max_depth': 15}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:53,365] Trial 48 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 106, 'max_depth': 13}. Best is trial 11 with value: 0.7821229050279329.
[I 2025-06-12 19:44:53,887] Trial 49 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 57, 'max_depth': 8}. Best is trial 11 with value: 0.7821229050279329.

In [13]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279329
Best hyperparameters: {'n_estimators': 119, 'max_depth': 20}

In [14]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

In [15]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [16]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2025-06-12 19:44:54,399] A new study created in memory with name: no-name-f515abf1-5662-43df-bc34-cbb55ec4ded9
[I 2025-06-12 19:44:55,218] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-06-12 19:44:56,608] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-06-12 19:44:57,085] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-12 19:44:58,010] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-12 19:44:58,933] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-12 19:44:59,386] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-12 19:45:00,629] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-12 19:45:02,008] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-12 19:45:03,347] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-12 19:45:05,157] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-12 19:45:07,075] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-12 19:45:08,793] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-12 19:45:10,451] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-12 19:45:10,880] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-06-12 19:45:11,784] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-06-12 19:45:12,252] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [17]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [18]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Optuna Visualizations

In [19]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [20]:
# 1. Optimization History
plot_optimization_history(study).show()

In [21]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [22]:
# 3. Slice Plot
plot_slice(study).show()

In [23]:
# 4. Contour Plot
plot_contour(study).show()

In [24]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [25]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [26]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [27]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-06-12 19:45:17,282] A new study created in memory with name: no-name-a547ce84-5237-428c-bb26-59c2b28454b9
[I 2025-06-12 19:45:17,366] Trial 0 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 79.43014362006525, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 0 with value: 0.7150837988826816.
[I 2025-06-12 19:45:18,213] Trial 1 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 96, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 1 with value: 0.7635009310986964.
[I 2025-06-12 19:45:20,416] Trial 2 finished with value: 0.7560521415270017 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 226, 'learning_rate': 0.06246844123232072, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 8}. Best is trial 1 with value: 0.7635009310986964.
[I 2025-06-12 19:45:22,253] Trial 3 finished with value: 0.7430167597765363 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 92, 'learning_rate': 0.16399739280849648, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 9}. Best is trial 1 with value: 0.7635009310986964.
[I 2025-06-12 19:45:22,311] Trial 4 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.18938598430833642, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-06-12 19:45:26,877] Trial 5 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 171, 'learning_rate': 0.023214287021776643, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 4 with value: 0.7746741154562384.
[I 2025-06-12 19:45:27,848] Trial 6 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 140, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 6 with value: 0.7783985102420856.
[I 2025-06-12 19:45:28,996] Trial 7 finished with value: 0.7597765363128491 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 73, 'learning_rate': 0.01323141822682937, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.7783985102420856.
[I 2025-06-12 19:45:30,206] Trial 8 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 183, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 6 with value: 0.7783985102420856.
[I 2025-06-12 19:45:30,326] Trial 9 finished with value: 0.6852886405959032 and parameters: {'classifier': 'SVM', 'C': 60.916694052378084, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 6 with value: 0.7783985102420856.
[I 2025-06-12 19:45:32,400] Trial 10 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 6 with value: 0.7783985102420856.
[I 2025-06-12 19:45:32,461] Trial 11 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.15011721391495328, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 6 with value: 0.7783985102420856.
[I 2025-06-12 19:45:32,516] Trial 12 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.164002447927585, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 6 with value: 0.7783985102420856.
[I 2025-06-12 19:45:33,614] Trial 13 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 145, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 6 with value: 0.7783985102420856.
[I 2025-06-12 19:45:33,684] Trial 14 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.3577921184225454, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2025-06-12 19:45:35,973] Trial 15 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 235, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.7858472998137801.
[I 2025-06-12 19:45:36,998] Trial 16 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 130, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 14 with value: 0.7858472998137801.
[I 2025-06-12 19:45:37,080] Trial 17 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.4130194218844894, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2025-06-12 19:45:37,158] Trial 18 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.293407147844371, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2025-06-12 19:45:37,238] Trial 19 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.4425022507005854, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2025-06-12 19:45:37,302] Trial 20 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.1203334670318426, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2025-06-12 19:45:37,372] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.7918475857458684, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2025-06-12 19:45:37,488] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.705409602370485, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2025-06-12 19:45:37,555] Trial 23 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.3833508218012476, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2025-06-12 19:45:37,740] Trial 24 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 10.739431981142687, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2025-06-12 19:45:37,794] Trial 25 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.9050516180677786, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:37,865] Trial 26 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.5272873049744259, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:37,929] Trial 27 finished with value: 0.7318435754189944 and parameters: {'classifier': 'SVM', 'C': 0.9323699142297943, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:38,060] Trial 28 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.393685099699757, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:38,119] Trial 29 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4477771004443354, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:38,190] Trial 30 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.9802479100162025, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:38,278] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.931049884169741, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:38,377] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.2048972114183325, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:38,557] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 21.182432061755392, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:42,264] Trial 34 finished with value: 0.7653631284916201 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 293, 'learning_rate': 0.287588073248238, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:42,334] Trial 35 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.945628706891711, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:47,182] Trial 36 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 246, 'learning_rate': 0.05884543770778732, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:47,243] Trial 37 finished with value: 0.7411545623836128 and parameters: {'classifier': 'SVM', 'C': 0.5768653803986327, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:47,316] Trial 38 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 2.081800882642994, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:49,095] Trial 39 finished with value: 0.7039106145251397 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 53, 'learning_rate': 0.01110523838054017, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:49,203] Trial 40 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.22079682075911, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:49,290] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.4430789184853228, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:49,362] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.8668067560118176, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:49,427] Trial 43 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8603813727398266, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:49,487] Trial 44 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7888845673340488, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:49,564] Trial 45 finished with value: 0.7690875232774674 and parameters: {'classifier': 'SVM', 'C': 0.8325897946791166, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:54,634] Trial 46 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 200, 'learning_rate': 0.11169844135514571, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:54,698] Trial 47 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4378408074034252, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:57,409] Trial 48 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 265, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:57,490] Trial 49 finished with value: 0.7597765363128491 and parameters: {'classifier': 'SVM', 'C': 0.30365810851847014, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:57,576] Trial 50 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.4130608003269045, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:57,653] Trial 51 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.67928965623985, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:57,712] Trial 52 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24950201625656102, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:57,778] Trial 53 finished with value: 0.707635009310987 and parameters: {'classifier': 'SVM', 'C': 0.10982839519259996, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:58,873] Trial 54 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 115, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:58,939] Trial 55 finished with value: 0.7616387337057727 and parameters: {'classifier': 'SVM', 'C': 0.24930731660498917, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:58,997] Trial 56 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8183094277911329, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:59,050] Trial 57 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6310742521852333, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:59,103] Trial 58 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.320586875137053, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:45:59,158] Trial 59 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7866084057922137, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:01,005] Trial 60 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 208, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:01,078] Trial 61 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7069777631644144, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:01,142] Trial 62 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.24451609052358, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:01,215] Trial 63 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19245793685645426, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:01,270] Trial 64 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.3449152541838849, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:01,340] Trial 65 finished with value: 0.7523277467411545 and parameters: {'classifier': 'SVM', 'C': 0.6962839826330408, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:01,406] Trial 66 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.1288896401624786, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:01,466] Trial 67 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22230536507743795, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:05,290] Trial 68 finished with value: 0.7597765363128491 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 170, 'learning_rate': 0.029275044019847596, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 8}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:05,360] Trial 69 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.5765122133888629, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:05,415] Trial 70 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.44641379183789104, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:05,471] Trial 71 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.36568221869346645, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:05,524] Trial 72 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.27934545928078314, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 25 with value: 0.7858472998137803.
[I 2025-06-12 19:46:05,589] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1296449261075851, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 73 with value: 0.7895716945996275.
[I 2025-06-12 19:46:05,644] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1489866096135214, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 73 with value: 0.7895716945996275.
[I 2025-06-12 19:46:05,703] Trial 75 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12594684854995805, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 73 with value: 0.7895716945996275.
[I 2025-06-12 19:46:05,764] Trial 76 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 0.13595399557064045, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 73 with value: 0.7895716945996275.
[I 2025-06-12 19:46:05,818] Trial 77 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.141535321517603, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 73 with value: 0.7895716945996275.
[I 2025-06-12 19:46:05,872] Trial 78 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10218423223505209, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 73 with value: 0.7895716945996275.
[I 2025-06-12 19:46:07,946] Trial 79 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 258, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 73 with value: 0.7895716945996275.
[I 2025-06-12 19:46:07,998] Trial 80 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10623990686127244, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 73 with value: 0.7895716945996275.
[I 2025-06-12 19:46:08,049] Trial 81 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10331011749973172, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 73 with value: 0.7895716945996275.

In [28]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.1296449261075851, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [29]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.715084,2025-06-12 19:45:17.285302,2025-06-12 19:45:17.366159,0 days 00:00:00.080857,79.430144,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.763501,2025-06-12 19:45:17.368846,2025-06-12 19:45:18.213078,0 days 00:00:00.844232,NaN,True,RandomForest,NaN,NaN,NaN,18.0,4.0,8.0,96.0,COMPLETE
2,2,0.756052,2025-06-12 19:45:18.215614,2025-06-12 19:45:20.415257,0 days 00:00:02.199643,NaN,NaN,GradientBoosting,NaN,NaN,0.062468,4.0,8.0,10.0,226.0,COMPLETE
3,3,0.743017,2025-06-12 19:45:20.417607,2025-06-12 19:45:22.252498,0 days 00:00:01.834891,NaN,NaN,GradientBoosting,NaN,NaN,0.163997,17.0,9.0,10.0,92.0,COMPLETE
4,4,0.774674,2025-06-12 19:45:22.254027,2025-06-12 19:45:22.309920,0 days 00:00:00.055893,0.189386,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.789572,2025-06-12 19:46:18.117761,2025-06-12 19:46:18.171919,0 days 00:00:00.054158,0.133281,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.770950,2025-06-12 19:46:18.174036,2025-06-12 19:46:18.237622,0 days 00:00:00.063586,0.170020,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.715084,2025-06-12 19:46:18.239616,2025-06-12 19:46:18.293858,0 days 00:00:00.054242,0.200777,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.789572,2025-06-12 19:46:18.294871,2025-06-12 19:46:18.345865,0 days 00:00:00.050994,0.130062,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.754190,2025-06-12 19:46:18.347867,2025-06-12 19:46:18.853875,0 days 00:00:00.506008,NaN,True,RandomForest,NaN,NaN,NaN,11.0,7.0,5.0,54.0,COMPLETE

In [30]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 78
RandomForest        12
GradientBoosting    10
Name: count, dtype: int64

In [31]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.747300
RandomForest        0.765518
SVM                 0.776942
Name: value, dtype: float64

In [32]:
# 1. Optimization History
plot_optimization_history(study).show()

In [33]:
# 3. Slice Plot
plot_slice(study).show()

In [34]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [37]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2025-06-12 19:47:37,706] A new study created in memory with name: no-name-a54337c3-f2db-41bd-a970-a65e710ff272

[0]	train-mlogloss:0.98219	eval-mlogloss:0.98365
[1]	train-mlogloss:0.89456	eval-mlogloss:0.88559
[2]	train-mlogloss:0.80735	eval-mlogloss:0.79107
[3]	train-mlogloss:0.72517	eval-mlogloss:0.70520
[4]	train-mlogloss:0.66029	eval-mlogloss:0.63920
[5]	train-mlogloss:0.59872	eval-mlogloss:0.57221
[6]	train-mlogloss:0.54574	eval-mlogloss:0.51337
[7]	train-mlogloss:0.50490	eval-mlogloss:0.47294
[8]	train-mlogloss:0.46813	eval-mlogloss:0.43165
[9]	train-mlogloss:0.43003	eval-mlogloss:0.39228
[10]	train-mlogloss:0.39698	eval-mlogloss:0.35804
[11]	train-mlogloss:0.36852	eval-mlogloss:0.32748
[12]	train-mlogloss:0.34442	eval-mlogloss:0.30162
[13]	train-mlogloss:0.32318	eval-mlogloss:0.27785
[14]	train-mlogloss:0.30742	eval-mlogloss:0.26131
[15]	train-mlogloss:0.28945	eval-mlogloss:0.24116
[16]	train-mlogloss:0.27587	eval-mlogloss:0.22584
[17]	train-mlogloss:0.26408	eval-mlogloss:0.21296
[18]	train-mlogloss:0.25272	eval-mlogloss:0.20033
[19]	train-mlogloss:0.24479	eval-mlogloss:0.19096
[20]	train-mlogloss:0.23730	eval-mlogloss:0.18188
[21]	train-mlogloss:0.22897	eval-mlogloss:0.17062
[22]	train-mlogloss:0.22656	eval-mlogloss:0.16750
[23]	train-mlogloss:0.21910	eval-mlogloss:0.15873
[24]	train-mlogloss:0.21266	eval-mlogloss:0.15043
[25]	train-mlogloss:0.20886	eval-mlogloss:0.14545
[26]	train-mlogloss:0.20662	eval-mlogloss:0.14286
[27]	train-mlogloss:0.20623	eval-mlogloss:0.14267
[28]	train-mlogloss:0.20608	eval-mlogloss:0.14237
[29]	train-mlogloss:0.20553	eval-mlogloss:0.14163
[30]	train-mlogloss:0.20215	eval-mlogloss:0.13776
[31]	train-mlogloss:0.20153	eval-mlogloss:0.13694
[32]	train-mlogloss:0.20134	eval-mlogloss:0.13676
[33]	train-mlogloss:0.20125	eval-mlogloss:0.13709
[34]	train-mlogloss:0.20103	eval-mlogloss:0.13693
[35]	train-mlogloss:0.20048	eval-mlogloss:0.13671
[36]	train-mlogloss:0.20051	eval-mlogloss:0.13677
[37]	train-mlogloss:0.19810	eval-mlogloss:0.13415
[38]	train-mlogloss:0.19804	eval-mlogloss:0.13415
[39]	train-mlogloss:0.19803	eval-mlogloss:0.13415
[40]	train-mlogloss:0.19757	eval-mlogloss:0.13394
[41]	train-mlogloss:0.19721	eval-mlogloss:0.13348
[42]	train-mlogloss:0.19713	eval-mlogloss:0.13336
[43]	train-mlogloss:0.19723	eval-mlogloss:0.13355
[44]	train-mlogloss:0.19722	eval-mlogloss:0.13355
[45]	train-mlogloss:0.19692	eval-mlogloss:0.13321
[46]	train-mlogloss:0.19638	eval-mlogloss:0.13222
[47]	train-mlogloss:0.19642	eval-mlogloss:0.13253
[48]	train-mlogloss:0.19628	eval-mlogloss:0.13196
[49]	train-mlogloss:0.19589	eval-mlogloss:0.13125
[50]	train-mlogloss:0.19331	eval-mlogloss:0.12755
[51]	train-mlogloss:0.19308	eval-mlogloss:0.12598
[52]	train-mlogloss:0.19319	eval-mlogloss:0.12614
[53]	train-mlogloss:0.19315	eval-mlogloss:0.12592
[54]	train-mlogloss:0.19301	eval-mlogloss:0.12569
[55]	train-mlogloss:0.19286	eval-mlogloss:0.12551
[56]	train-mlogloss:0.19275	eval-mlogloss:0.12514
[57]	train-mlogloss:0.19231	eval-mlogloss:0.12442
[58]	train-mlogloss:0.19124	eval-mlogloss:0.12321
[59]	train-mlogloss:0.19101	eval-mlogloss:0.12303
[60]	train-mlogloss:0.19090	eval-mlogloss:0.12296
[61]	train-mlogloss:0.19062	eval-mlogloss:0.12272
[62]	train-mlogloss:0.19029	eval-mlogloss:0.12272
[63]	train-mlogloss:0.19028	eval-mlogloss:0.12264
[64]	train-mlogloss:0.19010	eval-mlogloss:0.12253
[65]	train-mlogloss:0.19025	eval-mlogloss:0.12277
[66]	train-mlogloss:0.18991	eval-mlogloss:0.12234
[67]	train-mlogloss:0.18984	eval-mlogloss:0.12231
[68]	train-mlogloss:0.18986	eval-mlogloss:0.12230
[69]	train-mlogloss:0.18716	eval-mlogloss:0.11876
[70]	train-mlogloss:0.18701	eval-mlogloss:0.11867
[71]	train-mlogloss:0.18687	eval-mlogloss:0.11848
[72]	train-mlogloss:0.18686	eval-mlogloss:0.11838
[73]	train-mlogloss:0.18659	eval-mlogloss:0.11787
[74]	train-mlogloss:0.18653	eval-mlogloss:0.11811
[75]	train-mlogloss:0.18653	eval-mlogloss:0.11810
[76]	train-mlogloss:0.18658	eval-mlogloss:0.11812
[77]	train-mlogloss:0.18626	eval-mlogloss:0.11747
[78]	train-mlogloss:0.18635	eval-mlogloss:0.11740
[79]	train-mlogloss:0.18637	eval-mlogloss:0.11750
[80]	train-mlogloss:0.18619	eval-mlogloss:0.11740
[81]	train-mlogloss:0.18619	eval-mlogloss:0.11748
[82]	train-mlogloss:0.18617	eval-mlogloss:0.11746
[83]	train-mlogloss:0.18618	eval-mlogloss:0.11747
[84]	train-mlogloss:0.18419	eval-mlogloss:0.11545
[85]	train-mlogloss:0.18412	eval-mlogloss:0.11533
[86]	train-mlogloss:0.18412	eval-mlogloss:0.11537
[87]	train-mlogloss:0.18413	eval-mlogloss:0.11538
[88]	train-mlogloss:0.18385	eval-mlogloss:0.11525
[89]	train-mlogloss:0.18382	eval-mlogloss:0.11518
[90]	train-mlogloss:0.18383	eval-mlogloss:0.11519
[91]	train-mlogloss:0.18372	eval-mlogloss:0.11517
[92]	train-mlogloss:0.18364	eval-mlogloss:0.11505
[93]	train-mlogloss:0.18360	eval-mlogloss:0.11495
[94]	train-mlogloss:0.18359	eval-mlogloss:0.11491
[95]	train-mlogloss:0.18382	eval-mlogloss:0.11571
[96]	train-mlogloss:0.18390	eval-mlogloss:0.11585
[97]	train-mlogloss:0.18387	eval-mlogloss:0.11577
[98]	train-mlogloss:0.18381	eval-mlogloss:0.11604
[99]	train-mlogloss:0.18302	eval-mlogloss:0.11611
[100]	train-mlogloss:0.18292	eval-mlogloss:0.11590
[101]	train-mlogloss:0.18146	eval-mlogloss:0.11448
[102]	train-mlogloss:0.18147	eval-mlogloss:0.11452
[103]	train-mlogloss:0.18151	eval-mlogloss:0.11458
[104]	train-mlogloss:0.18157	eval-mlogloss:0.11466
[105]	train-mlogloss:0.18135	eval-mlogloss:0.11431
[106]	train-mlogloss:0.18144	eval-mlogloss:0.11449
[107]	train-mlogloss:0.18167	eval-mlogloss:0.11505
[108]	train-mlogloss:0.18151	eval-mlogloss:0.11504
[109]	train-mlogloss:0.18127	eval-mlogloss:0.11466
[110]	train-mlogloss:0.18133	eval-mlogloss:0.11478
[111]	train-mlogloss:0.18115	eval-mlogloss:0.11453
[112]	train-mlogloss:0.18099	eval-mlogloss:0.11429
[113]	train-mlogloss:0.18069	eval-mlogloss:0.11271
[114]	train-mlogloss:0.18057	eval-mlogloss:0.11155
[115]	train-mlogloss:0.18056	eval-mlogloss:0.11162
[116]	train-mlogloss:0.18058	eval-mlogloss:0.11169
[117]	train-mlogloss:0.18044	eval-mlogloss:0.11098
[118]	train-mlogloss:0.18035	eval-mlogloss:0.11089
[119]	train-mlogloss:0.18024	eval-mlogloss:0.11085
[120]	train-mlogloss:0.17986	eval-mlogloss:0.11047
[121]	train-mlogloss:0.17989	eval-mlogloss:0.11083
[122]	train-mlogloss:0.17997	eval-mlogloss:0.11097
[123]	train-mlogloss:0.17929	eval-mlogloss:0.11063
[124]	train-mlogloss:0.17731	eval-mlogloss:0.10778
[125]	train-mlogloss:0.17723	eval-mlogloss:0.10774
[126]	train-mlogloss:0.17705	eval-mlogloss:0.10763
[127]	train-mlogloss:0.17713	eval-mlogloss:0.10759
[128]	train-mlogloss:0.17700	eval-mlogloss:0.10758
[129]	train-mlogloss:0.17680	eval-mlogloss:0.10752
[130]	train-mlogloss:0.17696	eval-mlogloss:0.10773
[131]	train-mlogloss:0.17703	eval-mlogloss:0.10790
[132]	train-mlogloss:0.17578	eval-mlogloss:0.10602
[133]	train-mlogloss:0.17569	eval-mlogloss:0.10588
[134]	train-mlogloss:0.17565	eval-mlogloss:0.10584
[135]	train-mlogloss:0.17561	eval-mlogloss:0.10580
[136]	train-mlogloss:0.17563	eval-mlogloss:0.10584
[137]	train-mlogloss:0.17559	eval-mlogloss:0.10577
[138]	train-mlogloss:0.17537	eval-mlogloss:0.10560
[139]	train-mlogloss:0.17539	eval-mlogloss:0.10552
[140]	train-mlogloss:0.17528	eval-mlogloss:0.10537
[141]	train-mlogloss:0.17528	eval-mlogloss:0.10536
[142]	train-mlogloss:0.17541	eval-mlogloss:0.10563
[143]	train-mlogloss:0.17544	eval-mlogloss:0.10569
[144]	train-mlogloss:0.17528	eval-mlogloss:0.10548
[145]	train-mlogloss:0.17545	eval-mlogloss:0.10570
[146]	train-mlogloss:0.17532	eval-mlogloss:0.10543
[147]	train-mlogloss:0.17529	eval-mlogloss:0.10498
[148]	train-mlogloss:0.17529	eval-mlogloss:0.10506
[149]	train-mlogloss:0.17528	eval-mlogloss:0.10504
[150]	train-mlogloss:0.17518	eval-mlogloss:0.10460
[151]	train-mlogloss:0.17514	eval-mlogloss:0.10456
[152]	train-mlogloss:0.17520	eval-mlogloss:0.10461
[153]	train-mlogloss:0.17517	eval-mlogloss:0.10451
[154]	train-mlogloss:0.17484	eval-mlogloss:0.10405
[155]	train-mlogloss:0.17474	eval-mlogloss:0.10406
[156]	train-mlogloss:0.17477	eval-mlogloss:0.10408
[157]	train-mlogloss:0.17476	eval-mlogloss:0.10408
[158]	train-mlogloss:0.17472	eval-mlogloss:0.10410
[159]	train-mlogloss:0.17469	eval-mlogloss:0.10412
[160]	train-mlogloss:0.17471	eval-mlogloss:0.10409
[161]	train-mlogloss:0.17467	eval-mlogloss:0.10417
[162]	train-mlogloss:0.17469	eval-mlogloss:0.10419
[163]	train-mlogloss:0.17474	eval-mlogloss:0.10420
[164]	train-mlogloss:0.17453	eval-mlogloss:0.10410
[165]	train-mlogloss:0.17449	eval-mlogloss:0.10411
[166]	train-mlogloss:0.17431	eval-mlogloss:0.10389
[167]	train-mlogloss:0.17431	eval-mlogloss:0.10390
[168]	train-mlogloss:0.17430	eval-mlogloss:0.10397
[169]	train-mlogloss:0.17431	eval-mlogloss:0.10398
[170]	train-mlogloss:0.17431	eval-mlogloss:0.10401
[171]	train-mlogloss:0.17434	eval-mlogloss:0.10410
[172]	train-mlogloss:0.17435	eval-mlogloss:0.10452
[173]	train-mlogloss:0.17436	eval-mlogloss:0.10453
[174]	train-mlogloss:0.17437	eval-mlogloss:0.10417
[175]	train-mlogloss:0.17436	eval-mlogloss:0.10407
[176]	train-mlogloss:0.17436	eval-mlogloss:0.10401
[177]	train-mlogloss:0.17428	eval-mlogloss:0.10394
[178]	train-mlogloss:0.17392	eval-mlogloss:0.10326
[179]	train-mlogloss:0.17398	eval-mlogloss:0.10329
[180]	train-mlogloss:0.17413	eval-mlogloss:0.10343
[181]	train-mlogloss:0.17400	eval-mlogloss:0.10338
[182]	train-mlogloss:0.17392	eval-mlogloss:0.10320
[183]	train-mlogloss:0.17394	eval-mlogloss:0.10332
[184]	train-mlogloss:0.17385	eval-mlogloss:0.10338
[185]	train-mlogloss:0.17388	eval-mlogloss:0.10348
[186]	train-mlogloss:0.17353	eval-mlogloss:0.10277
[187]	train-mlogloss:0.17354	eval-mlogloss:0.10268
[188]	train-mlogloss:0.17353	eval-mlogloss:0.10281
[189]	train-mlogloss:0.17353	eval-mlogloss:0.10293
[190]	train-mlogloss:0.17354	eval-mlogloss:0.10300
[191]	train-mlogloss:0.17350	eval-mlogloss:0.10290
[192]	train-mlogloss:0.17349	eval-mlogloss:0.10294
[193]	train-mlogloss:0.17345	eval-mlogloss:0.10284
[194]	train-mlogloss:0.17347	eval-mlogloss:0.10296
[195]	train-mlogloss:0.17347	eval-mlogloss:0.10289
[196]	train-mlogloss:0.17349	eval-mlogloss:0.10292
[197]	train-mlogloss:0.17345	eval-mlogloss:0.10285
[198]	train-mlogloss:0.17361	eval-mlogloss:0.10280
[199]	train-mlogloss:0.17360	eval-mlogloss:0.10268
[200]	train-mlogloss:0.17361	eval-mlogloss:0.10267
[201]	train-mlogloss:0.17368	eval-mlogloss:0.10263
[202]	train-mlogloss:0.17366	eval-mlogloss:0.10263
[203]	train-mlogloss:0.17364	eval-mlogloss:0.10264
[204]	train-mlogloss:0.17365	eval-mlogloss:0.10264
[205]	train-mlogloss:0.17368	eval-mlogloss:0.10254
[206]	train-mlogloss:0.17363	eval-mlogloss:0.10274
[207]	train-mlogloss:0.17362	eval-mlogloss:0.10273
[208]	train-mlogloss:0.17360	eval-mlogloss:0.10278
[209]	train-mlogloss:0.17373	eval-mlogloss:0.10295
[210]	train-mlogloss:0.17367	eval-mlogloss:0.10292
[211]	train-mlogloss:0.17367	eval-mlogloss:0.10292
[212]	train-mlogloss:0.17358	eval-mlogloss:0.10295
[213]	train-mlogloss:0.17356	eval-mlogloss:0.10298
[214]	train-mlogloss:0.17358	eval-mlogloss:0.10295
[215]	train-mlogloss:0.17345	eval-mlogloss:0.10277
[216]	train-mlogloss:0.17346	eval-mlogloss:0.10274
[217]	train-mlogloss:0.17340	eval-mlogloss:0.10200
[218]	train-mlogloss:0.17341	eval-mlogloss:0.10209
[219]	train-mlogloss:0.17342	eval-mlogloss:0.10204
[220]	train-mlogloss:0.17339	eval-mlogloss:0.10204
[221]	train-mlogloss:0.17340	eval-mlogloss:0.10213
[222]	train-mlogloss:0.17323	eval-mlogloss:0.10199
[223]	train-mlogloss:0.17321	eval-mlogloss:0.10196
[224]	train-mlogloss:0.17322	eval-mlogloss:0.10203
[225]	train-mlogloss:0.17323	eval-mlogloss:0.10209
[226]	train-mlogloss:0.17320	eval-mlogloss:0.10192
[227]	train-mlogloss:0.17294	eval-mlogloss:0.10177
[228]	train-mlogloss:0.17293	eval-mlogloss:0.10171
[229]	train-mlogloss:0.17303	eval-mlogloss:0.10195
[230]	train-mlogloss:0.17306	eval-mlogloss:0.10130
[231]	train-mlogloss:0.17308	eval-mlogloss:0.10130
[232]	train-mlogloss:0.17305	eval-mlogloss:0.10129
[233]	train-mlogloss:0.17295	eval-mlogloss:0.10106
[234]	train-mlogloss:0.17304	eval-mlogloss:0.10129
[235]	train-mlogloss:0.17311	eval-mlogloss:0.10140
[236]	train-mlogloss:0.17301	eval-mlogloss:0.10147
[237]	train-mlogloss:0.17300	eval-mlogloss:0.10144
[238]	train-mlogloss:0.17284	eval-mlogloss:0.10128
[239]	train-mlogloss:0.17271	eval-mlogloss:0.10107
[240]	train-mlogloss:0.17272	eval-mlogloss:0.10113
[241]	train-mlogloss:0.17268	eval-mlogloss:0.10155
[242]	train-mlogloss:0.17273	eval-mlogloss:0.10165
[243]	train-mlogloss:0.17270	eval-mlogloss:0.10159
[244]	train-mlogloss:0.17268	eval-mlogloss:0.10154
[245]	train-mlogloss:0.17263	eval-mlogloss:0.10145
[246]	train-mlogloss:0.17258	eval-mlogloss:0.10118
[247]	train-mlogloss:0.17258	eval-mlogloss:0.10123
[248]	train-mlogloss:0.17258	eval-mlogloss:0.10118
[249]	train-mlogloss:0.17258	eval-mlogloss:0.10112
[250]	train-mlogloss:0.17260	eval-mlogloss:0.10110
[251]	train-mlogloss:0.17263	eval-mlogloss:0.10102
[252]	train-mlogloss:0.17268	eval-mlogloss:0.10093
[253]	train-mlogloss:0.17267	eval-mlogloss:0.10094
[254]	train-mlogloss:0.17269	eval-mlogloss:0.10186
[255]	train-mlogloss:0.17267	eval-mlogloss:0.10190
[256]	train-mlogloss:0.17268	eval-mlogloss:0.10189
[257]	train-mlogloss:0.17268	eval-mlogloss:0.10187
[258]	train-mlogloss:0.17276	eval-mlogloss:0.10179
[259]	train-mlogloss:0.17280	eval-mlogloss:0.10177
[260]	train-mlogloss:0.17282	eval-mlogloss:0.10177
[261]	train-mlogloss:0.17282	eval-mlogloss:0.10176
[262]	train-mlogloss:0.17272	eval-mlogloss:0.10118
[263]	train-mlogloss:0.17273	eval-mlogloss:0.10118
[264]	train-mlogloss:0.17273	eval-mlogloss:0.10118
[265]	train-mlogloss:0.17267	eval-mlogloss:0.10122
[266]	train-mlogloss:0.17265	eval-mlogloss:0.10124
[267]	train-mlogloss:0.17266	eval-mlogloss:0.10123
[268]	train-mlogloss:0.17257	eval-mlogloss:0.10123
[269]	train-mlogloss:0.17255	eval-mlogloss:0.10125
[270]	train-mlogloss:0.17245	eval-mlogloss:0.10117
[271]	train-mlogloss:0.17244	eval-mlogloss:0.10125
[272]	train-mlogloss:0.17242	eval-mlogloss:0.10149
[273]	train-mlogloss:0.17244	eval-mlogloss:0.10151
[274]	train-mlogloss:0.17245	eval-mlogloss:0.10158
[275]	train-mlogloss:0.17269	eval-mlogloss:0.10187
[276]	train-mlogloss:0.17265	eval-mlogloss:0.10178
[277]	train-mlogloss:0.17266	eval-mlogloss:0.10185
[278]	train-mlogloss:0.17270	eval-mlogloss:0.10185
[279]	train-mlogloss:0.17269	eval-mlogloss:0.10183
[280]	train-mlogloss:0.17265	eval-mlogloss:0.10172
[281]	train-mlogloss:0.17263	eval-mlogloss:0.10172
[282]	train-mlogloss:0.17256	eval-mlogloss:0.10183

[I 2025-06-12 19:47:39,560] Trial 0 finished with value: 1.0 and parameters: {'lambda': 0.0053756740193569574, 'alpha': 2.3961480124483085e-08, 'eta': 0.09531920517143157, 'gamma': 0.11584042713761838, 'max_depth': 9, 'min_child_weight': 5, 'subsample': 0.4928767937806364, 'colsample_bytree': 0.9666856335903532}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.80387	eval-mlogloss:0.80711
[1]	train-mlogloss:0.64810	eval-mlogloss:0.62496
[2]	train-mlogloss:0.50925	eval-mlogloss:0.47088
[3]	train-mlogloss:0.40284	eval-mlogloss:0.35442
[4]	train-mlogloss:0.35294	eval-mlogloss:0.30261
[5]	train-mlogloss:0.30908	eval-mlogloss:0.25246
[6]	train-mlogloss:0.27700	eval-mlogloss:0.21415
[7]	train-mlogloss:0.26666	eval-mlogloss:0.20378
[8]	train-mlogloss:0.26668	eval-mlogloss:0.20491
[9]	train-mlogloss:0.26568	eval-mlogloss:0.20068
[10]	train-mlogloss:0.25431	eval-mlogloss:0.18910
[11]	train-mlogloss:0.25415	eval-mlogloss:0.19029
[12]	train-mlogloss:0.25244	eval-mlogloss:0.18866
[13]	train-mlogloss:0.25164	eval-mlogloss:0.18820
[14]	train-mlogloss:0.25105	eval-mlogloss:0.18699
[15]	train-mlogloss:0.25105	eval-mlogloss:0.18665
[16]	train-mlogloss:0.25026	eval-mlogloss:0.18585
[17]	train-mlogloss:0.24996	eval-mlogloss:0.18570
[18]	train-mlogloss:0.25032	eval-mlogloss:0.18638
[19]	train-mlogloss:0.24987	eval-mlogloss:0.18615
[20]	train-mlogloss:0.24993	eval-mlogloss:0.18629
[21]	train-mlogloss:0.24944	eval-mlogloss:0.18479
[22]	train-mlogloss:0.24794	eval-mlogloss:0.18420
[23]	train-mlogloss:0.24793	eval-mlogloss:0.18428
[24]	train-mlogloss:0.24790	eval-mlogloss:0.18355
[25]	train-mlogloss:0.23809	eval-mlogloss:0.16999
[26]	train-mlogloss:0.23622	eval-mlogloss:0.16880
[27]	train-mlogloss:0.23623	eval-mlogloss:0.16888
[28]	train-mlogloss:0.23623	eval-mlogloss:0.16903
[29]	train-mlogloss:0.23626	eval-mlogloss:0.16914
[30]	train-mlogloss:0.23522	eval-mlogloss:0.16828
[31]	train-mlogloss:0.23474	eval-mlogloss:0.16822
[32]	train-mlogloss:0.23442	eval-mlogloss:0.16789
[33]	train-mlogloss:0.23418	eval-mlogloss:0.16737
[34]	train-mlogloss:0.23370	eval-mlogloss:0.16686
[35]	train-mlogloss:0.23368	eval-mlogloss:0.16704
[36]	train-mlogloss:0.23376	eval-mlogloss:0.16714
[37]	train-mlogloss:0.23342	eval-mlogloss:0.16838
[38]	train-mlogloss:0.23333	eval-mlogloss:0.16850
[39]	train-mlogloss:0.23335	eval-mlogloss:0.16862
[40]	train-mlogloss:0.23258	eval-mlogloss:0.16822
[41]	train-mlogloss:0.23231	eval-mlogloss:0.16810
[42]	train-mlogloss:0.23196	eval-mlogloss:0.16790
[43]	train-mlogloss:0.23223	eval-mlogloss:0.16843
[44]	train-mlogloss:0.23212	eval-mlogloss:0.16829
[45]	train-mlogloss:0.23166	eval-mlogloss:0.16756
[46]	train-mlogloss:0.23175	eval-mlogloss:0.16723
[47]	train-mlogloss:0.23161	eval-mlogloss:0.16663
[48]	train-mlogloss:0.23145	eval-mlogloss:0.16660
[49]	train-mlogloss:0.23136	eval-mlogloss:0.16494
[50]	train-mlogloss:0.22252	eval-mlogloss:0.15511
[51]	train-mlogloss:0.22219	eval-mlogloss:0.15469
[52]	train-mlogloss:0.22213	eval-mlogloss:0.15462
[53]	train-mlogloss:0.22210	eval-mlogloss:0.15438
[54]	train-mlogloss:0.22178	eval-mlogloss:0.15341
[55]	train-mlogloss:0.22149	eval-mlogloss:0.15317
[56]	train-mlogloss:0.22139	eval-mlogloss:0.15214
[57]	train-mlogloss:0.22153	eval-mlogloss:0.15223
[58]	train-mlogloss:0.22160	eval-mlogloss:0.15239
[59]	train-mlogloss:0.22135	eval-mlogloss:0.15240
[60]	train-mlogloss:0.22118	eval-mlogloss:0.15222
[61]	train-mlogloss:0.22081	eval-mlogloss:0.15190
[62]	train-mlogloss:0.22071	eval-mlogloss:0.15195
[63]	train-mlogloss:0.22061	eval-mlogloss:0.15146
[64]	train-mlogloss:0.22060	eval-mlogloss:0.15142
[65]	train-mlogloss:0.22107	eval-mlogloss:0.15249
[66]	train-mlogloss:0.22059	eval-mlogloss:0.15095
[67]	train-mlogloss:0.22050	eval-mlogloss:0.15106
[68]	train-mlogloss:0.22053	eval-mlogloss:0.15111
[69]	train-mlogloss:0.22007	eval-mlogloss:0.15039
[70]	train-mlogloss:0.22007	eval-mlogloss:0.15034
[71]	train-mlogloss:0.22020	eval-mlogloss:0.15074
[72]	train-mlogloss:0.22017	eval-mlogloss:0.15038
[73]	train-mlogloss:0.22012	eval-mlogloss:0.15051
[74]	train-mlogloss:0.22008	eval-mlogloss:0.15144
[75]	train-mlogloss:0.22034	eval-mlogloss:0.15181
[76]	train-mlogloss:0.22045	eval-mlogloss:0.15176
[77]	train-mlogloss:0.22010	eval-mlogloss:0.15148
[78]	train-mlogloss:0.22046	eval-mlogloss:0.15218
[79]	train-mlogloss:0.22048	eval-mlogloss:0.15225
[80]	train-mlogloss:0.22032	eval-mlogloss:0.15199
[81]	train-mlogloss:0.22028	eval-mlogloss:0.15195
[82]	train-mlogloss:0.22014	eval-mlogloss:0.15165
[83]	train-mlogloss:0.21999	eval-mlogloss:0.15135
[84]	train-mlogloss:0.21979	eval-mlogloss:0.15147
[85]	train-mlogloss:0.21958	eval-mlogloss:0.15092
[86]	train-mlogloss:0.21961	eval-mlogloss:0.15105
[87]	train-mlogloss:0.21936	eval-mlogloss:0.15083
[88]	train-mlogloss:0.21913	eval-mlogloss:0.15051
[89]	train-mlogloss:0.21907	eval-mlogloss:0.15023
[90]	train-mlogloss:0.21914	eval-mlogloss:0.15048
[91]	train-mlogloss:0.21934	eval-mlogloss:0.15098
[92]	train-mlogloss:0.21925	eval-mlogloss:0.15077
[93]	train-mlogloss:0.21916	eval-mlogloss:0.15038
[94]	train-mlogloss:0.21926	eval-mlogloss:0.15066
[95]	train-mlogloss:0.21945	eval-mlogloss:0.15116
[96]	train-mlogloss:0.21880	eval-mlogloss:0.15064
[97]	train-mlogloss:0.21867	eval-mlogloss:0.15037
[98]	train-mlogloss:0.21920	eval-mlogloss:0.15129
[99]	train-mlogloss:0.21883	eval-mlogloss:0.15054
[100]	train-mlogloss:0.21871	eval-mlogloss:0.15012
[101]	train-mlogloss:0.21844	eval-mlogloss:0.14975
[102]	train-mlogloss:0.21843	eval-mlogloss:0.14982
[103]	train-mlogloss:0.21852	eval-mlogloss:0.15012
[104]	train-mlogloss:0.21878	eval-mlogloss:0.15049
[105]	train-mlogloss:0.21825	eval-mlogloss:0.14919
[106]	train-mlogloss:0.21829	eval-mlogloss:0.14975
[107]	train-mlogloss:0.21864	eval-mlogloss:0.15060
[108]	train-mlogloss:0.21830	eval-mlogloss:0.14985
[109]	train-mlogloss:0.21823	eval-mlogloss:0.14958
[110]	train-mlogloss:0.21831	eval-mlogloss:0.14986
[111]	train-mlogloss:0.21829	eval-mlogloss:0.14970
[112]	train-mlogloss:0.21823	eval-mlogloss:0.14918
[113]	train-mlogloss:0.21827	eval-mlogloss:0.14919
[114]	train-mlogloss:0.21827	eval-mlogloss:0.14948
[115]	train-mlogloss:0.21829	eval-mlogloss:0.14957
[116]	train-mlogloss:0.21838	eval-mlogloss:0.15000
[117]	train-mlogloss:0.21846	eval-mlogloss:0.15072
[118]	train-mlogloss:0.21830	eval-mlogloss:0.15034
[119]	train-mlogloss:0.21830	eval-mlogloss:0.15019
[120]	train-mlogloss:0.21859	eval-mlogloss:0.15046
[121]	train-mlogloss:0.21849	eval-mlogloss:0.15177
[122]	train-mlogloss:0.21840	eval-mlogloss:0.15165
[123]	train-mlogloss:0.21870	eval-mlogloss:0.15199
[124]	train-mlogloss:0.21898	eval-mlogloss:0.15231
[125]	train-mlogloss:0.21901	eval-mlogloss:0.15264
[126]	train-mlogloss:0.21843	eval-mlogloss:0.15205
[127]	train-mlogloss:0.21869	eval-mlogloss:0.15248
[128]	train-mlogloss:0.21881	eval-mlogloss:0.15333
[129]	train-mlogloss:0.21834	eval-mlogloss:0.15281
[130]	train-mlogloss:0.21885	eval-mlogloss:0.15364
[131]	train-mlogloss:0.21867	eval-mlogloss:0.15344
[132]	train-mlogloss:0.21807	eval-mlogloss:0.15234
[133]	train-mlogloss:0.21804	eval-mlogloss:0.15220
[134]	train-mlogloss:0.21800	eval-mlogloss:0.15207
[135]	train-mlogloss:0.21795	eval-mlogloss:0.15251
[136]	train-mlogloss:0.21804	eval-mlogloss:0.15266
[137]	train-mlogloss:0.21797	eval-mlogloss:0.15250
[138]	train-mlogloss:0.21732	eval-mlogloss:0.15199
[139]	train-mlogloss:0.21741	eval-mlogloss:0.15209
[140]	train-mlogloss:0.21719	eval-mlogloss:0.15164
[141]	train-mlogloss:0.21722	eval-mlogloss:0.15168
[142]	train-mlogloss:0.21750	eval-mlogloss:0.15244

[I 2025-06-12 19:47:40,524] Trial 1 finished with value: 1.0 and parameters: {'lambda': 0.002479850613871405, 'alpha': 2.3506377332967465e-05, 'eta': 0.2624896817846184, 'gamma': 0.016050865779911612, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.5437822011629895, 'colsample_bytree': 0.9067501840159709}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.97454	eval-mlogloss:0.97085
[1]	train-mlogloss:0.90220	eval-mlogloss:0.90291
[2]	train-mlogloss:0.81242	eval-mlogloss:0.80823
[3]	train-mlogloss:0.72732	eval-mlogloss:0.71638
[4]	train-mlogloss:0.65405	eval-mlogloss:0.63954
[5]	train-mlogloss:0.59066	eval-mlogloss:0.57257
[6]	train-mlogloss:0.53576	eval-mlogloss:0.51745
[7]	train-mlogloss:0.48896	eval-mlogloss:0.46661
[8]	train-mlogloss:0.44605	eval-mlogloss:0.42320
[9]	train-mlogloss:0.40706	eval-mlogloss:0.38741
[10]	train-mlogloss:0.37439	eval-mlogloss:0.35634
[11]	train-mlogloss:0.34409	eval-mlogloss:0.32533
[12]	train-mlogloss:0.31936	eval-mlogloss:0.29877
[13]	train-mlogloss:0.29550	eval-mlogloss:0.27433
[14]	train-mlogloss:0.27300	eval-mlogloss:0.25059
[15]	train-mlogloss:0.25611	eval-mlogloss:0.23313
[16]	train-mlogloss:0.24019	eval-mlogloss:0.21637
[17]	train-mlogloss:0.22313	eval-mlogloss:0.19806
[18]	train-mlogloss:0.21088	eval-mlogloss:0.18558
[19]	train-mlogloss:0.19693	eval-mlogloss:0.17213
[20]	train-mlogloss:0.18438	eval-mlogloss:0.16453
[21]	train-mlogloss:0.17347	eval-mlogloss:0.15274
[22]	train-mlogloss:0.16198	eval-mlogloss:0.13970
[23]	train-mlogloss:0.15099	eval-mlogloss:0.12679
[24]	train-mlogloss:0.14128	eval-mlogloss:0.11661
[25]	train-mlogloss:0.13331	eval-mlogloss:0.10922
[26]	train-mlogloss:0.12588	eval-mlogloss:0.10111
[27]	train-mlogloss:0.11896	eval-mlogloss:0.09386
[28]	train-mlogloss:0.11190	eval-mlogloss:0.08917
[29]	train-mlogloss:0.10732	eval-mlogloss:0.08615
[30]	train-mlogloss:0.10379	eval-mlogloss:0.08391
[31]	train-mlogloss:0.09932	eval-mlogloss:0.07979

[I 2025-06-12 19:47:40,749] Trial 2 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:0.99551	eval-mlogloss:0.99324
[1]	train-mlogloss:0.90757	eval-mlogloss:0.89840
[2]	train-mlogloss:0.82806	eval-mlogloss:0.81402
[3]	train-mlogloss:0.75831	eval-mlogloss:0.74263
[4]	train-mlogloss:0.69823	eval-mlogloss:0.68067
[5]	train-mlogloss:0.64277	eval-mlogloss:0.62067
[6]	train-mlogloss:0.59511	eval-mlogloss:0.57009
[7]	train-mlogloss:0.55176	eval-mlogloss:0.52261
[8]	train-mlogloss:0.51277	eval-mlogloss:0.48015
[9]	train-mlogloss:0.47678	eval-mlogloss:0.44325
[10]	train-mlogloss:0.44373	eval-mlogloss:0.40985
[11]	train-mlogloss:0.41433	eval-mlogloss:0.37777
[12]	train-mlogloss:0.38784	eval-mlogloss:0.34902
[13]	train-mlogloss:0.36307	eval-mlogloss:0.32346
[14]	train-mlogloss:0.34114	eval-mlogloss:0.29945
[15]	train-mlogloss:0.32113	eval-mlogloss:0.27838
[16]	train-mlogloss:0.30262	eval-mlogloss:0.25860
[17]	train-mlogloss:0.28652	eval-mlogloss:0.24152
[18]	train-mlogloss:0.27103	eval-mlogloss:0.22451
[19]	train-mlogloss:0.25738	eval-mlogloss:0.21018
[20]	train-mlogloss:0.24506	eval-mlogloss:0.19670
[21]	train-mlogloss:0.23369	eval-mlogloss:0.18395
[22]	train-mlogloss:0.22383	eval-mlogloss:0.17233
[23]	train-mlogloss:0.21439	eval-mlogloss:0.16267
[24]	train-mlogloss:0.20630	eval-mlogloss:0.15409
[25]	train-mlogloss:0.19807	eval-mlogloss:0.14473
[26]	train-mlogloss:0.19152	eval-mlogloss:0.13703
[27]	train-mlogloss:0.18538	eval-mlogloss:0.13070
[28]	train-mlogloss:0.17980	eval-mlogloss:0.12406
[29]	train-mlogloss:0.17767	eval-mlogloss:0.12111
[30]	train-mlogloss:0.17389	eval-mlogloss:0.11689
[31]	train-mlogloss:0.17177	eval-mlogloss:0.11448
[32]	train-mlogloss:0.16980	eval-mlogloss:0.11213

[I 2025-06-12 19:47:41,078] Trial 3 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:0.93108	eval-mlogloss:0.92158
[1]	train-mlogloss:0.85812	eval-mlogloss:0.84631

[I 2025-06-12 19:47:41,106] Trial 4 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.96117	eval-mlogloss:0.95295
[1]	train-mlogloss:0.90215	eval-mlogloss:0.89054
[2]	train-mlogloss:0.83077	eval-mlogloss:0.82422
[3]	train-mlogloss:0.72153	eval-mlogloss:0.70639
[4]	train-mlogloss:0.68870	eval-mlogloss:0.67076
[5]	train-mlogloss:0.63802	eval-mlogloss:0.61992
[6]	train-mlogloss:0.56313	eval-mlogloss:0.53741
[7]	train-mlogloss:0.49394	eval-mlogloss:0.45964
[8]	train-mlogloss:0.47084	eval-mlogloss:0.43669

[I 2025-06-12 19:47:41,172] Trial 5 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.93954	eval-mlogloss:0.93071
[1]	train-mlogloss:0.88067	eval-mlogloss:0.86354
[2]	train-mlogloss:0.79801	eval-mlogloss:0.79014

[I 2025-06-12 19:47:41,213] Trial 6 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.94391	eval-mlogloss:0.94657
[1]	train-mlogloss:0.86244	eval-mlogloss:0.86827

[I 2025-06-12 19:47:41,235] Trial 7 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.84261	eval-mlogloss:0.83243
[1]	train-mlogloss:0.75690	eval-mlogloss:0.72795

[I 2025-06-12 19:47:41,265] Trial 8 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.94693	eval-mlogloss:0.94853
[1]	train-mlogloss:0.84707	eval-mlogloss:0.83183

[I 2025-06-12 19:47:41,297] Trial 9 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06461	eval-mlogloss:1.06345
[1]	train-mlogloss:1.03241	eval-mlogloss:1.02911
[2]	train-mlogloss:1.00096	eval-mlogloss:0.99555
[3]	train-mlogloss:0.97026	eval-mlogloss:0.96425
[4]	train-mlogloss:0.94194	eval-mlogloss:0.93490
[5]	train-mlogloss:0.91420	eval-mlogloss:0.90514
[6]	train-mlogloss:0.88850	eval-mlogloss:0.87768
[7]	train-mlogloss:0.86349	eval-mlogloss:0.85109
[8]	train-mlogloss:0.83967	eval-mlogloss:0.82627
[9]	train-mlogloss:0.81631	eval-mlogloss:0.80124
[10]	train-mlogloss:0.79396	eval-mlogloss:0.77830
[11]	train-mlogloss:0.77222	eval-mlogloss:0.75512
[12]	train-mlogloss:0.75173	eval-mlogloss:0.73303
[13]	train-mlogloss:0.73143	eval-mlogloss:0.71232
[14]	train-mlogloss:0.71274	eval-mlogloss:0.69169
[15]	train-mlogloss:0.69395	eval-mlogloss:0.67143
[16]	train-mlogloss:0.67568	eval-mlogloss:0.65227
[17]	train-mlogloss:0.65878	eval-mlogloss:0.63439
[18]	train-mlogloss:0.64240	eval-mlogloss:0.61726
[19]	train-mlogloss:0.62605	eval-mlogloss:0.60098
[20]	train-mlogloss:0.61070	eval-mlogloss:0.58452
[21]	train-mlogloss:0.59686	eval-mlogloss:0.56967
[22]	train-mlogloss:0.58198	eval-mlogloss:0.55391
[23]	train-mlogloss:0.56755	eval-mlogloss:0.53917
[24]	train-mlogloss:0.55354	eval-mlogloss:0.52447
[25]	train-mlogloss:0.54046	eval-mlogloss:0.51061
[26]	train-mlogloss:0.52775	eval-mlogloss:0.49675
[27]	train-mlogloss:0.51509	eval-mlogloss:0.48386
[28]	train-mlogloss:0.50318	eval-mlogloss:0.47105
[29]	train-mlogloss:0.49172	eval-mlogloss:0.45865
[30]	train-mlogloss:0.48041	eval-mlogloss:0.44724
[31]	train-mlogloss:0.46949	eval-mlogloss:0.43535
[32]	train-mlogloss:0.45881	eval-mlogloss:0.42426
[33]	train-mlogloss:0.44823	eval-mlogloss:0.41313
[34]	train-mlogloss:0.43839	eval-mlogloss:0.40303
[35]	train-mlogloss:0.42914	eval-mlogloss:0.39293
[36]	train-mlogloss:0.42001	eval-mlogloss:0.38326
[37]	train-mlogloss:0.41085	eval-mlogloss:0.37385
[38]	train-mlogloss:0.40234	eval-mlogloss:0.36487
[39]	train-mlogloss:0.39336	eval-mlogloss:0.35549
[40]	train-mlogloss:0.38500	eval-mlogloss:0.34721
[41]	train-mlogloss:0.37714	eval-mlogloss:0.33884
[42]	train-mlogloss:0.36933	eval-mlogloss:0.33075
[43]	train-mlogloss:0.36181	eval-mlogloss:0.32279
[44]	train-mlogloss:0.35413	eval-mlogloss:0.31492
[45]	train-mlogloss:0.34674	eval-mlogloss:0.30731
[46]	train-mlogloss:0.33930	eval-mlogloss:0.30017
[47]	train-mlogloss:0.33264	eval-mlogloss:0.29313
[48]	train-mlogloss:0.32591	eval-mlogloss:0.28597
[49]	train-mlogloss:0.31935	eval-mlogloss:0.27919
[50]	train-mlogloss:0.31293	eval-mlogloss:0.27245
[51]	train-mlogloss:0.30644	eval-mlogloss:0.26642
[52]	train-mlogloss:0.30058	eval-mlogloss:0.26020
[53]	train-mlogloss:0.29497	eval-mlogloss:0.25396
[54]	train-mlogloss:0.28931	eval-mlogloss:0.24788
[55]	train-mlogloss:0.28377	eval-mlogloss:0.24235
[56]	train-mlogloss:0.27859	eval-mlogloss:0.23682
[57]	train-mlogloss:0.27357	eval-mlogloss:0.23154
[58]	train-mlogloss:0.26853	eval-mlogloss:0.22663
[59]	train-mlogloss:0.26373	eval-mlogloss:0.22139
[60]	train-mlogloss:0.25897	eval-mlogloss:0.21728
[61]	train-mlogloss:0.25437	eval-mlogloss:0.21219
[62]	train-mlogloss:0.24985	eval-mlogloss:0.20750
[63]	train-mlogloss:0.24543	eval-mlogloss:0.20337
[64]	train-mlogloss:0.24136	eval-mlogloss:0.19934
[65]	train-mlogloss:0.23721	eval-mlogloss:0.19496
[66]	train-mlogloss:0.23286	eval-mlogloss:0.19069
[67]	train-mlogloss:0.22885	eval-mlogloss:0.18659
[68]	train-mlogloss:0.22521	eval-mlogloss:0.18327
[69]	train-mlogloss:0.22174	eval-mlogloss:0.17976
[70]	train-mlogloss:0.21824	eval-mlogloss:0.17608
[71]	train-mlogloss:0.21481	eval-mlogloss:0.17188
[72]	train-mlogloss:0.21195	eval-mlogloss:0.16850
[73]	train-mlogloss:0.20830	eval-mlogloss:0.16537
[74]	train-mlogloss:0.20554	eval-mlogloss:0.16258
[75]	train-mlogloss:0.20247	eval-mlogloss:0.15910
[76]	train-mlogloss:0.19954	eval-mlogloss:0.15626
[77]	train-mlogloss:0.19670	eval-mlogloss:0.15305
[78]	train-mlogloss:0.19383	eval-mlogloss:0.14953
[79]	train-mlogloss:0.19102	eval-mlogloss:0.14637
[80]	train-mlogloss:0.18864	eval-mlogloss:0.14346
[81]	train-mlogloss:0.18609	eval-mlogloss:0.14062
[82]	train-mlogloss:0.18352	eval-mlogloss:0.13819
[83]	train-mlogloss:0.18142	eval-mlogloss:0.13574
[84]	train-mlogloss:0.17908	eval-mlogloss:0.13311
[85]	train-mlogloss:0.17694	eval-mlogloss:0.13098
[86]	train-mlogloss:0.17468	eval-mlogloss:0.12829
[87]	train-mlogloss:0.17243	eval-mlogloss:0.12561
[88]	train-mlogloss:0.17018	eval-mlogloss:0.12299
[89]	train-mlogloss:0.16799	eval-mlogloss:0.12077
[90]	train-mlogloss:0.16611	eval-mlogloss:0.11869
[91]	train-mlogloss:0.16409	eval-mlogloss:0.11645
[92]	train-mlogloss:0.16242	eval-mlogloss:0.11472
[93]	train-mlogloss:0.16076	eval-mlogloss:0.11267
[94]	train-mlogloss:0.15900	eval-mlogloss:0.11055
[95]	train-mlogloss:0.15760	eval-mlogloss:0.10910
[96]	train-mlogloss:0.15608	eval-mlogloss:0.10712
[97]	train-mlogloss:0.15447	eval-mlogloss:0.10508
[98]	train-mlogloss:0.15283	eval-mlogloss:0.10322
[99]	train-mlogloss:0.15129	eval-mlogloss:0.10172
[100]	train-mlogloss:0.15007	eval-mlogloss:0.10027
[101]	train-mlogloss:0.14832	eval-mlogloss:0.09838
[102]	train-mlogloss:0.14730	eval-mlogloss:0.09726
[103]	train-mlogloss:0.14590	eval-mlogloss:0.09602
[104]	train-mlogloss:0.14519	eval-mlogloss:0.09504
[105]	train-mlogloss:0.14411	eval-mlogloss:0.09358
[106]	train-mlogloss:0.14333	eval-mlogloss:0.09272
[107]	train-mlogloss:0.14240	eval-mlogloss:0.09163
[108]	train-mlogloss:0.14192	eval-mlogloss:0.09088
[109]	train-mlogloss:0.14080	eval-mlogloss:0.08957
[110]	train-mlogloss:0.14017	eval-mlogloss:0.08886
[111]	train-mlogloss:0.13966	eval-mlogloss:0.08801
[112]	train-mlogloss:0.13933	eval-mlogloss:0.08752
[113]	train-mlogloss:0.13846	eval-mlogloss:0.08627
[114]	train-mlogloss:0.13803	eval-mlogloss:0.08555
[115]	train-mlogloss:0.13757	eval-mlogloss:0.08484
[116]	train-mlogloss:0.13717	eval-mlogloss:0.08427
[117]	train-mlogloss:0.13657	eval-mlogloss:0.08329
[118]	train-mlogloss:0.13620	eval-mlogloss:0.08295
[119]	train-mlogloss:0.13517	eval-mlogloss:0.08193
[120]	train-mlogloss:0.13480	eval-mlogloss:0.08129
[121]	train-mlogloss:0.13443	eval-mlogloss:0.08064
[122]	train-mlogloss:0.13403	eval-mlogloss:0.07997
[123]	train-mlogloss:0.13382	eval-mlogloss:0.07961
[124]	train-mlogloss:0.13348	eval-mlogloss:0.07921
[125]	train-mlogloss:0.13312	eval-mlogloss:0.07868
[126]	train-mlogloss:0.13261	eval-mlogloss:0.07812
[127]	train-mlogloss:0.13246	eval-mlogloss:0.07794
[128]	train-mlogloss:0.13208	eval-mlogloss:0.07738

[I 2025-06-12 19:47:42,467] Trial 10 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:0.76809	eval-mlogloss:0.76965
[1]	train-mlogloss:0.56856	eval-mlogloss:0.54936

[I 2025-06-12 19:47:42,658] Trial 11 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.81659	eval-mlogloss:0.81863
[1]	train-mlogloss:0.66920	eval-mlogloss:0.64637

[I 2025-06-12 19:47:42,790] Trial 12 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.81995	eval-mlogloss:0.81427
[1]	train-mlogloss:0.63391	eval-mlogloss:0.61166

[I 2025-06-12 19:47:42,929] Trial 13 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.04671	eval-mlogloss:1.04592
[1]	train-mlogloss:1.00023	eval-mlogloss:0.99347
[2]	train-mlogloss:0.95487	eval-mlogloss:0.94442
[3]	train-mlogloss:0.90898	eval-mlogloss:0.89650
[4]	train-mlogloss:0.86848	eval-mlogloss:0.85387
[5]	train-mlogloss:0.82888	eval-mlogloss:0.81146
[6]	train-mlogloss:0.79249	eval-mlogloss:0.77151
[7]	train-mlogloss:0.75965	eval-mlogloss:0.73636

[I 2025-06-12 19:47:43,090] Trial 14 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.01627	eval-mlogloss:1.01737
[1]	train-mlogloss:0.95560	eval-mlogloss:0.94704
[2]	train-mlogloss:0.88700	eval-mlogloss:0.87480
[3]	train-mlogloss:0.82086	eval-mlogloss:0.80371
[4]	train-mlogloss:0.76774	eval-mlogloss:0.74737
[5]	train-mlogloss:0.71492	eval-mlogloss:0.69188
[6]	train-mlogloss:0.66686	eval-mlogloss:0.63918
[7]	train-mlogloss:0.62935	eval-mlogloss:0.60470

[I 2025-06-12 19:47:43,243] Trial 15 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.82738	eval-mlogloss:0.83081
[1]	train-mlogloss:0.63907	eval-mlogloss:0.62482
[2]	train-mlogloss:0.50831	eval-mlogloss:0.48576

[I 2025-06-12 19:47:43,375] Trial 16 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.86204	eval-mlogloss:0.85601
[1]	train-mlogloss:0.69421	eval-mlogloss:0.67585
[2]	train-mlogloss:0.57161	eval-mlogloss:0.54286

[I 2025-06-12 19:47:43,505] Trial 17 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.95814	eval-mlogloss:0.95230
[1]	train-mlogloss:0.89956	eval-mlogloss:0.88388
[2]	train-mlogloss:0.80386	eval-mlogloss:0.78293

[I 2025-06-12 19:47:43,625] Trial 18 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.81140	eval-mlogloss:0.81489
[1]	train-mlogloss:0.61784	eval-mlogloss:0.60123

[I 2025-06-12 19:47:43,745] Trial 19 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.91921	eval-mlogloss:0.90805
[1]	train-mlogloss:0.83948	eval-mlogloss:0.82196

[I 2025-06-12 19:47:43,915] Trial 20 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06708	eval-mlogloss:1.06601
[1]	train-mlogloss:1.03705	eval-mlogloss:1.03397
[2]	train-mlogloss:1.00770	eval-mlogloss:1.00265
[3]	train-mlogloss:0.97894	eval-mlogloss:0.97320
[4]	train-mlogloss:0.95234	eval-mlogloss:0.94564
[5]	train-mlogloss:0.92622	eval-mlogloss:0.91763
[6]	train-mlogloss:0.90194	eval-mlogloss:0.89171
[7]	train-mlogloss:0.87823	eval-mlogloss:0.86719
[8]	train-mlogloss:0.85557	eval-mlogloss:0.84365
[9]	train-mlogloss:0.83328	eval-mlogloss:0.81980
[10]	train-mlogloss:0.81194	eval-mlogloss:0.79787
[11]	train-mlogloss:0.79112	eval-mlogloss:0.77569
[12]	train-mlogloss:0.77155	eval-mlogloss:0.75513
[13]	train-mlogloss:0.75207	eval-mlogloss:0.73524
[14]	train-mlogloss:0.73402	eval-mlogloss:0.71575
[15]	train-mlogloss:0.71580	eval-mlogloss:0.69608
[16]	train-mlogloss:0.69813	eval-mlogloss:0.67755
[17]	train-mlogloss:0.68175	eval-mlogloss:0.66020
[18]	train-mlogloss:0.66583	eval-mlogloss:0.64354
[19]	train-mlogloss:0.64994	eval-mlogloss:0.62770
[20]	train-mlogloss:0.63473	eval-mlogloss:0.61156
[21]	train-mlogloss:0.62117	eval-mlogloss:0.59702
[22]	train-mlogloss:0.60660	eval-mlogloss:0.58157
[23]	train-mlogloss:0.59247	eval-mlogloss:0.56708
[24]	train-mlogloss:0.57871	eval-mlogloss:0.55263
[25]	train-mlogloss:0.56585	eval-mlogloss:0.53898
[26]	train-mlogloss:0.55327	eval-mlogloss:0.52544
[27]	train-mlogloss:0.54072	eval-mlogloss:0.51262
[28]	train-mlogloss:0.52876	eval-mlogloss:0.50065
[29]	train-mlogloss:0.51737	eval-mlogloss:0.48830
[30]	train-mlogloss:0.50610	eval-mlogloss:0.47682
[31]	train-mlogloss:0.49516	eval-mlogloss:0.46497
[32]	train-mlogloss:0.48455	eval-mlogloss:0.45391
[33]	train-mlogloss:0.47402	eval-mlogloss:0.44280
[34]	train-mlogloss:0.46418	eval-mlogloss:0.43262
[35]	train-mlogloss:0.45485	eval-mlogloss:0.42236
[36]	train-mlogloss:0.44551	eval-mlogloss:0.41254
[37]	train-mlogloss:0.43630	eval-mlogloss:0.40305
[38]	train-mlogloss:0.42768	eval-mlogloss:0.39392
[39]	train-mlogloss:0.41866	eval-mlogloss:0.38445
[40]	train-mlogloss:0.41029	eval-mlogloss:0.37578
[41]	train-mlogloss:0.40220	eval-mlogloss:0.36698
[42]	train-mlogloss:0.39429	eval-mlogloss:0.35877
[43]	train-mlogloss:0.38663	eval-mlogloss:0.35065
[44]	train-mlogloss:0.37876	eval-mlogloss:0.34254
[45]	train-mlogloss:0.37130	eval-mlogloss:0.33472
[46]	train-mlogloss:0.36338	eval-mlogloss:0.32769
[47]	train-mlogloss:0.35652	eval-mlogloss:0.32036
[48]	train-mlogloss:0.34966	eval-mlogloss:0.31303
[49]	train-mlogloss:0.34294	eval-mlogloss:0.30603
[50]	train-mlogloss:0.33636	eval-mlogloss:0.29911
[51]	train-mlogloss:0.32975	eval-mlogloss:0.29289
[52]	train-mlogloss:0.32387	eval-mlogloss:0.28633
[53]	train-mlogloss:0.31807	eval-mlogloss:0.27989
[54]	train-mlogloss:0.31222	eval-mlogloss:0.27361
[55]	train-mlogloss:0.30647	eval-mlogloss:0.26775
[56]	train-mlogloss:0.30110	eval-mlogloss:0.26200
[57]	train-mlogloss:0.29578	eval-mlogloss:0.25670
[58]	train-mlogloss:0.29056	eval-mlogloss:0.25157
[59]	train-mlogloss:0.28556	eval-mlogloss:0.24610
[60]	train-mlogloss:0.28066	eval-mlogloss:0.24177
[61]	train-mlogloss:0.27590	eval-mlogloss:0.23636
[62]	train-mlogloss:0.27116	eval-mlogloss:0.23143
[63]	train-mlogloss:0.26655	eval-mlogloss:0.22711
[64]	train-mlogloss:0.26215	eval-mlogloss:0.22288
[65]	train-mlogloss:0.25772	eval-mlogloss:0.21808
[66]	train-mlogloss:0.25317	eval-mlogloss:0.21358
[67]	train-mlogloss:0.24894	eval-mlogloss:0.20922
[68]	train-mlogloss:0.24501	eval-mlogloss:0.20490
[69]	train-mlogloss:0.24115	eval-mlogloss:0.20108
[70]	train-mlogloss:0.23724	eval-mlogloss:0.19695
[71]	train-mlogloss:0.23353	eval-mlogloss:0.19245
[72]	train-mlogloss:0.23013	eval-mlogloss:0.18874
[73]	train-mlogloss:0.22649	eval-mlogloss:0.18540
[74]	train-mlogloss:0.22319	eval-mlogloss:0.18199
[75]	train-mlogloss:0.21978	eval-mlogloss:0.17827
[76]	train-mlogloss:0.21662	eval-mlogloss:0.17516
[77]	train-mlogloss:0.21360	eval-mlogloss:0.17180
[78]	train-mlogloss:0.21043	eval-mlogloss:0.16806
[79]	train-mlogloss:0.20721	eval-mlogloss:0.16457
[80]	train-mlogloss:0.20469	eval-mlogloss:0.16151
[81]	train-mlogloss:0.20195	eval-mlogloss:0.15847
[82]	train-mlogloss:0.19936	eval-mlogloss:0.15574
[83]	train-mlogloss:0.19681	eval-mlogloss:0.15261
[84]	train-mlogloss:0.19424	eval-mlogloss:0.14971
[85]	train-mlogloss:0.19176	eval-mlogloss:0.14714
[86]	train-mlogloss:0.18935	eval-mlogloss:0.14427
[87]	train-mlogloss:0.18697	eval-mlogloss:0.14147
[88]	train-mlogloss:0.18453	eval-mlogloss:0.13864
[89]	train-mlogloss:0.18212	eval-mlogloss:0.13608
[90]	train-mlogloss:0.17999	eval-mlogloss:0.13373
[91]	train-mlogloss:0.17754	eval-mlogloss:0.13121
[92]	train-mlogloss:0.17562	eval-mlogloss:0.12917
[93]	train-mlogloss:0.17375	eval-mlogloss:0.12683
[94]	train-mlogloss:0.17173	eval-mlogloss:0.12448
[95]	train-mlogloss:0.17011	eval-mlogloss:0.12280
[96]	train-mlogloss:0.16837	eval-mlogloss:0.12059
[97]	train-mlogloss:0.16653	eval-mlogloss:0.11847
[98]	train-mlogloss:0.16460	eval-mlogloss:0.11643
[99]	train-mlogloss:0.16288	eval-mlogloss:0.11494
[100]	train-mlogloss:0.16133	eval-mlogloss:0.11315
[101]	train-mlogloss:0.15945	eval-mlogloss:0.11114
[102]	train-mlogloss:0.15818	eval-mlogloss:0.10980
[103]	train-mlogloss:0.15644	eval-mlogloss:0.10786
[104]	train-mlogloss:0.15507	eval-mlogloss:0.10612
[105]	train-mlogloss:0.15366	eval-mlogloss:0.10425
[106]	train-mlogloss:0.15194	eval-mlogloss:0.10278
[107]	train-mlogloss:0.15069	eval-mlogloss:0.10132
[108]	train-mlogloss:0.14953	eval-mlogloss:0.09991
[109]	train-mlogloss:0.14826	eval-mlogloss:0.09843
[110]	train-mlogloss:0.14702	eval-mlogloss:0.09679
[111]	train-mlogloss:0.14585	eval-mlogloss:0.09531
[112]	train-mlogloss:0.14492	eval-mlogloss:0.09430
[113]	train-mlogloss:0.14402	eval-mlogloss:0.09304
[114]	train-mlogloss:0.14297	eval-mlogloss:0.09173
[115]	train-mlogloss:0.14243	eval-mlogloss:0.09092
[116]	train-mlogloss:0.14201	eval-mlogloss:0.09033
[117]	train-mlogloss:0.14140	eval-mlogloss:0.08934
[118]	train-mlogloss:0.14102	eval-mlogloss:0.08897
[119]	train-mlogloss:0.13993	eval-mlogloss:0.08798
[120]	train-mlogloss:0.13947	eval-mlogloss:0.08723
[121]	train-mlogloss:0.13907	eval-mlogloss:0.08656
[122]	train-mlogloss:0.13866	eval-mlogloss:0.08586
[123]	train-mlogloss:0.13842	eval-mlogloss:0.08558
[124]	train-mlogloss:0.13805	eval-mlogloss:0.08515
[125]	train-mlogloss:0.13763	eval-mlogloss:0.08446
[126]	train-mlogloss:0.13708	eval-mlogloss:0.08385
[127]	train-mlogloss:0.13693	eval-mlogloss:0.08367

[I 2025-06-12 19:47:44,896] Trial 21 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:1.03580	eval-mlogloss:1.03504
[1]	train-mlogloss:0.97904	eval-mlogloss:0.97432
[2]	train-mlogloss:0.92430	eval-mlogloss:0.91702
[3]	train-mlogloss:0.87460	eval-mlogloss:0.86654
[4]	train-mlogloss:0.82931	eval-mlogloss:0.81893
[5]	train-mlogloss:0.78656	eval-mlogloss:0.77285
[6]	train-mlogloss:0.74803	eval-mlogloss:0.73155
[7]	train-mlogloss:0.71115	eval-mlogloss:0.69269

[I 2025-06-12 19:47:45,070] Trial 22 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.07095	eval-mlogloss:1.06979
[1]	train-mlogloss:1.04445	eval-mlogloss:1.04164
[2]	train-mlogloss:1.01830	eval-mlogloss:1.01411
[3]	train-mlogloss:0.99249	eval-mlogloss:0.98702
[4]	train-mlogloss:0.96832	eval-mlogloss:0.96248
[5]	train-mlogloss:0.94443	eval-mlogloss:0.93728
[6]	train-mlogloss:0.92209	eval-mlogloss:0.91454
[7]	train-mlogloss:0.90035	eval-mlogloss:0.89189
[8]	train-mlogloss:0.87933	eval-mlogloss:0.87007
[9]	train-mlogloss:0.85851	eval-mlogloss:0.84785
[10]	train-mlogloss:0.83895	eval-mlogloss:0.82746
[11]	train-mlogloss:0.81950	eval-mlogloss:0.80671
[12]	train-mlogloss:0.80127	eval-mlogloss:0.78813
[13]	train-mlogloss:0.78266	eval-mlogloss:0.76857
[14]	train-mlogloss:0.76553	eval-mlogloss:0.75058
[15]	train-mlogloss:0.74825	eval-mlogloss:0.73230
[16]	train-mlogloss:0.73178	eval-mlogloss:0.71510
[17]	train-mlogloss:0.71623	eval-mlogloss:0.69915
[18]	train-mlogloss:0.70075	eval-mlogloss:0.68329
[19]	train-mlogloss:0.68567	eval-mlogloss:0.66793
[20]	train-mlogloss:0.67135	eval-mlogloss:0.65285
[21]	train-mlogloss:0.65800	eval-mlogloss:0.63888
[22]	train-mlogloss:0.64359	eval-mlogloss:0.62373
[23]	train-mlogloss:0.62972	eval-mlogloss:0.60913
[24]	train-mlogloss:0.61627	eval-mlogloss:0.59533
[25]	train-mlogloss:0.60355	eval-mlogloss:0.58163
[26]	train-mlogloss:0.59145	eval-mlogloss:0.56867
[27]	train-mlogloss:0.57914	eval-mlogloss:0.55599
[28]	train-mlogloss:0.56737	eval-mlogloss:0.54356
[29]	train-mlogloss:0.55602	eval-mlogloss:0.53162
[30]	train-mlogloss:0.54491	eval-mlogloss:0.52039
[31]	train-mlogloss:0.53395	eval-mlogloss:0.50869
[32]	train-mlogloss:0.52354	eval-mlogloss:0.49831
[33]	train-mlogloss:0.51328	eval-mlogloss:0.48725
[34]	train-mlogloss:0.50337	eval-mlogloss:0.47736
[35]	train-mlogloss:0.49397	eval-mlogloss:0.46739
[36]	train-mlogloss:0.48434	eval-mlogloss:0.45803
[37]	train-mlogloss:0.47493	eval-mlogloss:0.44807
[38]	train-mlogloss:0.46619	eval-mlogloss:0.43913
[39]	train-mlogloss:0.45709	eval-mlogloss:0.42989
[40]	train-mlogloss:0.44838	eval-mlogloss:0.42088
[41]	train-mlogloss:0.44008	eval-mlogloss:0.41224
[42]	train-mlogloss:0.43181	eval-mlogloss:0.40323
[43]	train-mlogloss:0.42368	eval-mlogloss:0.39484
[44]	train-mlogloss:0.41576	eval-mlogloss:0.38631
[45]	train-mlogloss:0.40799	eval-mlogloss:0.37852
[46]	train-mlogloss:0.40025	eval-mlogloss:0.37058
[47]	train-mlogloss:0.39308	eval-mlogloss:0.36334
[48]	train-mlogloss:0.38598	eval-mlogloss:0.35612
[49]	train-mlogloss:0.37894	eval-mlogloss:0.34867
[50]	train-mlogloss:0.37191	eval-mlogloss:0.34095
[51]	train-mlogloss:0.36556	eval-mlogloss:0.33408
[52]	train-mlogloss:0.35930	eval-mlogloss:0.32753
[53]	train-mlogloss:0.35324	eval-mlogloss:0.32111
[54]	train-mlogloss:0.34713	eval-mlogloss:0.31506
[55]	train-mlogloss:0.34077	eval-mlogloss:0.30979
[56]	train-mlogloss:0.33499	eval-mlogloss:0.30367
[57]	train-mlogloss:0.32925	eval-mlogloss:0.29808
[58]	train-mlogloss:0.32368	eval-mlogloss:0.29210
[59]	train-mlogloss:0.31821	eval-mlogloss:0.28637
[60]	train-mlogloss:0.31293	eval-mlogloss:0.28088
[61]	train-mlogloss:0.30786	eval-mlogloss:0.27521
[62]	train-mlogloss:0.30251	eval-mlogloss:0.26955
[63]	train-mlogloss:0.29735	eval-mlogloss:0.26493
[64]	train-mlogloss:0.29268	eval-mlogloss:0.26003
[65]	train-mlogloss:0.28778	eval-mlogloss:0.25491
[66]	train-mlogloss:0.28279	eval-mlogloss:0.24947
[67]	train-mlogloss:0.27791	eval-mlogloss:0.24517
[68]	train-mlogloss:0.27339	eval-mlogloss:0.24088
[69]	train-mlogloss:0.26871	eval-mlogloss:0.23712
[70]	train-mlogloss:0.26430	eval-mlogloss:0.23223
[71]	train-mlogloss:0.25991	eval-mlogloss:0.22780
[72]	train-mlogloss:0.25591	eval-mlogloss:0.22397
[73]	train-mlogloss:0.25156	eval-mlogloss:0.22051
[74]	train-mlogloss:0.24778	eval-mlogloss:0.21658
[75]	train-mlogloss:0.24364	eval-mlogloss:0.21302
[76]	train-mlogloss:0.23968	eval-mlogloss:0.20967
[77]	train-mlogloss:0.23592	eval-mlogloss:0.20571
[78]	train-mlogloss:0.23236	eval-mlogloss:0.20161
[79]	train-mlogloss:0.22885	eval-mlogloss:0.19777
[80]	train-mlogloss:0.22546	eval-mlogloss:0.19418
[81]	train-mlogloss:0.22183	eval-mlogloss:0.19022
[82]	train-mlogloss:0.21851	eval-mlogloss:0.18669
[83]	train-mlogloss:0.21522	eval-mlogloss:0.18314
[84]	train-mlogloss:0.21204	eval-mlogloss:0.17949
[85]	train-mlogloss:0.20878	eval-mlogloss:0.17640
[86]	train-mlogloss:0.20572	eval-mlogloss:0.17316
[87]	train-mlogloss:0.20280	eval-mlogloss:0.16976
[88]	train-mlogloss:0.19969	eval-mlogloss:0.16708
[89]	train-mlogloss:0.19656	eval-mlogloss:0.16358
[90]	train-mlogloss:0.19363	eval-mlogloss:0.16107
[91]	train-mlogloss:0.19086	eval-mlogloss:0.15819
[92]	train-mlogloss:0.18822	eval-mlogloss:0.15546
[93]	train-mlogloss:0.18572	eval-mlogloss:0.15261
[94]	train-mlogloss:0.18299	eval-mlogloss:0.15036
[95]	train-mlogloss:0.18046	eval-mlogloss:0.14847
[96]	train-mlogloss:0.17810	eval-mlogloss:0.14560
[97]	train-mlogloss:0.17552	eval-mlogloss:0.14283
[98]	train-mlogloss:0.17302	eval-mlogloss:0.14040
[99]	train-mlogloss:0.17075	eval-mlogloss:0.13812
[100]	train-mlogloss:0.16864	eval-mlogloss:0.13596
[101]	train-mlogloss:0.16635	eval-mlogloss:0.13380
[102]	train-mlogloss:0.16402	eval-mlogloss:0.13142
[103]	train-mlogloss:0.16158	eval-mlogloss:0.12961
[104]	train-mlogloss:0.15944	eval-mlogloss:0.12752
[105]	train-mlogloss:0.15738	eval-mlogloss:0.12538
[106]	train-mlogloss:0.15506	eval-mlogloss:0.12398
[107]	train-mlogloss:0.15288	eval-mlogloss:0.12172
[108]	train-mlogloss:0.15087	eval-mlogloss:0.11982
[109]	train-mlogloss:0.14919	eval-mlogloss:0.11804
[110]	train-mlogloss:0.14744	eval-mlogloss:0.11593
[111]	train-mlogloss:0.14574	eval-mlogloss:0.11399
[112]	train-mlogloss:0.14415	eval-mlogloss:0.11218
[113]	train-mlogloss:0.14250	eval-mlogloss:0.11033
[114]	train-mlogloss:0.14087	eval-mlogloss:0.10852
[115]	train-mlogloss:0.13927	eval-mlogloss:0.10662
[116]	train-mlogloss:0.13774	eval-mlogloss:0.10517
[117]	train-mlogloss:0.13600	eval-mlogloss:0.10322
[118]	train-mlogloss:0.13452	eval-mlogloss:0.10172
[119]	train-mlogloss:0.13310	eval-mlogloss:0.10026
[120]	train-mlogloss:0.13143	eval-mlogloss:0.09897
[121]	train-mlogloss:0.12990	eval-mlogloss:0.09731
[122]	train-mlogloss:0.12856	eval-mlogloss:0.09584
[123]	train-mlogloss:0.12716	eval-mlogloss:0.09434
[124]	train-mlogloss:0.12577	eval-mlogloss:0.09300
[125]	train-mlogloss:0.12434	eval-mlogloss:0.09143
[126]	train-mlogloss:0.12294	eval-mlogloss:0.09045
[127]	train-mlogloss:0.12171	eval-mlogloss:0.08904

[I 2025-06-12 19:47:46,215] Trial 23 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:1.08433	eval-mlogloss:1.08419
[1]	train-mlogloss:1.07005	eval-mlogloss:1.06883
[2]	train-mlogloss:1.05562	eval-mlogloss:1.05328
[3]	train-mlogloss:1.04121	eval-mlogloss:1.03833
[4]	train-mlogloss:1.02736	eval-mlogloss:1.02492
[5]	train-mlogloss:1.01361	eval-mlogloss:1.01036
[6]	train-mlogloss:1.00045	eval-mlogloss:0.99623
[7]	train-mlogloss:0.98824	eval-mlogloss:0.98399
[8]	train-mlogloss:0.97562	eval-mlogloss:0.97005
[9]	train-mlogloss:0.96269	eval-mlogloss:0.95637
[10]	train-mlogloss:0.95059	eval-mlogloss:0.94377
[11]	train-mlogloss:0.93866	eval-mlogloss:0.93078
[12]	train-mlogloss:0.92701	eval-mlogloss:0.91859
[13]	train-mlogloss:0.91506	eval-mlogloss:0.90634
[14]	train-mlogloss:0.90377	eval-mlogloss:0.89422
[15]	train-mlogloss:0.89227	eval-mlogloss:0.88209
[16]	train-mlogloss:0.88116	eval-mlogloss:0.86999
[17]	train-mlogloss:0.87034	eval-mlogloss:0.85894
[18]	train-mlogloss:0.85953	eval-mlogloss:0.84795
[19]	train-mlogloss:0.84885	eval-mlogloss:0.83699
[20]	train-mlogloss:0.84019	eval-mlogloss:0.82778
[21]	train-mlogloss:0.83094	eval-mlogloss:0.81754
[22]	train-mlogloss:0.82171	eval-mlogloss:0.80754
[23]	train-mlogloss:0.81245	eval-mlogloss:0.79837
[24]	train-mlogloss:0.80258	eval-mlogloss:0.78777
[25]	train-mlogloss:0.79349	eval-mlogloss:0.77763
[26]	train-mlogloss:0.78400	eval-mlogloss:0.76761
[27]	train-mlogloss:0.77505	eval-mlogloss:0.75839
[28]	train-mlogloss:0.76573	eval-mlogloss:0.74840
[29]	train-mlogloss:0.75701	eval-mlogloss:0.73912
[30]	train-mlogloss:0.74813	eval-mlogloss:0.73010
[31]	train-mlogloss:0.73977	eval-mlogloss:0.72117
[32]	train-mlogloss:0.73134	eval-mlogloss:0.71248
[33]	train-mlogloss:0.72307	eval-mlogloss:0.70369
[34]	train-mlogloss:0.71515	eval-mlogloss:0.69565
[35]	train-mlogloss:0.70728	eval-mlogloss:0.68708
[36]	train-mlogloss:0.69976	eval-mlogloss:0.67933
[37]	train-mlogloss:0.69212	eval-mlogloss:0.67138
[38]	train-mlogloss:0.68458	eval-mlogloss:0.66352
[39]	train-mlogloss:0.67684	eval-mlogloss:0.65513
[40]	train-mlogloss:0.66973	eval-mlogloss:0.64823
[41]	train-mlogloss:0.66233	eval-mlogloss:0.64014
[42]	train-mlogloss:0.65483	eval-mlogloss:0.63204
[43]	train-mlogloss:0.64805	eval-mlogloss:0.62460
[44]	train-mlogloss:0.64166	eval-mlogloss:0.61790
[45]	train-mlogloss:0.63436	eval-mlogloss:0.61004
[46]	train-mlogloss:0.62724	eval-mlogloss:0.60255
[47]	train-mlogloss:0.62084	eval-mlogloss:0.59604
[48]	train-mlogloss:0.61439	eval-mlogloss:0.58956
[49]	train-mlogloss:0.60750	eval-mlogloss:0.58200
[50]	train-mlogloss:0.60114	eval-mlogloss:0.57509
[51]	train-mlogloss:0.59514	eval-mlogloss:0.56859
[52]	train-mlogloss:0.58879	eval-mlogloss:0.56163
[53]	train-mlogloss:0.58279	eval-mlogloss:0.55539
[54]	train-mlogloss:0.57660	eval-mlogloss:0.54907
[55]	train-mlogloss:0.57022	eval-mlogloss:0.54348
[56]	train-mlogloss:0.56430	eval-mlogloss:0.53720
[57]	train-mlogloss:0.55852	eval-mlogloss:0.53102
[58]	train-mlogloss:0.55270	eval-mlogloss:0.52492
[59]	train-mlogloss:0.54690	eval-mlogloss:0.51838
[60]	train-mlogloss:0.54109	eval-mlogloss:0.51230
[61]	train-mlogloss:0.53578	eval-mlogloss:0.50673
[62]	train-mlogloss:0.53003	eval-mlogloss:0.50043
[63]	train-mlogloss:0.52468	eval-mlogloss:0.49486
[64]	train-mlogloss:0.51936	eval-mlogloss:0.48912
[65]	train-mlogloss:0.51414	eval-mlogloss:0.48354
[66]	train-mlogloss:0.50899	eval-mlogloss:0.47792
[67]	train-mlogloss:0.50363	eval-mlogloss:0.47276
[68]	train-mlogloss:0.49871	eval-mlogloss:0.46753
[69]	train-mlogloss:0.49396	eval-mlogloss:0.46235
[70]	train-mlogloss:0.48902	eval-mlogloss:0.45701
[71]	train-mlogloss:0.48405	eval-mlogloss:0.45182
[72]	train-mlogloss:0.47956	eval-mlogloss:0.44697
[73]	train-mlogloss:0.47449	eval-mlogloss:0.44210
[74]	train-mlogloss:0.46980	eval-mlogloss:0.43721
[75]	train-mlogloss:0.46528	eval-mlogloss:0.43244
[76]	train-mlogloss:0.46043	eval-mlogloss:0.42736
[77]	train-mlogloss:0.45591	eval-mlogloss:0.42264
[78]	train-mlogloss:0.45131	eval-mlogloss:0.41765
[79]	train-mlogloss:0.44694	eval-mlogloss:0.41303
[80]	train-mlogloss:0.44281	eval-mlogloss:0.40843
[81]	train-mlogloss:0.43847	eval-mlogloss:0.40397
[82]	train-mlogloss:0.43409	eval-mlogloss:0.39931
[83]	train-mlogloss:0.42983	eval-mlogloss:0.39461
[84]	train-mlogloss:0.42561	eval-mlogloss:0.39006
[85]	train-mlogloss:0.42141	eval-mlogloss:0.38654
[86]	train-mlogloss:0.41776	eval-mlogloss:0.38280
[87]	train-mlogloss:0.41381	eval-mlogloss:0.37842
[88]	train-mlogloss:0.40998	eval-mlogloss:0.37428
[89]	train-mlogloss:0.40600	eval-mlogloss:0.37012
[90]	train-mlogloss:0.40208	eval-mlogloss:0.36649
[91]	train-mlogloss:0.39827	eval-mlogloss:0.36258
[92]	train-mlogloss:0.39451	eval-mlogloss:0.35853
[93]	train-mlogloss:0.39077	eval-mlogloss:0.35443
[94]	train-mlogloss:0.38708	eval-mlogloss:0.35064
[95]	train-mlogloss:0.38372	eval-mlogloss:0.34700
[96]	train-mlogloss:0.38020	eval-mlogloss:0.34311
[97]	train-mlogloss:0.37656	eval-mlogloss:0.33920
[98]	train-mlogloss:0.37301	eval-mlogloss:0.33545
[99]	train-mlogloss:0.36967	eval-mlogloss:0.33207
[100]	train-mlogloss:0.36638	eval-mlogloss:0.32856
[101]	train-mlogloss:0.36309	eval-mlogloss:0.32569
[102]	train-mlogloss:0.35968	eval-mlogloss:0.32217
[103]	train-mlogloss:0.35663	eval-mlogloss:0.31899
[104]	train-mlogloss:0.35324	eval-mlogloss:0.31589
[105]	train-mlogloss:0.34997	eval-mlogloss:0.31245
[106]	train-mlogloss:0.34670	eval-mlogloss:0.30906
[107]	train-mlogloss:0.34356	eval-mlogloss:0.30592
[108]	train-mlogloss:0.34058	eval-mlogloss:0.30266
[109]	train-mlogloss:0.33758	eval-mlogloss:0.29926
[110]	train-mlogloss:0.33466	eval-mlogloss:0.29613
[111]	train-mlogloss:0.33166	eval-mlogloss:0.29294
[112]	train-mlogloss:0.32867	eval-mlogloss:0.28970
[113]	train-mlogloss:0.32597	eval-mlogloss:0.28668
[114]	train-mlogloss:0.32330	eval-mlogloss:0.28361
[115]	train-mlogloss:0.32057	eval-mlogloss:0.28054
[116]	train-mlogloss:0.31786	eval-mlogloss:0.27762
[117]	train-mlogloss:0.31515	eval-mlogloss:0.27454
[118]	train-mlogloss:0.31255	eval-mlogloss:0.27213
[119]	train-mlogloss:0.30984	eval-mlogloss:0.26935
[120]	train-mlogloss:0.30731	eval-mlogloss:0.26665
[121]	train-mlogloss:0.30456	eval-mlogloss:0.26376
[122]	train-mlogloss:0.30189	eval-mlogloss:0.26120
[123]	train-mlogloss:0.29936	eval-mlogloss:0.25858
[124]	train-mlogloss:0.29684	eval-mlogloss:0.25572
[125]	train-mlogloss:0.29429	eval-mlogloss:0.25320
[126]	train-mlogloss:0.29179	eval-mlogloss:0.25117
[127]	train-mlogloss:0.28930	eval-mlogloss:0.24832
[128]	train-mlogloss:0.28682	eval-mlogloss:0.24552
[129]	train-mlogloss:0.28454	eval-mlogloss:0.24308
[130]	train-mlogloss:0.28223	eval-mlogloss:0.24076
[131]	train-mlogloss:0.27987	eval-mlogloss:0.23830
[132]	train-mlogloss:0.27762	eval-mlogloss:0.23609
[133]	train-mlogloss:0.27533	eval-mlogloss:0.23370
[134]	train-mlogloss:0.27324	eval-mlogloss:0.23149
[135]	train-mlogloss:0.27124	eval-mlogloss:0.22913
[136]	train-mlogloss:0.26895	eval-mlogloss:0.22675
[137]	train-mlogloss:0.26679	eval-mlogloss:0.22428
[138]	train-mlogloss:0.26459	eval-mlogloss:0.22213
[139]	train-mlogloss:0.26270	eval-mlogloss:0.22006
[140]	train-mlogloss:0.26064	eval-mlogloss:0.21770
[141]	train-mlogloss:0.25852	eval-mlogloss:0.21536
[142]	train-mlogloss:0.25630	eval-mlogloss:0.21340
[143]	train-mlogloss:0.25435	eval-mlogloss:0.21122
[144]	train-mlogloss:0.25224	eval-mlogloss:0.20899
[145]	train-mlogloss:0.25010	eval-mlogloss:0.20643
[146]	train-mlogloss:0.24812	eval-mlogloss:0.20439
[147]	train-mlogloss:0.24619	eval-mlogloss:0.20232
[148]	train-mlogloss:0.24410	eval-mlogloss:0.20000
[149]	train-mlogloss:0.24231	eval-mlogloss:0.19855
[150]	train-mlogloss:0.24063	eval-mlogloss:0.19717
[151]	train-mlogloss:0.23874	eval-mlogloss:0.19533
[152]	train-mlogloss:0.23685	eval-mlogloss:0.19318
[153]	train-mlogloss:0.23503	eval-mlogloss:0.19138
[154]	train-mlogloss:0.23328	eval-mlogloss:0.18961
[155]	train-mlogloss:0.23136	eval-mlogloss:0.18757
[156]	train-mlogloss:0.22960	eval-mlogloss:0.18563
[157]	train-mlogloss:0.22789	eval-mlogloss:0.18364
[158]	train-mlogloss:0.22606	eval-mlogloss:0.18174
[159]	train-mlogloss:0.22446	eval-mlogloss:0.18035
[160]	train-mlogloss:0.22275	eval-mlogloss:0.17868
[161]	train-mlogloss:0.22103	eval-mlogloss:0.17724
[162]	train-mlogloss:0.21946	eval-mlogloss:0.17579
[163]	train-mlogloss:0.21790	eval-mlogloss:0.17451
[164]	train-mlogloss:0.21657	eval-mlogloss:0.17315
[165]	train-mlogloss:0.21475	eval-mlogloss:0.17148
[166]	train-mlogloss:0.21318	eval-mlogloss:0.16968
[167]	train-mlogloss:0.21151	eval-mlogloss:0.16809
[168]	train-mlogloss:0.20988	eval-mlogloss:0.16668
[169]	train-mlogloss:0.20851	eval-mlogloss:0.16507
[170]	train-mlogloss:0.20713	eval-mlogloss:0.16346
[171]	train-mlogloss:0.20562	eval-mlogloss:0.16178
[172]	train-mlogloss:0.20427	eval-mlogloss:0.16041
[173]	train-mlogloss:0.20290	eval-mlogloss:0.15880
[174]	train-mlogloss:0.20137	eval-mlogloss:0.15719
[175]	train-mlogloss:0.19998	eval-mlogloss:0.15586
[176]	train-mlogloss:0.19874	eval-mlogloss:0.15451
[177]	train-mlogloss:0.19730	eval-mlogloss:0.15281
[178]	train-mlogloss:0.19597	eval-mlogloss:0.15136
[179]	train-mlogloss:0.19487	eval-mlogloss:0.15005
[180]	train-mlogloss:0.19375	eval-mlogloss:0.14866
[181]	train-mlogloss:0.19249	eval-mlogloss:0.14721
[182]	train-mlogloss:0.19150	eval-mlogloss:0.14609
[183]	train-mlogloss:0.19008	eval-mlogloss:0.14470
[184]	train-mlogloss:0.18886	eval-mlogloss:0.14342
[185]	train-mlogloss:0.18772	eval-mlogloss:0.14201
[186]	train-mlogloss:0.18650	eval-mlogloss:0.14101
[187]	train-mlogloss:0.18539	eval-mlogloss:0.14003
[188]	train-mlogloss:0.18423	eval-mlogloss:0.13868
[189]	train-mlogloss:0.18320	eval-mlogloss:0.13780
[190]	train-mlogloss:0.18196	eval-mlogloss:0.13627
[191]	train-mlogloss:0.18086	eval-mlogloss:0.13507
[192]	train-mlogloss:0.17957	eval-mlogloss:0.13377
[193]	train-mlogloss:0.17831	eval-mlogloss:0.13257
[194]	train-mlogloss:0.17728	eval-mlogloss:0.13129
[195]	train-mlogloss:0.17614	eval-mlogloss:0.13043
[196]	train-mlogloss:0.17507	eval-mlogloss:0.12925
[197]	train-mlogloss:0.17427	eval-mlogloss:0.12845
[198]	train-mlogloss:0.17317	eval-mlogloss:0.12728
[199]	train-mlogloss:0.17204	eval-mlogloss:0.12611
[200]	train-mlogloss:0.17099	eval-mlogloss:0.12487
[201]	train-mlogloss:0.17011	eval-mlogloss:0.12382
[202]	train-mlogloss:0.16892	eval-mlogloss:0.12293
[203]	train-mlogloss:0.16788	eval-mlogloss:0.12183
[204]	train-mlogloss:0.16692	eval-mlogloss:0.12084
[205]	train-mlogloss:0.16588	eval-mlogloss:0.11966
[206]	train-mlogloss:0.16498	eval-mlogloss:0.11869
[207]	train-mlogloss:0.16392	eval-mlogloss:0.11751
[208]	train-mlogloss:0.16299	eval-mlogloss:0.11680
[209]	train-mlogloss:0.16213	eval-mlogloss:0.11581
[210]	train-mlogloss:0.16123	eval-mlogloss:0.11494
[211]	train-mlogloss:0.16016	eval-mlogloss:0.11374
[212]	train-mlogloss:0.15945	eval-mlogloss:0.11280
[213]	train-mlogloss:0.15856	eval-mlogloss:0.11175
[214]	train-mlogloss:0.15777	eval-mlogloss:0.11096
[215]	train-mlogloss:0.15678	eval-mlogloss:0.11042
[216]	train-mlogloss:0.15580	eval-mlogloss:0.10965
[217]	train-mlogloss:0.15515	eval-mlogloss:0.10886
[218]	train-mlogloss:0.15441	eval-mlogloss:0.10819
[219]	train-mlogloss:0.15336	eval-mlogloss:0.10711
[220]	train-mlogloss:0.15246	eval-mlogloss:0.10610
[221]	train-mlogloss:0.15172	eval-mlogloss:0.10548
[222]	train-mlogloss:0.15076	eval-mlogloss:0.10439
[223]	train-mlogloss:0.15015	eval-mlogloss:0.10363
[224]	train-mlogloss:0.14951	eval-mlogloss:0.10294
[225]	train-mlogloss:0.14877	eval-mlogloss:0.10204
[226]	train-mlogloss:0.14805	eval-mlogloss:0.10120
[227]	train-mlogloss:0.14730	eval-mlogloss:0.10046
[228]	train-mlogloss:0.14666	eval-mlogloss:0.09996
[229]	train-mlogloss:0.14605	eval-mlogloss:0.09932
[230]	train-mlogloss:0.14532	eval-mlogloss:0.09872
[231]	train-mlogloss:0.14473	eval-mlogloss:0.09801
[232]	train-mlogloss:0.14408	eval-mlogloss:0.09722
[233]	train-mlogloss:0.14311	eval-mlogloss:0.09628
[234]	train-mlogloss:0.14238	eval-mlogloss:0.09550
[235]	train-mlogloss:0.14173	eval-mlogloss:0.09474
[236]	train-mlogloss:0.14100	eval-mlogloss:0.09412
[237]	train-mlogloss:0.14044	eval-mlogloss:0.09340
[238]	train-mlogloss:0.13974	eval-mlogloss:0.09272
[239]	train-mlogloss:0.13894	eval-mlogloss:0.09189
[240]	train-mlogloss:0.13833	eval-mlogloss:0.09156
[241]	train-mlogloss:0.13775	eval-mlogloss:0.09109
[242]	train-mlogloss:0.13723	eval-mlogloss:0.09085
[243]	train-mlogloss:0.13664	eval-mlogloss:0.09011
[244]	train-mlogloss:0.13618	eval-mlogloss:0.08955
[245]	train-mlogloss:0.13569	eval-mlogloss:0.08911
[246]	train-mlogloss:0.13508	eval-mlogloss:0.08846
[247]	train-mlogloss:0.13441	eval-mlogloss:0.08794
[248]	train-mlogloss:0.13387	eval-mlogloss:0.08727
[249]	train-mlogloss:0.13343	eval-mlogloss:0.08673
[250]	train-mlogloss:0.13298	eval-mlogloss:0.08629
[251]	train-mlogloss:0.13234	eval-mlogloss:0.08550
[252]	train-mlogloss:0.13177	eval-mlogloss:0.08469
[253]	train-mlogloss:0.13121	eval-mlogloss:0.08402
[254]	train-mlogloss:0.13074	eval-mlogloss:0.08367
[255]	train-mlogloss:0.13029	eval-mlogloss:0.08333
[256]	train-mlogloss:0.12978	eval-mlogloss:0.08314
[257]	train-mlogloss:0.12919	eval-mlogloss:0.08249
[258]	train-mlogloss:0.12886	eval-mlogloss:0.08209
[259]	train-mlogloss:0.12855	eval-mlogloss:0.08174
[260]	train-mlogloss:0.12802	eval-mlogloss:0.08107
[261]	train-mlogloss:0.12740	eval-mlogloss:0.08039
[262]	train-mlogloss:0.12689	eval-mlogloss:0.07992
[263]	train-mlogloss:0.12651	eval-mlogloss:0.07945
[264]	train-mlogloss:0.12606	eval-mlogloss:0.07882
[265]	train-mlogloss:0.12577	eval-mlogloss:0.07867
[266]	train-mlogloss:0.12544	eval-mlogloss:0.07838
[267]	train-mlogloss:0.12500	eval-mlogloss:0.07800
[268]	train-mlogloss:0.12457	eval-mlogloss:0.07745
[269]	train-mlogloss:0.12417	eval-mlogloss:0.07696
[270]	train-mlogloss:0.12359	eval-mlogloss:0.07632
[271]	train-mlogloss:0.12325	eval-mlogloss:0.07581
[272]	train-mlogloss:0.12285	eval-mlogloss:0.07532
[273]	train-mlogloss:0.12242	eval-mlogloss:0.07498
[274]	train-mlogloss:0.12200	eval-mlogloss:0.07437
[275]	train-mlogloss:0.12144	eval-mlogloss:0.07399
[276]	train-mlogloss:0.12106	eval-mlogloss:0.07368
[277]	train-mlogloss:0.12084	eval-mlogloss:0.07334
[278]	train-mlogloss:0.12047	eval-mlogloss:0.07302
[279]	train-mlogloss:0.12004	eval-mlogloss:0.07267
[280]	train-mlogloss:0.11978	eval-mlogloss:0.07245
[281]	train-mlogloss:0.11932	eval-mlogloss:0.07179
[282]	train-mlogloss:0.11890	eval-mlogloss:0.07148
[283]	train-mlogloss:0.11877	eval-mlogloss:0.07113
[284]	train-mlogloss:0.11859	eval-mlogloss:0.07080
[285]	train-mlogloss:0.11837	eval-mlogloss:0.07041
[286]	train-mlogloss:0.11812	eval-mlogloss:0.07000
[287]	train-mlogloss:0.11789	eval-mlogloss:0.06980
[288]	train-mlogloss:0.11757	eval-mlogloss:0.06948
[289]	train-mlogloss:0.11729	eval-mlogloss:0.06920
[290]	train-mlogloss:0.11722	eval-mlogloss:0.06914
[291]	train-mlogloss:0.11702	eval-mlogloss:0.06885
[292]	train-mlogloss:0.11692	eval-mlogloss:0.06871
[293]	train-mlogloss:0.11657	eval-mlogloss:0.06829
[294]	train-mlogloss:0.11646	eval-mlogloss:0.06816
[295]	train-mlogloss:0.11603	eval-mlogloss:0.06768
[296]	train-mlogloss:0.11580	eval-mlogloss:0.06758
[297]	train-mlogloss:0.11577	eval-mlogloss:0.06753
[298]	train-mlogloss:0.11554	eval-mlogloss:0.06723
[299]	train-mlogloss:0.11516	eval-mlogloss:0.06685

[I 2025-06-12 19:47:48,807] Trial 24 finished with value: 1.0 and parameters: {'lambda': 1.8767535176317062e-08, 'alpha': 1.4308555449991256e-06, 'eta': 0.011143802552676135, 'gamma': 0.0016794011895620688, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.4810744889767691, 'colsample_bytree': 0.8882954976477065}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.00884	eval-mlogloss:1.00995
[1]	train-mlogloss:0.94394	eval-mlogloss:0.93475
[2]	train-mlogloss:0.87153	eval-mlogloss:0.85641

[I 2025-06-12 19:47:48,945] Trial 25 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03675	eval-mlogloss:1.03752
[1]	train-mlogloss:0.97904	eval-mlogloss:0.97660
[2]	train-mlogloss:0.92370	eval-mlogloss:0.91753
[3]	train-mlogloss:0.87212	eval-mlogloss:0.86389
[4]	train-mlogloss:0.82683	eval-mlogloss:0.81636
[5]	train-mlogloss:0.78241	eval-mlogloss:0.76854
[6]	train-mlogloss:0.74329	eval-mlogloss:0.72620
[7]	train-mlogloss:0.70781	eval-mlogloss:0.68810

[I 2025-06-12 19:47:49,120] Trial 26 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.97962	eval-mlogloss:0.98122
[1]	train-mlogloss:0.89609	eval-mlogloss:0.88429
[2]	train-mlogloss:0.80537	eval-mlogloss:0.78871

[I 2025-06-12 19:47:49,266] Trial 27 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.85071	eval-mlogloss:0.84163
[1]	train-mlogloss:0.75818	eval-mlogloss:0.72012
[2]	train-mlogloss:0.67095	eval-mlogloss:0.63188

[I 2025-06-12 19:47:49,408] Trial 28 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.84614	eval-mlogloss:0.84164
[1]	train-mlogloss:0.72366	eval-mlogloss:0.72736
[2]	train-mlogloss:0.58054	eval-mlogloss:0.58050

[I 2025-06-12 19:47:49,553] Trial 29 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.89855	eval-mlogloss:0.90092
[1]	train-mlogloss:0.74570	eval-mlogloss:0.73375

[I 2025-06-12 19:47:49,679] Trial 30 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07121	eval-mlogloss:1.07114
[1]	train-mlogloss:1.04418	eval-mlogloss:1.04260
[2]	train-mlogloss:1.01695	eval-mlogloss:1.01424
[3]	train-mlogloss:0.99039	eval-mlogloss:0.98633
[4]	train-mlogloss:0.96569	eval-mlogloss:0.96130
[5]	train-mlogloss:0.94126	eval-mlogloss:0.93544
[6]	train-mlogloss:0.91832	eval-mlogloss:0.91174
[7]	train-mlogloss:0.89688	eval-mlogloss:0.88899
[8]	train-mlogloss:0.87561	eval-mlogloss:0.86559
[9]	train-mlogloss:0.85427	eval-mlogloss:0.84281
[10]	train-mlogloss:0.83403	eval-mlogloss:0.82175
[11]	train-mlogloss:0.81495	eval-mlogloss:0.80082
[12]	train-mlogloss:0.79647	eval-mlogloss:0.78205
[13]	train-mlogloss:0.77758	eval-mlogloss:0.76250
[14]	train-mlogloss:0.76044	eval-mlogloss:0.74405
[15]	train-mlogloss:0.74282	eval-mlogloss:0.72571
[16]	train-mlogloss:0.72613	eval-mlogloss:0.70828
[17]	train-mlogloss:0.71073	eval-mlogloss:0.69193
[18]	train-mlogloss:0.69502	eval-mlogloss:0.67546
[19]	train-mlogloss:0.67980	eval-mlogloss:0.65902
[20]	train-mlogloss:0.66526	eval-mlogloss:0.64372
[21]	train-mlogloss:0.65186	eval-mlogloss:0.62963
[22]	train-mlogloss:0.63719	eval-mlogloss:0.61420
[23]	train-mlogloss:0.62318	eval-mlogloss:0.59966
[24]	train-mlogloss:0.61002	eval-mlogloss:0.58628
[25]	train-mlogloss:0.59722	eval-mlogloss:0.57242
[26]	train-mlogloss:0.58500	eval-mlogloss:0.55965
[27]	train-mlogloss:0.57258	eval-mlogloss:0.54706
[28]	train-mlogloss:0.56075	eval-mlogloss:0.53437
[29]	train-mlogloss:0.54911	eval-mlogloss:0.52206
[30]	train-mlogloss:0.53794	eval-mlogloss:0.51061
[31]	train-mlogloss:0.52680	eval-mlogloss:0.49889
[32]	train-mlogloss:0.51638	eval-mlogloss:0.48872

[I 2025-06-12 19:47:50,218] Trial 31 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:0.97692	eval-mlogloss:0.97220
[1]	train-mlogloss:0.87348	eval-mlogloss:0.86554
[2]	train-mlogloss:0.78111	eval-mlogloss:0.77050

[I 2025-06-12 19:47:50,359] Trial 32 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08533	eval-mlogloss:1.08465
[1]	train-mlogloss:1.07225	eval-mlogloss:1.07067
[2]	train-mlogloss:1.05911	eval-mlogloss:1.05684
[3]	train-mlogloss:1.04590	eval-mlogloss:1.04308
[4]	train-mlogloss:1.03328	eval-mlogloss:1.03021
[5]	train-mlogloss:1.02065	eval-mlogloss:1.01680
[6]	train-mlogloss:1.00858	eval-mlogloss:1.00459
[7]	train-mlogloss:0.99684	eval-mlogloss:0.99203
[8]	train-mlogloss:0.98494	eval-mlogloss:0.97916
[9]	train-mlogloss:0.97312	eval-mlogloss:0.96659
[10]	train-mlogloss:0.96172	eval-mlogloss:0.95467
[11]	train-mlogloss:0.95047	eval-mlogloss:0.94266
[12]	train-mlogloss:0.93970	eval-mlogloss:0.93164
[13]	train-mlogloss:0.92864	eval-mlogloss:0.92008
[14]	train-mlogloss:0.91814	eval-mlogloss:0.90921
[15]	train-mlogloss:0.90757	eval-mlogloss:0.89816
[16]	train-mlogloss:0.89724	eval-mlogloss:0.88731
[17]	train-mlogloss:0.88760	eval-mlogloss:0.87690
[18]	train-mlogloss:0.87780	eval-mlogloss:0.86702
[19]	train-mlogloss:0.86792	eval-mlogloss:0.85655
[20]	train-mlogloss:0.85836	eval-mlogloss:0.84652
[21]	train-mlogloss:0.84931	eval-mlogloss:0.83690
[22]	train-mlogloss:0.83953	eval-mlogloss:0.82663
[23]	train-mlogloss:0.82997	eval-mlogloss:0.81658
[24]	train-mlogloss:0.82064	eval-mlogloss:0.80686
[25]	train-mlogloss:0.81180	eval-mlogloss:0.79762
[26]	train-mlogloss:0.80312	eval-mlogloss:0.78850
[27]	train-mlogloss:0.79438	eval-mlogloss:0.77935
[28]	train-mlogloss:0.78579	eval-mlogloss:0.77019
[29]	train-mlogloss:0.77724	eval-mlogloss:0.76139
[30]	train-mlogloss:0.76891	eval-mlogloss:0.75294
[31]	train-mlogloss:0.76052	eval-mlogloss:0.74410
[32]	train-mlogloss:0.75247	eval-mlogloss:0.73600
[33]	train-mlogloss:0.74473	eval-mlogloss:0.72773
[34]	train-mlogloss:0.73692	eval-mlogloss:0.71976
[35]	train-mlogloss:0.72963	eval-mlogloss:0.71191
[36]	train-mlogloss:0.72191	eval-mlogloss:0.70436
[37]	train-mlogloss:0.71440	eval-mlogloss:0.69643
[38]	train-mlogloss:0.70721	eval-mlogloss:0.68933
[39]	train-mlogloss:0.69972	eval-mlogloss:0.68143
[40]	train-mlogloss:0.69236	eval-mlogloss:0.67382
[41]	train-mlogloss:0.68524	eval-mlogloss:0.66636
[42]	train-mlogloss:0.67811	eval-mlogloss:0.65872
[43]	train-mlogloss:0.67105	eval-mlogloss:0.65145
[44]	train-mlogloss:0.66410	eval-mlogloss:0.64415
[45]	train-mlogloss:0.65715	eval-mlogloss:0.63704
[46]	train-mlogloss:0.65018	eval-mlogloss:0.62972
[47]	train-mlogloss:0.64368	eval-mlogloss:0.62307
[48]	train-mlogloss:0.63719	eval-mlogloss:0.61634
[49]	train-mlogloss:0.63063	eval-mlogloss:0.60980
[50]	train-mlogloss:0.62430	eval-mlogloss:0.60295
[51]	train-mlogloss:0.61819	eval-mlogloss:0.59617
[52]	train-mlogloss:0.61224	eval-mlogloss:0.58987
[53]	train-mlogloss:0.60628	eval-mlogloss:0.58352
[54]	train-mlogloss:0.60024	eval-mlogloss:0.57734
[55]	train-mlogloss:0.59411	eval-mlogloss:0.57150
[56]	train-mlogloss:0.58831	eval-mlogloss:0.56558
[57]	train-mlogloss:0.58259	eval-mlogloss:0.55961
[58]	train-mlogloss:0.57696	eval-mlogloss:0.55367
[59]	train-mlogloss:0.57142	eval-mlogloss:0.54755
[60]	train-mlogloss:0.56577	eval-mlogloss:0.54180
[61]	train-mlogloss:0.56038	eval-mlogloss:0.53607
[62]	train-mlogloss:0.55474	eval-mlogloss:0.53017
[63]	train-mlogloss:0.54948	eval-mlogloss:0.52513
[64]	train-mlogloss:0.54419	eval-mlogloss:0.51948
[65]	train-mlogloss:0.53893	eval-mlogloss:0.51393
[66]	train-mlogloss:0.53364	eval-mlogloss:0.50822
[67]	train-mlogloss:0.52853	eval-mlogloss:0.50339
[68]	train-mlogloss:0.52368	eval-mlogloss:0.49807
[69]	train-mlogloss:0.51882	eval-mlogloss:0.49293
[70]	train-mlogloss:0.51388	eval-mlogloss:0.48774
[71]	train-mlogloss:0.50908	eval-mlogloss:0.48242
[72]	train-mlogloss:0.50440	eval-mlogloss:0.47787
[73]	train-mlogloss:0.49960	eval-mlogloss:0.47344
[74]	train-mlogloss:0.49505	eval-mlogloss:0.46879
[75]	train-mlogloss:0.49044	eval-mlogloss:0.46419
[76]	train-mlogloss:0.48598	eval-mlogloss:0.45950
[77]	train-mlogloss:0.48137	eval-mlogloss:0.45456
[78]	train-mlogloss:0.47694	eval-mlogloss:0.44966
[79]	train-mlogloss:0.47245	eval-mlogloss:0.44506
[80]	train-mlogloss:0.46820	eval-mlogloss:0.44055
[81]	train-mlogloss:0.46392	eval-mlogloss:0.43605
[82]	train-mlogloss:0.45971	eval-mlogloss:0.43142
[83]	train-mlogloss:0.45555	eval-mlogloss:0.42702
[84]	train-mlogloss:0.45131	eval-mlogloss:0.42241
[85]	train-mlogloss:0.44720	eval-mlogloss:0.41825
[86]	train-mlogloss:0.44316	eval-mlogloss:0.41373
[87]	train-mlogloss:0.43912	eval-mlogloss:0.40943
[88]	train-mlogloss:0.43522	eval-mlogloss:0.40542
[89]	train-mlogloss:0.43132	eval-mlogloss:0.40121
[90]	train-mlogloss:0.42759	eval-mlogloss:0.39726
[91]	train-mlogloss:0.42372	eval-mlogloss:0.39338
[92]	train-mlogloss:0.41999	eval-mlogloss:0.38963
[93]	train-mlogloss:0.41632	eval-mlogloss:0.38567
[94]	train-mlogloss:0.41264	eval-mlogloss:0.38153
[95]	train-mlogloss:0.40903	eval-mlogloss:0.37795
[96]	train-mlogloss:0.40548	eval-mlogloss:0.37389
[97]	train-mlogloss:0.40186	eval-mlogloss:0.37005
[98]	train-mlogloss:0.39830	eval-mlogloss:0.36628
[99]	train-mlogloss:0.39488	eval-mlogloss:0.36289
[100]	train-mlogloss:0.39162	eval-mlogloss:0.35956
[101]	train-mlogloss:0.38799	eval-mlogloss:0.35631
[102]	train-mlogloss:0.38454	eval-mlogloss:0.35271
[103]	train-mlogloss:0.38105	eval-mlogloss:0.34938
[104]	train-mlogloss:0.37784	eval-mlogloss:0.34590
[105]	train-mlogloss:0.37460	eval-mlogloss:0.34259
[106]	train-mlogloss:0.37138	eval-mlogloss:0.33950
[107]	train-mlogloss:0.36822	eval-mlogloss:0.33627
[108]	train-mlogloss:0.36512	eval-mlogloss:0.33299
[109]	train-mlogloss:0.36204	eval-mlogloss:0.32987
[110]	train-mlogloss:0.35905	eval-mlogloss:0.32657
[111]	train-mlogloss:0.35605	eval-mlogloss:0.32330
[112]	train-mlogloss:0.35310	eval-mlogloss:0.32018
[113]	train-mlogloss:0.35024	eval-mlogloss:0.31704
[114]	train-mlogloss:0.34736	eval-mlogloss:0.31391
[115]	train-mlogloss:0.34452	eval-mlogloss:0.31075
[116]	train-mlogloss:0.34167	eval-mlogloss:0.30826
[117]	train-mlogloss:0.33890	eval-mlogloss:0.30517
[118]	train-mlogloss:0.33591	eval-mlogloss:0.30273
[119]	train-mlogloss:0.33313	eval-mlogloss:0.29991
[120]	train-mlogloss:0.33040	eval-mlogloss:0.29725
[121]	train-mlogloss:0.32759	eval-mlogloss:0.29431
[122]	train-mlogloss:0.32487	eval-mlogloss:0.29141
[123]	train-mlogloss:0.32224	eval-mlogloss:0.28864
[124]	train-mlogloss:0.31965	eval-mlogloss:0.28589
[125]	train-mlogloss:0.31694	eval-mlogloss:0.28339
[126]	train-mlogloss:0.31436	eval-mlogloss:0.28085
[127]	train-mlogloss:0.31192	eval-mlogloss:0.27803
[128]	train-mlogloss:0.30945	eval-mlogloss:0.27535
[129]	train-mlogloss:0.30702	eval-mlogloss:0.27275
[130]	train-mlogloss:0.30481	eval-mlogloss:0.27046
[131]	train-mlogloss:0.30233	eval-mlogloss:0.26780
[132]	train-mlogloss:0.29999	eval-mlogloss:0.26533
[133]	train-mlogloss:0.29750	eval-mlogloss:0.26277
[134]	train-mlogloss:0.29520	eval-mlogloss:0.26019
[135]	train-mlogloss:0.29285	eval-mlogloss:0.25754
[136]	train-mlogloss:0.29043	eval-mlogloss:0.25502
[137]	train-mlogloss:0.28807	eval-mlogloss:0.25248
[138]	train-mlogloss:0.28584	eval-mlogloss:0.25026
[139]	train-mlogloss:0.28370	eval-mlogloss:0.24799
[140]	train-mlogloss:0.28136	eval-mlogloss:0.24565
[141]	train-mlogloss:0.27924	eval-mlogloss:0.24328
[142]	train-mlogloss:0.27705	eval-mlogloss:0.24079
[143]	train-mlogloss:0.27500	eval-mlogloss:0.23856
[144]	train-mlogloss:0.27280	eval-mlogloss:0.23678
[145]	train-mlogloss:0.27073	eval-mlogloss:0.23442
[146]	train-mlogloss:0.26861	eval-mlogloss:0.23208
[147]	train-mlogloss:0.26651	eval-mlogloss:0.22990
[148]	train-mlogloss:0.26443	eval-mlogloss:0.22759
[149]	train-mlogloss:0.26226	eval-mlogloss:0.22556
[150]	train-mlogloss:0.26036	eval-mlogloss:0.22350
[151]	train-mlogloss:0.25846	eval-mlogloss:0.22151
[152]	train-mlogloss:0.25646	eval-mlogloss:0.21924
[153]	train-mlogloss:0.25458	eval-mlogloss:0.21716
[154]	train-mlogloss:0.25271	eval-mlogloss:0.21520
[155]	train-mlogloss:0.25076	eval-mlogloss:0.21336
[156]	train-mlogloss:0.24892	eval-mlogloss:0.21118
[157]	train-mlogloss:0.24706	eval-mlogloss:0.20914
[158]	train-mlogloss:0.24522	eval-mlogloss:0.20732
[159]	train-mlogloss:0.24333	eval-mlogloss:0.20566
[160]	train-mlogloss:0.24164	eval-mlogloss:0.20393
[161]	train-mlogloss:0.23967	eval-mlogloss:0.20257
[162]	train-mlogloss:0.23788	eval-mlogloss:0.20098
[163]	train-mlogloss:0.23596	eval-mlogloss:0.19969
[164]	train-mlogloss:0.23414	eval-mlogloss:0.19777
[165]	train-mlogloss:0.23232	eval-mlogloss:0.19619
[166]	train-mlogloss:0.23068	eval-mlogloss:0.19447
[167]	train-mlogloss:0.22905	eval-mlogloss:0.19277
[168]	train-mlogloss:0.22745	eval-mlogloss:0.19112
[169]	train-mlogloss:0.22592	eval-mlogloss:0.18928
[170]	train-mlogloss:0.22438	eval-mlogloss:0.18761
[171]	train-mlogloss:0.22275	eval-mlogloss:0.18593
[172]	train-mlogloss:0.22130	eval-mlogloss:0.18431
[173]	train-mlogloss:0.21951	eval-mlogloss:0.18283
[174]	train-mlogloss:0.21793	eval-mlogloss:0.18114
[175]	train-mlogloss:0.21641	eval-mlogloss:0.17963
[176]	train-mlogloss:0.21495	eval-mlogloss:0.17816
[177]	train-mlogloss:0.21347	eval-mlogloss:0.17652
[178]	train-mlogloss:0.21189	eval-mlogloss:0.17473
[179]	train-mlogloss:0.21046	eval-mlogloss:0.17324
[180]	train-mlogloss:0.20909	eval-mlogloss:0.17156
[181]	train-mlogloss:0.20765	eval-mlogloss:0.17003
[182]	train-mlogloss:0.20607	eval-mlogloss:0.16860
[183]	train-mlogloss:0.20456	eval-mlogloss:0.16712
[184]	train-mlogloss:0.20309	eval-mlogloss:0.16601
[185]	train-mlogloss:0.20160	eval-mlogloss:0.16480
[186]	train-mlogloss:0.20020	eval-mlogloss:0.16353
[187]	train-mlogloss:0.19886	eval-mlogloss:0.16215
[188]	train-mlogloss:0.19740	eval-mlogloss:0.16054
[189]	train-mlogloss:0.19602	eval-mlogloss:0.15937
[190]	train-mlogloss:0.19472	eval-mlogloss:0.15803
[191]	train-mlogloss:0.19350	eval-mlogloss:0.15661
[192]	train-mlogloss:0.19208	eval-mlogloss:0.15524
[193]	train-mlogloss:0.19079	eval-mlogloss:0.15387
[194]	train-mlogloss:0.18961	eval-mlogloss:0.15262
[195]	train-mlogloss:0.18835	eval-mlogloss:0.15147
[196]	train-mlogloss:0.18712	eval-mlogloss:0.15013
[197]	train-mlogloss:0.18601	eval-mlogloss:0.14889
[198]	train-mlogloss:0.18470	eval-mlogloss:0.14766
[199]	train-mlogloss:0.18335	eval-mlogloss:0.14661
[200]	train-mlogloss:0.18209	eval-mlogloss:0.14547
[201]	train-mlogloss:0.18090	eval-mlogloss:0.14401
[202]	train-mlogloss:0.17964	eval-mlogloss:0.14312
[203]	train-mlogloss:0.17841	eval-mlogloss:0.14174
[204]	train-mlogloss:0.17719	eval-mlogloss:0.14070
[205]	train-mlogloss:0.17600	eval-mlogloss:0.13949
[206]	train-mlogloss:0.17485	eval-mlogloss:0.13828
[207]	train-mlogloss:0.17368	eval-mlogloss:0.13706
[208]	train-mlogloss:0.17253	eval-mlogloss:0.13617
[209]	train-mlogloss:0.17151	eval-mlogloss:0.13513
[210]	train-mlogloss:0.17048	eval-mlogloss:0.13402
[211]	train-mlogloss:0.16929	eval-mlogloss:0.13309
[212]	train-mlogloss:0.16814	eval-mlogloss:0.13219
[213]	train-mlogloss:0.16716	eval-mlogloss:0.13119
[214]	train-mlogloss:0.16602	eval-mlogloss:0.13041
[215]	train-mlogloss:0.16487	eval-mlogloss:0.12958
[216]	train-mlogloss:0.16386	eval-mlogloss:0.12852
[217]	train-mlogloss:0.16289	eval-mlogloss:0.12740
[218]	train-mlogloss:0.16191	eval-mlogloss:0.12646
[219]	train-mlogloss:0.16097	eval-mlogloss:0.12552
[220]	train-mlogloss:0.15997	eval-mlogloss:0.12447
[221]	train-mlogloss:0.15912	eval-mlogloss:0.12361
[222]	train-mlogloss:0.15809	eval-mlogloss:0.12247
[223]	train-mlogloss:0.15717	eval-mlogloss:0.12131
[224]	train-mlogloss:0.15623	eval-mlogloss:0.12020
[225]	train-mlogloss:0.15528	eval-mlogloss:0.11907
[226]	train-mlogloss:0.15428	eval-mlogloss:0.11804
[227]	train-mlogloss:0.15344	eval-mlogloss:0.11714
[228]	train-mlogloss:0.15246	eval-mlogloss:0.11620
[229]	train-mlogloss:0.15160	eval-mlogloss:0.11513
[230]	train-mlogloss:0.15064	eval-mlogloss:0.11438
[231]	train-mlogloss:0.14964	eval-mlogloss:0.11359
[232]	train-mlogloss:0.14878	eval-mlogloss:0.11256
[233]	train-mlogloss:0.14787	eval-mlogloss:0.11166
[234]	train-mlogloss:0.14700	eval-mlogloss:0.11077
[235]	train-mlogloss:0.14619	eval-mlogloss:0.10989
[236]	train-mlogloss:0.14533	eval-mlogloss:0.10905
[237]	train-mlogloss:0.14456	eval-mlogloss:0.10822
[238]	train-mlogloss:0.14374	eval-mlogloss:0.10744
[239]	train-mlogloss:0.14287	eval-mlogloss:0.10648
[240]	train-mlogloss:0.14203	eval-mlogloss:0.10562
[241]	train-mlogloss:0.14128	eval-mlogloss:0.10506
[242]	train-mlogloss:0.14042	eval-mlogloss:0.10443
[243]	train-mlogloss:0.13971	eval-mlogloss:0.10369
[244]	train-mlogloss:0.13894	eval-mlogloss:0.10316
[245]	train-mlogloss:0.13816	eval-mlogloss:0.10227
[246]	train-mlogloss:0.13740	eval-mlogloss:0.10145
[247]	train-mlogloss:0.13661	eval-mlogloss:0.10071
[248]	train-mlogloss:0.13584	eval-mlogloss:0.09978
[249]	train-mlogloss:0.13514	eval-mlogloss:0.09898
[250]	train-mlogloss:0.13446	eval-mlogloss:0.09825
[251]	train-mlogloss:0.13371	eval-mlogloss:0.09741
[252]	train-mlogloss:0.13302	eval-mlogloss:0.09664
[253]	train-mlogloss:0.13233	eval-mlogloss:0.09591
[254]	train-mlogloss:0.13160	eval-mlogloss:0.09540
[255]	train-mlogloss:0.13090	eval-mlogloss:0.09470
[256]	train-mlogloss:0.13024	eval-mlogloss:0.09418
[257]	train-mlogloss:0.12962	eval-mlogloss:0.09344
[258]	train-mlogloss:0.12908	eval-mlogloss:0.09281
[259]	train-mlogloss:0.12842	eval-mlogloss:0.09206
[260]	train-mlogloss:0.12770	eval-mlogloss:0.09145
[261]	train-mlogloss:0.12712	eval-mlogloss:0.09070
[262]	train-mlogloss:0.12654	eval-mlogloss:0.09022
[263]	train-mlogloss:0.12596	eval-mlogloss:0.08974
[264]	train-mlogloss:0.12530	eval-mlogloss:0.08898
[265]	train-mlogloss:0.12462	eval-mlogloss:0.08841
[266]	train-mlogloss:0.12420	eval-mlogloss:0.08811
[267]	train-mlogloss:0.12354	eval-mlogloss:0.08760
[268]	train-mlogloss:0.12291	eval-mlogloss:0.08712
[269]	train-mlogloss:0.12231	eval-mlogloss:0.08654
[270]	train-mlogloss:0.12172	eval-mlogloss:0.08608
[271]	train-mlogloss:0.12119	eval-mlogloss:0.08549
[272]	train-mlogloss:0.12071	eval-mlogloss:0.08482
[273]	train-mlogloss:0.12013	eval-mlogloss:0.08421
[274]	train-mlogloss:0.11963	eval-mlogloss:0.08351
[275]	train-mlogloss:0.11909	eval-mlogloss:0.08296
[276]	train-mlogloss:0.11850	eval-mlogloss:0.08250
[277]	train-mlogloss:0.11791	eval-mlogloss:0.08181
[278]	train-mlogloss:0.11732	eval-mlogloss:0.08146
[279]	train-mlogloss:0.11677	eval-mlogloss:0.08080
[280]	train-mlogloss:0.11631	eval-mlogloss:0.08023
[281]	train-mlogloss:0.11581	eval-mlogloss:0.07976
[282]	train-mlogloss:0.11528	eval-mlogloss:0.07911
[283]	train-mlogloss:0.11472	eval-mlogloss:0.07871
[284]	train-mlogloss:0.11420	eval-mlogloss:0.07830
[285]	train-mlogloss:0.11374	eval-mlogloss:0.07772
[286]	train-mlogloss:0.11330	eval-mlogloss:0.07713
[287]	train-mlogloss:0.11276	eval-mlogloss:0.07665
[288]	train-mlogloss:0.11229	eval-mlogloss:0.07609
[289]	train-mlogloss:0.11184	eval-mlogloss:0.07569
[290]	train-mlogloss:0.11141	eval-mlogloss:0.07531
[291]	train-mlogloss:0.11102	eval-mlogloss:0.07476
[292]	train-mlogloss:0.11066	eval-mlogloss:0.07426
[293]	train-mlogloss:0.11018	eval-mlogloss:0.07390
[294]	train-mlogloss:0.10971	eval-mlogloss:0.07339
[295]	train-mlogloss:0.10924	eval-mlogloss:0.07293
[296]	train-mlogloss:0.10888	eval-mlogloss:0.07270
[297]	train-mlogloss:0.10851	eval-mlogloss:0.07215
[298]	train-mlogloss:0.10810	eval-mlogloss:0.07159
[299]	train-mlogloss:0.10760	eval-mlogloss:0.07104

[I 2025-06-12 19:47:52,758] Trial 33 finished with value: 1.0 and parameters: {'lambda': 5.8651587063264956e-08, 'alpha': 3.453857859300771e-06, 'eta': 0.010071698744777402, 'gamma': 0.2184417702035992, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7122552776062675, 'colsample_bytree': 0.8504764696470786}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.08414	eval-mlogloss:1.08371
[1]	train-mlogloss:1.06989	eval-mlogloss:1.06868
[2]	train-mlogloss:1.05543	eval-mlogloss:1.05375
[3]	train-mlogloss:1.04110	eval-mlogloss:1.03892
[4]	train-mlogloss:1.02757	eval-mlogloss:1.02482
[5]	train-mlogloss:1.01386	eval-mlogloss:1.01039
[6]	train-mlogloss:1.00106	eval-mlogloss:0.99680
[7]	train-mlogloss:0.98855	eval-mlogloss:0.98351
[8]	train-mlogloss:0.97602	eval-mlogloss:0.97016
[9]	train-mlogloss:0.96332	eval-mlogloss:0.95672
[10]	train-mlogloss:0.95120	eval-mlogloss:0.94405
[11]	train-mlogloss:0.93928	eval-mlogloss:0.93132
[12]	train-mlogloss:0.92772	eval-mlogloss:0.91926
[13]	train-mlogloss:0.91612	eval-mlogloss:0.90736
[14]	train-mlogloss:0.90506	eval-mlogloss:0.89551
[15]	train-mlogloss:0.89395	eval-mlogloss:0.88359
[16]	train-mlogloss:0.88290	eval-mlogloss:0.87190
[17]	train-mlogloss:0.87261	eval-mlogloss:0.86094
[18]	train-mlogloss:0.86230	eval-mlogloss:0.85027
[19]	train-mlogloss:0.85187	eval-mlogloss:0.83989
[20]	train-mlogloss:0.84166	eval-mlogloss:0.82911
[21]	train-mlogloss:0.83245	eval-mlogloss:0.81912
[22]	train-mlogloss:0.82214	eval-mlogloss:0.80843
[23]	train-mlogloss:0.81211	eval-mlogloss:0.79798
[24]	train-mlogloss:0.80239	eval-mlogloss:0.78761
[25]	train-mlogloss:0.79311	eval-mlogloss:0.77752
[26]	train-mlogloss:0.78397	eval-mlogloss:0.76774
[27]	train-mlogloss:0.77481	eval-mlogloss:0.75815
[28]	train-mlogloss:0.76579	eval-mlogloss:0.74859
[29]	train-mlogloss:0.75695	eval-mlogloss:0.73922
[30]	train-mlogloss:0.74820	eval-mlogloss:0.73050
[31]	train-mlogloss:0.73958	eval-mlogloss:0.72136
[32]	train-mlogloss:0.73138	eval-mlogloss:0.71280
[33]	train-mlogloss:0.72328	eval-mlogloss:0.70382
[34]	train-mlogloss:0.71520	eval-mlogloss:0.69560
[35]	train-mlogloss:0.70755	eval-mlogloss:0.68762
[36]	train-mlogloss:0.69969	eval-mlogloss:0.67948
[37]	train-mlogloss:0.69195	eval-mlogloss:0.67135
[38]	train-mlogloss:0.68458	eval-mlogloss:0.66378
[39]	train-mlogloss:0.67681	eval-mlogloss:0.65565
[40]	train-mlogloss:0.66949	eval-mlogloss:0.64826
[41]	train-mlogloss:0.66221	eval-mlogloss:0.64041
[42]	train-mlogloss:0.65503	eval-mlogloss:0.63290
[43]	train-mlogloss:0.64780	eval-mlogloss:0.62552
[44]	train-mlogloss:0.64065	eval-mlogloss:0.61810
[45]	train-mlogloss:0.63363	eval-mlogloss:0.61083
[46]	train-mlogloss:0.62667	eval-mlogloss:0.60363
[47]	train-mlogloss:0.61996	eval-mlogloss:0.59681
[48]	train-mlogloss:0.61320	eval-mlogloss:0.58981
[49]	train-mlogloss:0.60656	eval-mlogloss:0.58283
[50]	train-mlogloss:0.59998	eval-mlogloss:0.57569
[51]	train-mlogloss:0.59379	eval-mlogloss:0.56889
[52]	train-mlogloss:0.58761	eval-mlogloss:0.56223
[53]	train-mlogloss:0.58145	eval-mlogloss:0.55571
[54]	train-mlogloss:0.57528	eval-mlogloss:0.54923
[55]	train-mlogloss:0.56913	eval-mlogloss:0.54338
[56]	train-mlogloss:0.56327	eval-mlogloss:0.53719
[57]	train-mlogloss:0.55748	eval-mlogloss:0.53116
[58]	train-mlogloss:0.55175	eval-mlogloss:0.52512
[59]	train-mlogloss:0.54604	eval-mlogloss:0.51896
[60]	train-mlogloss:0.54039	eval-mlogloss:0.51347
[61]	train-mlogloss:0.53494	eval-mlogloss:0.50755
[62]	train-mlogloss:0.52946	eval-mlogloss:0.50189
[63]	train-mlogloss:0.52431	eval-mlogloss:0.49639
[64]	train-mlogloss:0.51901	eval-mlogloss:0.49094
[65]	train-mlogloss:0.51372	eval-mlogloss:0.48547
[66]	train-mlogloss:0.50858	eval-mlogloss:0.47991
[67]	train-mlogloss:0.50342	eval-mlogloss:0.47478
[68]	train-mlogloss:0.49850	eval-mlogloss:0.46939
[69]	train-mlogloss:0.49372	eval-mlogloss:0.46422
[70]	train-mlogloss:0.48880	eval-mlogloss:0.45903
[71]	train-mlogloss:0.48390	eval-mlogloss:0.45371
[72]	train-mlogloss:0.47927	eval-mlogloss:0.44878
[73]	train-mlogloss:0.47441	eval-mlogloss:0.44406
[74]	train-mlogloss:0.46986	eval-mlogloss:0.43937
[75]	train-mlogloss:0.46515	eval-mlogloss:0.43430
[76]	train-mlogloss:0.46074	eval-mlogloss:0.42947
[77]	train-mlogloss:0.45629	eval-mlogloss:0.42482
[78]	train-mlogloss:0.45182	eval-mlogloss:0.41988
[79]	train-mlogloss:0.44745	eval-mlogloss:0.41520
[80]	train-mlogloss:0.44320	eval-mlogloss:0.41080
[81]	train-mlogloss:0.43894	eval-mlogloss:0.40638
[82]	train-mlogloss:0.43470	eval-mlogloss:0.40169
[83]	train-mlogloss:0.43043	eval-mlogloss:0.39715
[84]	train-mlogloss:0.42633	eval-mlogloss:0.39280
[85]	train-mlogloss:0.42231	eval-mlogloss:0.38857
[86]	train-mlogloss:0.41829	eval-mlogloss:0.38400
[87]	train-mlogloss:0.41417	eval-mlogloss:0.37965
[88]	train-mlogloss:0.41023	eval-mlogloss:0.37565
[89]	train-mlogloss:0.40630	eval-mlogloss:0.37161
[90]	train-mlogloss:0.40242	eval-mlogloss:0.36811
[91]	train-mlogloss:0.39861	eval-mlogloss:0.36426
[92]	train-mlogloss:0.39489	eval-mlogloss:0.36049
[93]	train-mlogloss:0.39119	eval-mlogloss:0.35657
[94]	train-mlogloss:0.38752	eval-mlogloss:0.35256
[95]	train-mlogloss:0.38411	eval-mlogloss:0.34882
[96]	train-mlogloss:0.38065	eval-mlogloss:0.34509
[97]	train-mlogloss:0.37714	eval-mlogloss:0.34134
[98]	train-mlogloss:0.37366	eval-mlogloss:0.33800
[99]	train-mlogloss:0.37023	eval-mlogloss:0.33462
[100]	train-mlogloss:0.36701	eval-mlogloss:0.33140
[101]	train-mlogloss:0.36344	eval-mlogloss:0.32810
[102]	train-mlogloss:0.36005	eval-mlogloss:0.32457
[103]	train-mlogloss:0.35677	eval-mlogloss:0.32142
[104]	train-mlogloss:0.35350	eval-mlogloss:0.31805
[105]	train-mlogloss:0.35034	eval-mlogloss:0.31478
[106]	train-mlogloss:0.34696	eval-mlogloss:0.31186
[107]	train-mlogloss:0.34392	eval-mlogloss:0.30860
[108]	train-mlogloss:0.34089	eval-mlogloss:0.30541
[109]	train-mlogloss:0.33803	eval-mlogloss:0.30239
[110]	train-mlogloss:0.33511	eval-mlogloss:0.29911
[111]	train-mlogloss:0.33219	eval-mlogloss:0.29587
[112]	train-mlogloss:0.32938	eval-mlogloss:0.29276
[113]	train-mlogloss:0.32662	eval-mlogloss:0.28975
[114]	train-mlogloss:0.32387	eval-mlogloss:0.28683
[115]	train-mlogloss:0.32110	eval-mlogloss:0.28378
[116]	train-mlogloss:0.31846	eval-mlogloss:0.28112
[117]	train-mlogloss:0.31572	eval-mlogloss:0.27808
[118]	train-mlogloss:0.31286	eval-mlogloss:0.27547
[119]	train-mlogloss:0.31024	eval-mlogloss:0.27272
[120]	train-mlogloss:0.30760	eval-mlogloss:0.26997
[121]	train-mlogloss:0.30496	eval-mlogloss:0.26714
[122]	train-mlogloss:0.30232	eval-mlogloss:0.26448
[123]	train-mlogloss:0.29990	eval-mlogloss:0.26194
[124]	train-mlogloss:0.29743	eval-mlogloss:0.25946
[125]	train-mlogloss:0.29475	eval-mlogloss:0.25694
[126]	train-mlogloss:0.29233	eval-mlogloss:0.25438
[127]	train-mlogloss:0.28997	eval-mlogloss:0.25170
[128]	train-mlogloss:0.28764	eval-mlogloss:0.24904

[I 2025-06-12 19:47:53,732] Trial 34 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:1.02286	eval-mlogloss:1.02381
[1]	train-mlogloss:0.96705	eval-mlogloss:0.95916

[I 2025-06-12 19:47:53,870] Trial 35 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.04489	eval-mlogloss:1.04570
[1]	train-mlogloss:0.99320	eval-mlogloss:0.99006
[2]	train-mlogloss:0.94555	eval-mlogloss:0.94000
[3]	train-mlogloss:0.89922	eval-mlogloss:0.89096
[4]	train-mlogloss:0.85878	eval-mlogloss:0.84894
[5]	train-mlogloss:0.81739	eval-mlogloss:0.80428
[6]	train-mlogloss:0.78035	eval-mlogloss:0.76378
[7]	train-mlogloss:0.74747	eval-mlogloss:0.72790
[8]	train-mlogloss:0.71571	eval-mlogloss:0.69382

[I 2025-06-12 19:47:54,073] Trial 36 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.99620	eval-mlogloss:0.99181
[1]	train-mlogloss:0.95003	eval-mlogloss:0.93709
[2]	train-mlogloss:0.87370	eval-mlogloss:0.85615

[I 2025-06-12 19:47:54,234] Trial 37 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08575	eval-mlogloss:1.08596
[1]	train-mlogloss:1.07271	eval-mlogloss:1.07200
[2]	train-mlogloss:1.05993	eval-mlogloss:1.05860
[3]	train-mlogloss:1.04706	eval-mlogloss:1.04539
[4]	train-mlogloss:1.03498	eval-mlogloss:1.03315
[5]	train-mlogloss:1.02215	eval-mlogloss:1.01941
[6]	train-mlogloss:1.01011	eval-mlogloss:1.00637
[7]	train-mlogloss:0.99871	eval-mlogloss:0.99453
[8]	train-mlogloss:0.98722	eval-mlogloss:0.98228
[9]	train-mlogloss:0.97570	eval-mlogloss:0.96989
[10]	train-mlogloss:0.96452	eval-mlogloss:0.95846
[11]	train-mlogloss:0.95342	eval-mlogloss:0.94655
[12]	train-mlogloss:0.94280	eval-mlogloss:0.93597
[13]	train-mlogloss:0.93193	eval-mlogloss:0.92469
[14]	train-mlogloss:0.92152	eval-mlogloss:0.91376
[15]	train-mlogloss:0.91111	eval-mlogloss:0.90295
[16]	train-mlogloss:0.90078	eval-mlogloss:0.89209
[17]	train-mlogloss:0.89099	eval-mlogloss:0.88153
[18]	train-mlogloss:0.88103	eval-mlogloss:0.87095
[19]	train-mlogloss:0.87116	eval-mlogloss:0.86064
[20]	train-mlogloss:0.86191	eval-mlogloss:0.85080
[21]	train-mlogloss:0.85465	eval-mlogloss:0.84288
[22]	train-mlogloss:0.84525	eval-mlogloss:0.83260
[23]	train-mlogloss:0.83590	eval-mlogloss:0.82284
[24]	train-mlogloss:0.82813	eval-mlogloss:0.81510
[25]	train-mlogloss:0.81935	eval-mlogloss:0.80540
[26]	train-mlogloss:0.81070	eval-mlogloss:0.79629
[27]	train-mlogloss:0.80355	eval-mlogloss:0.78905
[28]	train-mlogloss:0.79489	eval-mlogloss:0.77985
[29]	train-mlogloss:0.78776	eval-mlogloss:0.77241
[30]	train-mlogloss:0.77995	eval-mlogloss:0.76431
[31]	train-mlogloss:0.77171	eval-mlogloss:0.75528
[32]	train-mlogloss:0.76413	eval-mlogloss:0.74784
[33]	train-mlogloss:0.75771	eval-mlogloss:0.74044
[34]	train-mlogloss:0.75006	eval-mlogloss:0.73237
[35]	train-mlogloss:0.74377	eval-mlogloss:0.72569
[36]	train-mlogloss:0.73622	eval-mlogloss:0.71782
[37]	train-mlogloss:0.72881	eval-mlogloss:0.70988
[38]	train-mlogloss:0.72336	eval-mlogloss:0.70419
[39]	train-mlogloss:0.71598	eval-mlogloss:0.69642
[40]	train-mlogloss:0.70876	eval-mlogloss:0.68886
[41]	train-mlogloss:0.70165	eval-mlogloss:0.68130
[42]	train-mlogloss:0.69474	eval-mlogloss:0.67380
[43]	train-mlogloss:0.68824	eval-mlogloss:0.66702
[44]	train-mlogloss:0.68161	eval-mlogloss:0.65985
[45]	train-mlogloss:0.67460	eval-mlogloss:0.65227
[46]	train-mlogloss:0.66941	eval-mlogloss:0.64647
[47]	train-mlogloss:0.66282	eval-mlogloss:0.63953
[48]	train-mlogloss:0.65658	eval-mlogloss:0.63308
[49]	train-mlogloss:0.64993	eval-mlogloss:0.62582
[50]	train-mlogloss:0.64393	eval-mlogloss:0.61928
[51]	train-mlogloss:0.63775	eval-mlogloss:0.61253
[52]	train-mlogloss:0.63160	eval-mlogloss:0.60593
[53]	train-mlogloss:0.62570	eval-mlogloss:0.59960
[54]	train-mlogloss:0.61980	eval-mlogloss:0.59344
[55]	train-mlogloss:0.61386	eval-mlogloss:0.58728
[56]	train-mlogloss:0.60897	eval-mlogloss:0.58245
[57]	train-mlogloss:0.60381	eval-mlogloss:0.57697
[58]	train-mlogloss:0.59861	eval-mlogloss:0.57128
[59]	train-mlogloss:0.59375	eval-mlogloss:0.56615
[60]	train-mlogloss:0.58965	eval-mlogloss:0.56197
[61]	train-mlogloss:0.58561	eval-mlogloss:0.55806
[62]	train-mlogloss:0.58021	eval-mlogloss:0.55254
[63]	train-mlogloss:0.57574	eval-mlogloss:0.54815
[64]	train-mlogloss:0.57086	eval-mlogloss:0.54315
[65]	train-mlogloss:0.56607	eval-mlogloss:0.53836
[66]	train-mlogloss:0.56089	eval-mlogloss:0.53250
[67]	train-mlogloss:0.55697	eval-mlogloss:0.52828
[68]	train-mlogloss:0.55254	eval-mlogloss:0.52322
[69]	train-mlogloss:0.54792	eval-mlogloss:0.51830
[70]	train-mlogloss:0.54349	eval-mlogloss:0.51357
[71]	train-mlogloss:0.53975	eval-mlogloss:0.50968
[72]	train-mlogloss:0.53625	eval-mlogloss:0.50566
[73]	train-mlogloss:0.53145	eval-mlogloss:0.50034
[74]	train-mlogloss:0.52741	eval-mlogloss:0.49593
[75]	train-mlogloss:0.52340	eval-mlogloss:0.49190
[76]	train-mlogloss:0.51914	eval-mlogloss:0.48695
[77]	train-mlogloss:0.51485	eval-mlogloss:0.48232
[78]	train-mlogloss:0.51052	eval-mlogloss:0.47757
[79]	train-mlogloss:0.50725	eval-mlogloss:0.47390
[80]	train-mlogloss:0.50358	eval-mlogloss:0.46965
[81]	train-mlogloss:0.50029	eval-mlogloss:0.46625
[82]	train-mlogloss:0.49701	eval-mlogloss:0.46291
[83]	train-mlogloss:0.49371	eval-mlogloss:0.45927
[84]	train-mlogloss:0.49067	eval-mlogloss:0.45607
[85]	train-mlogloss:0.48748	eval-mlogloss:0.45285
[86]	train-mlogloss:0.48425	eval-mlogloss:0.44927
[87]	train-mlogloss:0.48098	eval-mlogloss:0.44582
[88]	train-mlogloss:0.47730	eval-mlogloss:0.44158
[89]	train-mlogloss:0.47428	eval-mlogloss:0.43852
[90]	train-mlogloss:0.47129	eval-mlogloss:0.43531
[91]	train-mlogloss:0.46835	eval-mlogloss:0.43222
[92]	train-mlogloss:0.46531	eval-mlogloss:0.42916
[93]	train-mlogloss:0.46172	eval-mlogloss:0.42527
[94]	train-mlogloss:0.45882	eval-mlogloss:0.42222
[95]	train-mlogloss:0.45596	eval-mlogloss:0.41904
[96]	train-mlogloss:0.45242	eval-mlogloss:0.41507
[97]	train-mlogloss:0.44907	eval-mlogloss:0.41135
[98]	train-mlogloss:0.44545	eval-mlogloss:0.40733
[99]	train-mlogloss:0.44286	eval-mlogloss:0.40444
[100]	train-mlogloss:0.44028	eval-mlogloss:0.40156
[101]	train-mlogloss:0.43751	eval-mlogloss:0.39877
[102]	train-mlogloss:0.43479	eval-mlogloss:0.39552
[103]	train-mlogloss:0.43231	eval-mlogloss:0.39286
[104]	train-mlogloss:0.42894	eval-mlogloss:0.38920
[105]	train-mlogloss:0.42637	eval-mlogloss:0.38632
[106]	train-mlogloss:0.42368	eval-mlogloss:0.38311
[107]	train-mlogloss:0.42146	eval-mlogloss:0.38069
[108]	train-mlogloss:0.41895	eval-mlogloss:0.37788
[109]	train-mlogloss:0.41649	eval-mlogloss:0.37512
[110]	train-mlogloss:0.41401	eval-mlogloss:0.37237
[111]	train-mlogloss:0.41154	eval-mlogloss:0.36964
[112]	train-mlogloss:0.40919	eval-mlogloss:0.36700
[113]	train-mlogloss:0.40696	eval-mlogloss:0.36426
[114]	train-mlogloss:0.40456	eval-mlogloss:0.36153
[115]	train-mlogloss:0.40215	eval-mlogloss:0.35886
[116]	train-mlogloss:0.40005	eval-mlogloss:0.35657
[117]	train-mlogloss:0.39695	eval-mlogloss:0.35295
[118]	train-mlogloss:0.39506	eval-mlogloss:0.35118
[119]	train-mlogloss:0.39270	eval-mlogloss:0.34869
[120]	train-mlogloss:0.39054	eval-mlogloss:0.34642
[121]	train-mlogloss:0.38836	eval-mlogloss:0.34401
[122]	train-mlogloss:0.38608	eval-mlogloss:0.34147
[123]	train-mlogloss:0.38428	eval-mlogloss:0.33948
[124]	train-mlogloss:0.38158	eval-mlogloss:0.33660
[125]	train-mlogloss:0.37953	eval-mlogloss:0.33426
[126]	train-mlogloss:0.37862	eval-mlogloss:0.33324
[127]	train-mlogloss:0.37666	eval-mlogloss:0.33108
[128]	train-mlogloss:0.37452	eval-mlogloss:0.32872
[129]	train-mlogloss:0.37350	eval-mlogloss:0.32742
[130]	train-mlogloss:0.37167	eval-mlogloss:0.32553
[131]	train-mlogloss:0.36998	eval-mlogloss:0.32352
[132]	train-mlogloss:0.36809	eval-mlogloss:0.32137
[133]	train-mlogloss:0.36616	eval-mlogloss:0.31915
[134]	train-mlogloss:0.36452	eval-mlogloss:0.31741
[135]	train-mlogloss:0.36255	eval-mlogloss:0.31519
[136]	train-mlogloss:0.36176	eval-mlogloss:0.31418
[137]	train-mlogloss:0.35988	eval-mlogloss:0.31196
[138]	train-mlogloss:0.35820	eval-mlogloss:0.31011
[139]	train-mlogloss:0.35735	eval-mlogloss:0.30916
[140]	train-mlogloss:0.35559	eval-mlogloss:0.30720
[141]	train-mlogloss:0.35400	eval-mlogloss:0.30540
[142]	train-mlogloss:0.35223	eval-mlogloss:0.30356
[143]	train-mlogloss:0.35048	eval-mlogloss:0.30157
[144]	train-mlogloss:0.34869	eval-mlogloss:0.29969
[145]	train-mlogloss:0.34676	eval-mlogloss:0.29757
[146]	train-mlogloss:0.34512	eval-mlogloss:0.29588
[147]	train-mlogloss:0.34424	eval-mlogloss:0.29472
[148]	train-mlogloss:0.34256	eval-mlogloss:0.29283
[149]	train-mlogloss:0.34085	eval-mlogloss:0.29092
[150]	train-mlogloss:0.33987	eval-mlogloss:0.28979
[151]	train-mlogloss:0.33922	eval-mlogloss:0.28907
[152]	train-mlogloss:0.33843	eval-mlogloss:0.28810
[153]	train-mlogloss:0.33673	eval-mlogloss:0.28626
[154]	train-mlogloss:0.33496	eval-mlogloss:0.28437
[155]	train-mlogloss:0.33353	eval-mlogloss:0.28289
[156]	train-mlogloss:0.33216	eval-mlogloss:0.28132
[157]	train-mlogloss:0.33175	eval-mlogloss:0.28060
[158]	train-mlogloss:0.33104	eval-mlogloss:0.27984
[159]	train-mlogloss:0.32964	eval-mlogloss:0.27831
[160]	train-mlogloss:0.32890	eval-mlogloss:0.27744
[161]	train-mlogloss:0.32881	eval-mlogloss:0.27722
[162]	train-mlogloss:0.32822	eval-mlogloss:0.27654
[163]	train-mlogloss:0.32793	eval-mlogloss:0.27607
[164]	train-mlogloss:0.32697	eval-mlogloss:0.27510
[165]	train-mlogloss:0.32625	eval-mlogloss:0.27413
[166]	train-mlogloss:0.32551	eval-mlogloss:0.27318
[167]	train-mlogloss:0.32541	eval-mlogloss:0.27313
[168]	train-mlogloss:0.32402	eval-mlogloss:0.27171
[169]	train-mlogloss:0.32330	eval-mlogloss:0.27073
[170]	train-mlogloss:0.32264	eval-mlogloss:0.26988
[171]	train-mlogloss:0.32197	eval-mlogloss:0.26903
[172]	train-mlogloss:0.32072	eval-mlogloss:0.26760
[173]	train-mlogloss:0.32008	eval-mlogloss:0.26690
[174]	train-mlogloss:0.31926	eval-mlogloss:0.26587
[175]	train-mlogloss:0.31865	eval-mlogloss:0.26525
[176]	train-mlogloss:0.31803	eval-mlogloss:0.26434
[177]	train-mlogloss:0.31653	eval-mlogloss:0.26267
[178]	train-mlogloss:0.31588	eval-mlogloss:0.26192
[179]	train-mlogloss:0.31435	eval-mlogloss:0.26012
[180]	train-mlogloss:0.31425	eval-mlogloss:0.25985
[181]	train-mlogloss:0.31363	eval-mlogloss:0.25905
[182]	train-mlogloss:0.31297	eval-mlogloss:0.25818
[183]	train-mlogloss:0.31198	eval-mlogloss:0.25701
[184]	train-mlogloss:0.31117	eval-mlogloss:0.25628
[185]	train-mlogloss:0.31032	eval-mlogloss:0.25542
[186]	train-mlogloss:0.30967	eval-mlogloss:0.25457
[187]	train-mlogloss:0.30965	eval-mlogloss:0.25455
[188]	train-mlogloss:0.30961	eval-mlogloss:0.25446
[189]	train-mlogloss:0.30955	eval-mlogloss:0.25432
[190]	train-mlogloss:0.30948	eval-mlogloss:0.25416
[191]	train-mlogloss:0.30940	eval-mlogloss:0.25396
[192]	train-mlogloss:0.30938	eval-mlogloss:0.25393
[193]	train-mlogloss:0.30873	eval-mlogloss:0.25306
[194]	train-mlogloss:0.30815	eval-mlogloss:0.25237
[195]	train-mlogloss:0.30739	eval-mlogloss:0.25151
[196]	train-mlogloss:0.30694	eval-mlogloss:0.25103
[197]	train-mlogloss:0.30666	eval-mlogloss:0.25070
[198]	train-mlogloss:0.30664	eval-mlogloss:0.25073
[199]	train-mlogloss:0.30651	eval-mlogloss:0.25057
[200]	train-mlogloss:0.30646	eval-mlogloss:0.25054
[201]	train-mlogloss:0.30518	eval-mlogloss:0.24924
[202]	train-mlogloss:0.30515	eval-mlogloss:0.24922
[203]	train-mlogloss:0.30465	eval-mlogloss:0.24846
[204]	train-mlogloss:0.30416	eval-mlogloss:0.24785
[205]	train-mlogloss:0.30409	eval-mlogloss:0.24762
[206]	train-mlogloss:0.30404	eval-mlogloss:0.24751
[207]	train-mlogloss:0.30398	eval-mlogloss:0.24748
[208]	train-mlogloss:0.30394	eval-mlogloss:0.24744
[209]	train-mlogloss:0.30259	eval-mlogloss:0.24600
[210]	train-mlogloss:0.30251	eval-mlogloss:0.24578
[211]	train-mlogloss:0.30247	eval-mlogloss:0.24566
[212]	train-mlogloss:0.30241	eval-mlogloss:0.24550
[213]	train-mlogloss:0.30234	eval-mlogloss:0.24543
[214]	train-mlogloss:0.30232	eval-mlogloss:0.24545
[215]	train-mlogloss:0.30129	eval-mlogloss:0.24414
[216]	train-mlogloss:0.30070	eval-mlogloss:0.24322
[217]	train-mlogloss:0.30066	eval-mlogloss:0.24310
[218]	train-mlogloss:0.30013	eval-mlogloss:0.24242
[219]	train-mlogloss:0.29933	eval-mlogloss:0.24167
[220]	train-mlogloss:0.29926	eval-mlogloss:0.24161
[221]	train-mlogloss:0.29904	eval-mlogloss:0.24138
[222]	train-mlogloss:0.29902	eval-mlogloss:0.24140
[223]	train-mlogloss:0.29898	eval-mlogloss:0.24140
[224]	train-mlogloss:0.29828	eval-mlogloss:0.24049
[225]	train-mlogloss:0.29768	eval-mlogloss:0.23959
[226]	train-mlogloss:0.29763	eval-mlogloss:0.23954
[227]	train-mlogloss:0.29757	eval-mlogloss:0.23949
[228]	train-mlogloss:0.29704	eval-mlogloss:0.23888
[229]	train-mlogloss:0.29640	eval-mlogloss:0.23814
[230]	train-mlogloss:0.29634	eval-mlogloss:0.23797
[231]	train-mlogloss:0.29632	eval-mlogloss:0.23801
[232]	train-mlogloss:0.29626	eval-mlogloss:0.23798
[233]	train-mlogloss:0.29622	eval-mlogloss:0.23793
[234]	train-mlogloss:0.29603	eval-mlogloss:0.23770
[235]	train-mlogloss:0.29473	eval-mlogloss:0.23619
[236]	train-mlogloss:0.29420	eval-mlogloss:0.23562
[237]	train-mlogloss:0.29411	eval-mlogloss:0.23538
[238]	train-mlogloss:0.29405	eval-mlogloss:0.23538
[239]	train-mlogloss:0.29401	eval-mlogloss:0.23525
[240]	train-mlogloss:0.29399	eval-mlogloss:0.23525
[241]	train-mlogloss:0.29395	eval-mlogloss:0.23519
[242]	train-mlogloss:0.29352	eval-mlogloss:0.23464
[243]	train-mlogloss:0.29352	eval-mlogloss:0.23464
[244]	train-mlogloss:0.29349	eval-mlogloss:0.23452
[245]	train-mlogloss:0.29343	eval-mlogloss:0.23435
[246]	train-mlogloss:0.29340	eval-mlogloss:0.23436
[247]	train-mlogloss:0.29338	eval-mlogloss:0.23436
[248]	train-mlogloss:0.29338	eval-mlogloss:0.23436
[249]	train-mlogloss:0.29283	eval-mlogloss:0.23368
[250]	train-mlogloss:0.29279	eval-mlogloss:0.23351
[251]	train-mlogloss:0.29276	eval-mlogloss:0.23348
[252]	train-mlogloss:0.29271	eval-mlogloss:0.23342
[253]	train-mlogloss:0.29267	eval-mlogloss:0.23341
[254]	train-mlogloss:0.29265	eval-mlogloss:0.23341
[255]	train-mlogloss:0.29259	eval-mlogloss:0.23336
[256]	train-mlogloss:0.29255	eval-mlogloss:0.23334
[257]	train-mlogloss:0.29201	eval-mlogloss:0.23277
[258]	train-mlogloss:0.29180	eval-mlogloss:0.23249
[259]	train-mlogloss:0.29138	eval-mlogloss:0.23192
[260]	train-mlogloss:0.29133	eval-mlogloss:0.23178
[261]	train-mlogloss:0.29132	eval-mlogloss:0.23180
[262]	train-mlogloss:0.29125	eval-mlogloss:0.23159
[263]	train-mlogloss:0.29119	eval-mlogloss:0.23155
[264]	train-mlogloss:0.29115	eval-mlogloss:0.23145
[265]	train-mlogloss:0.29111	eval-mlogloss:0.23132
[266]	train-mlogloss:0.29103	eval-mlogloss:0.23111
[267]	train-mlogloss:0.29094	eval-mlogloss:0.23103
[268]	train-mlogloss:0.29086	eval-mlogloss:0.23099
[269]	train-mlogloss:0.29082	eval-mlogloss:0.23097
[270]	train-mlogloss:0.29034	eval-mlogloss:0.23025
[271]	train-mlogloss:0.29031	eval-mlogloss:0.23023
[272]	train-mlogloss:0.29028	eval-mlogloss:0.23023
[273]	train-mlogloss:0.29026	eval-mlogloss:0.23021
[274]	train-mlogloss:0.29024	eval-mlogloss:0.23025
[275]	train-mlogloss:0.29017	eval-mlogloss:0.23023
[276]	train-mlogloss:0.29017	eval-mlogloss:0.23022
[277]	train-mlogloss:0.29016	eval-mlogloss:0.23021
[278]	train-mlogloss:0.29006	eval-mlogloss:0.23016
[279]	train-mlogloss:0.29004	eval-mlogloss:0.23012
[280]	train-mlogloss:0.28956	eval-mlogloss:0.22946
[281]	train-mlogloss:0.28952	eval-mlogloss:0.22945
[282]	train-mlogloss:0.28950	eval-mlogloss:0.22947
[283]	train-mlogloss:0.28903	eval-mlogloss:0.22887
[284]	train-mlogloss:0.28899	eval-mlogloss:0.22883
[285]	train-mlogloss:0.28899	eval-mlogloss:0.22883
[286]	train-mlogloss:0.28891	eval-mlogloss:0.22874
[287]	train-mlogloss:0.28837	eval-mlogloss:0.22815
[288]	train-mlogloss:0.28835	eval-mlogloss:0.22808
[289]	train-mlogloss:0.28779	eval-mlogloss:0.22736
[290]	train-mlogloss:0.28776	eval-mlogloss:0.22735
[291]	train-mlogloss:0.28730	eval-mlogloss:0.22678
[292]	train-mlogloss:0.28727	eval-mlogloss:0.22671
[293]	train-mlogloss:0.28683	eval-mlogloss:0.22615
[294]	train-mlogloss:0.28678	eval-mlogloss:0.22613
[295]	train-mlogloss:0.28671	eval-mlogloss:0.22602
[296]	train-mlogloss:0.28671	eval-mlogloss:0.22604
[297]	train-mlogloss:0.28670	eval-mlogloss:0.22604
[298]	train-mlogloss:0.28664	eval-mlogloss:0.22596
[299]	train-mlogloss:0.28664	eval-mlogloss:0.22595

[I 2025-06-12 19:47:58,151] Trial 38 finished with value: 1.0 and parameters: {'lambda': 4.1671392017420505e-08, 'alpha': 0.0015540338764784955, 'eta': 0.010350333886370688, 'gamma': 0.016469942627163035, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.6234657993174102, 'colsample_bytree': 0.9289431775004935}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.95282	eval-mlogloss:0.95027
[1]	train-mlogloss:0.82965	eval-mlogloss:0.82148
[2]	train-mlogloss:0.72453	eval-mlogloss:0.70451

[I 2025-06-12 19:47:58,365] Trial 39 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88401	eval-mlogloss:0.87271
[1]	train-mlogloss:0.72425	eval-mlogloss:0.70710
[2]	train-mlogloss:0.60049	eval-mlogloss:0.57653

[I 2025-06-12 19:47:58,767] Trial 40 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08429	eval-mlogloss:1.08452
[1]	train-mlogloss:1.06980	eval-mlogloss:1.06897
[2]	train-mlogloss:1.05627	eval-mlogloss:1.05552
[3]	train-mlogloss:1.04305	eval-mlogloss:1.04125
[4]	train-mlogloss:1.02958	eval-mlogloss:1.02758
[5]	train-mlogloss:1.01561	eval-mlogloss:1.01276
[6]	train-mlogloss:1.00235	eval-mlogloss:0.99844
[7]	train-mlogloss:0.99008	eval-mlogloss:0.98595
[8]	train-mlogloss:0.97747	eval-mlogloss:0.97252
[9]	train-mlogloss:0.96482	eval-mlogloss:0.95890
[10]	train-mlogloss:0.95277	eval-mlogloss:0.94607
[11]	train-mlogloss:0.94080	eval-mlogloss:0.93328
[12]	train-mlogloss:0.92959	eval-mlogloss:0.92262
[13]	train-mlogloss:0.91770	eval-mlogloss:0.91027
[14]	train-mlogloss:0.90656	eval-mlogloss:0.89862
[15]	train-mlogloss:0.89558	eval-mlogloss:0.88759
[16]	train-mlogloss:0.88510	eval-mlogloss:0.87715
[17]	train-mlogloss:0.87752	eval-mlogloss:0.86876
[18]	train-mlogloss:0.86721	eval-mlogloss:0.85771
[19]	train-mlogloss:0.85643	eval-mlogloss:0.84644
[20]	train-mlogloss:0.84845	eval-mlogloss:0.83789
[21]	train-mlogloss:0.84123	eval-mlogloss:0.83020
[22]	train-mlogloss:0.83148	eval-mlogloss:0.81926
[23]	train-mlogloss:0.82150	eval-mlogloss:0.80905
[24]	train-mlogloss:0.81307	eval-mlogloss:0.80064
[25]	train-mlogloss:0.80424	eval-mlogloss:0.79099
[26]	train-mlogloss:0.79539	eval-mlogloss:0.78135
[27]	train-mlogloss:0.78757	eval-mlogloss:0.77331
[28]	train-mlogloss:0.77893	eval-mlogloss:0.76406
[29]	train-mlogloss:0.77098	eval-mlogloss:0.75477
[30]	train-mlogloss:0.76302	eval-mlogloss:0.74660
[31]	train-mlogloss:0.75410	eval-mlogloss:0.73685
[32]	train-mlogloss:0.74611	eval-mlogloss:0.72879
[33]	train-mlogloss:0.73948	eval-mlogloss:0.72097
[34]	train-mlogloss:0.73132	eval-mlogloss:0.71256
[35]	train-mlogloss:0.72533	eval-mlogloss:0.70607
[36]	train-mlogloss:0.71772	eval-mlogloss:0.69809
[37]	train-mlogloss:0.70980	eval-mlogloss:0.68962
[38]	train-mlogloss:0.70413	eval-mlogloss:0.68343
[39]	train-mlogloss:0.69630	eval-mlogloss:0.67467
[40]	train-mlogloss:0.68858	eval-mlogloss:0.66656
[41]	train-mlogloss:0.68098	eval-mlogloss:0.65850
[42]	train-mlogloss:0.67390	eval-mlogloss:0.65095
[43]	train-mlogloss:0.66701	eval-mlogloss:0.64360
[44]	train-mlogloss:0.66146	eval-mlogloss:0.63706
[45]	train-mlogloss:0.65399	eval-mlogloss:0.62929
[46]	train-mlogloss:0.64845	eval-mlogloss:0.62343
[47]	train-mlogloss:0.64287	eval-mlogloss:0.61768
[48]	train-mlogloss:0.63763	eval-mlogloss:0.61190
[49]	train-mlogloss:0.63075	eval-mlogloss:0.60458
[50]	train-mlogloss:0.62571	eval-mlogloss:0.59885
[51]	train-mlogloss:0.61963	eval-mlogloss:0.59233
[52]	train-mlogloss:0.61300	eval-mlogloss:0.58523
[53]	train-mlogloss:0.60817	eval-mlogloss:0.58016
[54]	train-mlogloss:0.60341	eval-mlogloss:0.57507
[55]	train-mlogloss:0.59745	eval-mlogloss:0.56854
[56]	train-mlogloss:0.59181	eval-mlogloss:0.56215
[57]	train-mlogloss:0.58743	eval-mlogloss:0.55722
[58]	train-mlogloss:0.58308	eval-mlogloss:0.55267
[59]	train-mlogloss:0.57809	eval-mlogloss:0.54724
[60]	train-mlogloss:0.57424	eval-mlogloss:0.54327
[61]	train-mlogloss:0.57094	eval-mlogloss:0.53994
[62]	train-mlogloss:0.56654	eval-mlogloss:0.53510
[63]	train-mlogloss:0.56256	eval-mlogloss:0.53044
[64]	train-mlogloss:0.55837	eval-mlogloss:0.52622
[65]	train-mlogloss:0.55328	eval-mlogloss:0.52115
[66]	train-mlogloss:0.54901	eval-mlogloss:0.51643
[67]	train-mlogloss:0.54501	eval-mlogloss:0.51205
[68]	train-mlogloss:0.54123	eval-mlogloss:0.50798
[69]	train-mlogloss:0.53771	eval-mlogloss:0.50395
[70]	train-mlogloss:0.53397	eval-mlogloss:0.49985
[71]	train-mlogloss:0.52996	eval-mlogloss:0.49573
[72]	train-mlogloss:0.52642	eval-mlogloss:0.49175
[73]	train-mlogloss:0.52165	eval-mlogloss:0.48673
[74]	train-mlogloss:0.51731	eval-mlogloss:0.48233
[75]	train-mlogloss:0.51342	eval-mlogloss:0.47794
[76]	train-mlogloss:0.50887	eval-mlogloss:0.47261
[77]	train-mlogloss:0.50443	eval-mlogloss:0.46764
[78]	train-mlogloss:0.50082	eval-mlogloss:0.46344
[79]	train-mlogloss:0.49752	eval-mlogloss:0.45985
[80]	train-mlogloss:0.49438	eval-mlogloss:0.45645
[81]	train-mlogloss:0.49095	eval-mlogloss:0.45279
[82]	train-mlogloss:0.48747	eval-mlogloss:0.44913
[83]	train-mlogloss:0.48407	eval-mlogloss:0.44538
[84]	train-mlogloss:0.48088	eval-mlogloss:0.44206
[85]	train-mlogloss:0.47764	eval-mlogloss:0.43888
[86]	train-mlogloss:0.47432	eval-mlogloss:0.43523
[87]	train-mlogloss:0.47140	eval-mlogloss:0.43201
[88]	train-mlogloss:0.46832	eval-mlogloss:0.42854
[89]	train-mlogloss:0.46507	eval-mlogloss:0.42511
[90]	train-mlogloss:0.46215	eval-mlogloss:0.42163
[91]	train-mlogloss:0.45916	eval-mlogloss:0.41834
[92]	train-mlogloss:0.45606	eval-mlogloss:0.41507
[93]	train-mlogloss:0.45325	eval-mlogloss:0.41208
[94]	train-mlogloss:0.45030	eval-mlogloss:0.40918
[95]	train-mlogloss:0.44750	eval-mlogloss:0.40642
[96]	train-mlogloss:0.44464	eval-mlogloss:0.40316
[97]	train-mlogloss:0.44190	eval-mlogloss:0.40039
[98]	train-mlogloss:0.43903	eval-mlogloss:0.39723
[99]	train-mlogloss:0.43627	eval-mlogloss:0.39432
[100]	train-mlogloss:0.43389	eval-mlogloss:0.39211
[101]	train-mlogloss:0.43105	eval-mlogloss:0.38912
[102]	train-mlogloss:0.42817	eval-mlogloss:0.38567
[103]	train-mlogloss:0.42562	eval-mlogloss:0.38262
[104]	train-mlogloss:0.42246	eval-mlogloss:0.37931
[105]	train-mlogloss:0.42010	eval-mlogloss:0.37675
[106]	train-mlogloss:0.41773	eval-mlogloss:0.37395
[107]	train-mlogloss:0.41577	eval-mlogloss:0.37196
[108]	train-mlogloss:0.41324	eval-mlogloss:0.36918
[109]	train-mlogloss:0.41062	eval-mlogloss:0.36626
[110]	train-mlogloss:0.40831	eval-mlogloss:0.36364
[111]	train-mlogloss:0.40606	eval-mlogloss:0.36116
[112]	train-mlogloss:0.40370	eval-mlogloss:0.35856
[113]	train-mlogloss:0.40135	eval-mlogloss:0.35569
[114]	train-mlogloss:0.39911	eval-mlogloss:0.35306
[115]	train-mlogloss:0.39664	eval-mlogloss:0.35052
[116]	train-mlogloss:0.39618	eval-mlogloss:0.34995
[117]	train-mlogloss:0.39395	eval-mlogloss:0.34759
[118]	train-mlogloss:0.39289	eval-mlogloss:0.34646
[119]	train-mlogloss:0.39057	eval-mlogloss:0.34401
[120]	train-mlogloss:0.38834	eval-mlogloss:0.34178
[121]	train-mlogloss:0.38611	eval-mlogloss:0.33935
[122]	train-mlogloss:0.38377	eval-mlogloss:0.33680
[123]	train-mlogloss:0.38194	eval-mlogloss:0.33490
[124]	train-mlogloss:0.38004	eval-mlogloss:0.33283
[125]	train-mlogloss:0.37887	eval-mlogloss:0.33147
[126]	train-mlogloss:0.37795	eval-mlogloss:0.33030
[127]	train-mlogloss:0.37620	eval-mlogloss:0.32844
[128]	train-mlogloss:0.37525	eval-mlogloss:0.32737
[129]	train-mlogloss:0.37431	eval-mlogloss:0.32619
[130]	train-mlogloss:0.37299	eval-mlogloss:0.32483
[131]	train-mlogloss:0.37231	eval-mlogloss:0.32421
[132]	train-mlogloss:0.37025	eval-mlogloss:0.32187
[133]	train-mlogloss:0.36928	eval-mlogloss:0.32076
[134]	train-mlogloss:0.36923	eval-mlogloss:0.32070
[135]	train-mlogloss:0.36705	eval-mlogloss:0.31825
[136]	train-mlogloss:0.36623	eval-mlogloss:0.31735
[137]	train-mlogloss:0.36428	eval-mlogloss:0.31538
[138]	train-mlogloss:0.36323	eval-mlogloss:0.31417
[139]	train-mlogloss:0.36237	eval-mlogloss:0.31307
[140]	train-mlogloss:0.36229	eval-mlogloss:0.31298
[141]	train-mlogloss:0.36215	eval-mlogloss:0.31268
[142]	train-mlogloss:0.36064	eval-mlogloss:0.31109
[143]	train-mlogloss:0.35996	eval-mlogloss:0.31018
[144]	train-mlogloss:0.35890	eval-mlogloss:0.30896
[145]	train-mlogloss:0.35879	eval-mlogloss:0.30884
[146]	train-mlogloss:0.35704	eval-mlogloss:0.30690
[147]	train-mlogloss:0.35603	eval-mlogloss:0.30556
[148]	train-mlogloss:0.35450	eval-mlogloss:0.30414
[149]	train-mlogloss:0.35368	eval-mlogloss:0.30311
[150]	train-mlogloss:0.35356	eval-mlogloss:0.30281
[151]	train-mlogloss:0.35286	eval-mlogloss:0.30187
[152]	train-mlogloss:0.35219	eval-mlogloss:0.30114
[153]	train-mlogloss:0.35041	eval-mlogloss:0.29917
[154]	train-mlogloss:0.34856	eval-mlogloss:0.29723
[155]	train-mlogloss:0.34852	eval-mlogloss:0.29727
[156]	train-mlogloss:0.34773	eval-mlogloss:0.29607
[157]	train-mlogloss:0.34757	eval-mlogloss:0.29567
[158]	train-mlogloss:0.34739	eval-mlogloss:0.29548
[159]	train-mlogloss:0.34658	eval-mlogloss:0.29466
[160]	train-mlogloss:0.34649	eval-mlogloss:0.29444
[161]	train-mlogloss:0.34639	eval-mlogloss:0.29420
[162]	train-mlogloss:0.34569	eval-mlogloss:0.29342
[163]	train-mlogloss:0.34562	eval-mlogloss:0.29324
[164]	train-mlogloss:0.34549	eval-mlogloss:0.29306
[165]	train-mlogloss:0.34465	eval-mlogloss:0.29193
[166]	train-mlogloss:0.34377	eval-mlogloss:0.29079
[167]	train-mlogloss:0.34370	eval-mlogloss:0.29071
[168]	train-mlogloss:0.34370	eval-mlogloss:0.29072
[169]	train-mlogloss:0.34343	eval-mlogloss:0.29034
[170]	train-mlogloss:0.34269	eval-mlogloss:0.28953
[171]	train-mlogloss:0.34190	eval-mlogloss:0.28869
[172]	train-mlogloss:0.34183	eval-mlogloss:0.28850
[173]	train-mlogloss:0.34116	eval-mlogloss:0.28764
[174]	train-mlogloss:0.34039	eval-mlogloss:0.28672
[175]	train-mlogloss:0.33981	eval-mlogloss:0.28611
[176]	train-mlogloss:0.33916	eval-mlogloss:0.28520
[177]	train-mlogloss:0.33741	eval-mlogloss:0.28327
[178]	train-mlogloss:0.33662	eval-mlogloss:0.28238
[179]	train-mlogloss:0.33595	eval-mlogloss:0.28146
[180]	train-mlogloss:0.33583	eval-mlogloss:0.28116
[181]	train-mlogloss:0.33580	eval-mlogloss:0.28113
[182]	train-mlogloss:0.33577	eval-mlogloss:0.28116
[183]	train-mlogloss:0.33566	eval-mlogloss:0.28091
[184]	train-mlogloss:0.33477	eval-mlogloss:0.28001
[185]	train-mlogloss:0.33473	eval-mlogloss:0.27999
[186]	train-mlogloss:0.33398	eval-mlogloss:0.27908
[187]	train-mlogloss:0.33398	eval-mlogloss:0.27908
[188]	train-mlogloss:0.33393	eval-mlogloss:0.27896
[189]	train-mlogloss:0.33385	eval-mlogloss:0.27879
[190]	train-mlogloss:0.33376	eval-mlogloss:0.27860
[191]	train-mlogloss:0.33367	eval-mlogloss:0.27835
[192]	train-mlogloss:0.33362	eval-mlogloss:0.27832
[193]	train-mlogloss:0.33354	eval-mlogloss:0.27810
[194]	train-mlogloss:0.33283	eval-mlogloss:0.27727
[195]	train-mlogloss:0.33278	eval-mlogloss:0.27712
[196]	train-mlogloss:0.33267	eval-mlogloss:0.27715
[197]	train-mlogloss:0.33264	eval-mlogloss:0.27719
[198]	train-mlogloss:0.33262	eval-mlogloss:0.27722
[199]	train-mlogloss:0.33247	eval-mlogloss:0.27705
[200]	train-mlogloss:0.33241	eval-mlogloss:0.27701
[201]	train-mlogloss:0.33080	eval-mlogloss:0.27524
[202]	train-mlogloss:0.33076	eval-mlogloss:0.27512
[203]	train-mlogloss:0.33065	eval-mlogloss:0.27485
[204]	train-mlogloss:0.33059	eval-mlogloss:0.27483
[205]	train-mlogloss:0.33050	eval-mlogloss:0.27456
[206]	train-mlogloss:0.33044	eval-mlogloss:0.27444
[207]	train-mlogloss:0.33036	eval-mlogloss:0.27440
[208]	train-mlogloss:0.33032	eval-mlogloss:0.27437
[209]	train-mlogloss:0.32876	eval-mlogloss:0.27254
[210]	train-mlogloss:0.32865	eval-mlogloss:0.27224
[211]	train-mlogloss:0.32858	eval-mlogloss:0.27221
[212]	train-mlogloss:0.32852	eval-mlogloss:0.27205
[213]	train-mlogloss:0.32843	eval-mlogloss:0.27197
[214]	train-mlogloss:0.32841	eval-mlogloss:0.27199
[215]	train-mlogloss:0.32818	eval-mlogloss:0.27156
[216]	train-mlogloss:0.32747	eval-mlogloss:0.27053
[217]	train-mlogloss:0.32742	eval-mlogloss:0.27037
[218]	train-mlogloss:0.32677	eval-mlogloss:0.26954
[219]	train-mlogloss:0.32673	eval-mlogloss:0.26951
[220]	train-mlogloss:0.32664	eval-mlogloss:0.26944
[221]	train-mlogloss:0.32637	eval-mlogloss:0.26915
[222]	train-mlogloss:0.32635	eval-mlogloss:0.26918
[223]	train-mlogloss:0.32628	eval-mlogloss:0.26917
[224]	train-mlogloss:0.32544	eval-mlogloss:0.26793
[225]	train-mlogloss:0.32468	eval-mlogloss:0.26693
[226]	train-mlogloss:0.32469	eval-mlogloss:0.26693
[227]	train-mlogloss:0.32465	eval-mlogloss:0.26690
[228]	train-mlogloss:0.32461	eval-mlogloss:0.26686
[229]	train-mlogloss:0.32395	eval-mlogloss:0.26617
[230]	train-mlogloss:0.32388	eval-mlogloss:0.26598
[231]	train-mlogloss:0.32385	eval-mlogloss:0.26595
[232]	train-mlogloss:0.32383	eval-mlogloss:0.26594
[233]	train-mlogloss:0.32381	eval-mlogloss:0.26597
[234]	train-mlogloss:0.32358	eval-mlogloss:0.26571
[235]	train-mlogloss:0.32200	eval-mlogloss:0.26403
[236]	train-mlogloss:0.32196	eval-mlogloss:0.26402
[237]	train-mlogloss:0.32187	eval-mlogloss:0.26380
[238]	train-mlogloss:0.32180	eval-mlogloss:0.26379
[239]	train-mlogloss:0.32175	eval-mlogloss:0.26365
[240]	train-mlogloss:0.32172	eval-mlogloss:0.26364
[241]	train-mlogloss:0.32172	eval-mlogloss:0.26363
[242]	train-mlogloss:0.32164	eval-mlogloss:0.26357
[243]	train-mlogloss:0.32164	eval-mlogloss:0.26356
[244]	train-mlogloss:0.32164	eval-mlogloss:0.26356
[245]	train-mlogloss:0.32158	eval-mlogloss:0.26338
[246]	train-mlogloss:0.32155	eval-mlogloss:0.26338
[247]	train-mlogloss:0.32156	eval-mlogloss:0.26340
[248]	train-mlogloss:0.32156	eval-mlogloss:0.26340
[249]	train-mlogloss:0.32154	eval-mlogloss:0.26341
[250]	train-mlogloss:0.32148	eval-mlogloss:0.26321
[251]	train-mlogloss:0.32144	eval-mlogloss:0.26317
[252]	train-mlogloss:0.32140	eval-mlogloss:0.26309
[253]	train-mlogloss:0.32136	eval-mlogloss:0.26307
[254]	train-mlogloss:0.32135	eval-mlogloss:0.26311
[255]	train-mlogloss:0.32128	eval-mlogloss:0.26304
[256]	train-mlogloss:0.32118	eval-mlogloss:0.26291
[257]	train-mlogloss:0.32116	eval-mlogloss:0.26293
[258]	train-mlogloss:0.32089	eval-mlogloss:0.26258
[259]	train-mlogloss:0.32089	eval-mlogloss:0.26258
[260]	train-mlogloss:0.32083	eval-mlogloss:0.26241
[261]	train-mlogloss:0.32081	eval-mlogloss:0.26243
[262]	train-mlogloss:0.32074	eval-mlogloss:0.26222
[263]	train-mlogloss:0.32066	eval-mlogloss:0.26217
[264]	train-mlogloss:0.32061	eval-mlogloss:0.26212
[265]	train-mlogloss:0.32056	eval-mlogloss:0.26196
[266]	train-mlogloss:0.32047	eval-mlogloss:0.26171
[267]	train-mlogloss:0.32036	eval-mlogloss:0.26162
[268]	train-mlogloss:0.32026	eval-mlogloss:0.26157
[269]	train-mlogloss:0.32018	eval-mlogloss:0.26147
[270]	train-mlogloss:0.31968	eval-mlogloss:0.26078
[271]	train-mlogloss:0.31964	eval-mlogloss:0.26076
[272]	train-mlogloss:0.31961	eval-mlogloss:0.26076
[273]	train-mlogloss:0.31958	eval-mlogloss:0.26074
[274]	train-mlogloss:0.31958	eval-mlogloss:0.26076
[275]	train-mlogloss:0.31950	eval-mlogloss:0.26074
[276]	train-mlogloss:0.31951	eval-mlogloss:0.26074
[277]	train-mlogloss:0.31949	eval-mlogloss:0.26071
[278]	train-mlogloss:0.31942	eval-mlogloss:0.26066
[279]	train-mlogloss:0.31939	eval-mlogloss:0.26062
[280]	train-mlogloss:0.31879	eval-mlogloss:0.25990
[281]	train-mlogloss:0.31874	eval-mlogloss:0.25989
[282]	train-mlogloss:0.31872	eval-mlogloss:0.25991
[283]	train-mlogloss:0.31864	eval-mlogloss:0.25968
[284]	train-mlogloss:0.31862	eval-mlogloss:0.25963
[285]	train-mlogloss:0.31862	eval-mlogloss:0.25963
[286]	train-mlogloss:0.31855	eval-mlogloss:0.25962
[287]	train-mlogloss:0.31787	eval-mlogloss:0.25883
[288]	train-mlogloss:0.31787	eval-mlogloss:0.25882
[289]	train-mlogloss:0.31725	eval-mlogloss:0.25807
[290]	train-mlogloss:0.31717	eval-mlogloss:0.25794
[291]	train-mlogloss:0.31717	eval-mlogloss:0.25796
[292]	train-mlogloss:0.31716	eval-mlogloss:0.25795
[293]	train-mlogloss:0.31658	eval-mlogloss:0.25722
[294]	train-mlogloss:0.31653	eval-mlogloss:0.25720
[295]	train-mlogloss:0.31646	eval-mlogloss:0.25707
[296]	train-mlogloss:0.31646	eval-mlogloss:0.25710
[297]	train-mlogloss:0.31644	eval-mlogloss:0.25710
[298]	train-mlogloss:0.31638	eval-mlogloss:0.25706
[299]	train-mlogloss:0.31637	eval-mlogloss:0.25708

[I 2025-06-12 19:48:01,482] Trial 41 finished with value: 1.0 and parameters: {'lambda': 3.945911427946644e-08, 'alpha': 0.021375822810317652, 'eta': 0.011564745944452386, 'gamma': 0.01447467362485958, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.6350771726348153, 'colsample_bytree': 0.9265166651128117}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.05425	eval-mlogloss:1.05494
[1]	train-mlogloss:1.01101	eval-mlogloss:1.00860
[2]	train-mlogloss:0.97064	eval-mlogloss:0.96620
[3]	train-mlogloss:0.93085	eval-mlogloss:0.92409
[4]	train-mlogloss:0.89600	eval-mlogloss:0.88814
[5]	train-mlogloss:0.85984	eval-mlogloss:0.84921
[6]	train-mlogloss:0.82688	eval-mlogloss:0.81326
[7]	train-mlogloss:0.79930	eval-mlogloss:0.78473

[I 2025-06-12 19:48:01,711] Trial 42 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.04522	eval-mlogloss:1.04224
[1]	train-mlogloss:1.00289	eval-mlogloss:0.99109

[I 2025-06-12 19:48:01,884] Trial 43 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06363	eval-mlogloss:1.06411
[1]	train-mlogloss:1.03682	eval-mlogloss:1.03311
[2]	train-mlogloss:1.00528	eval-mlogloss:1.00079
[3]	train-mlogloss:0.97141	eval-mlogloss:0.96549
[4]	train-mlogloss:0.94239	eval-mlogloss:0.93571
[5]	train-mlogloss:0.91229	eval-mlogloss:0.90340
[6]	train-mlogloss:0.88997	eval-mlogloss:0.87944
[7]	train-mlogloss:0.86623	eval-mlogloss:0.85600

[I 2025-06-12 19:48:02,067] Trial 44 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.93323	eval-mlogloss:0.92774
[1]	train-mlogloss:0.80065	eval-mlogloss:0.78455
[2]	train-mlogloss:0.69356	eval-mlogloss:0.67270

[I 2025-06-12 19:48:02,218] Trial 45 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06412	eval-mlogloss:1.06298
[1]	train-mlogloss:1.02287	eval-mlogloss:1.02046
[2]	train-mlogloss:0.98595	eval-mlogloss:0.98212
[3]	train-mlogloss:0.94848	eval-mlogloss:0.94357
[4]	train-mlogloss:0.91397	eval-mlogloss:0.90754
[5]	train-mlogloss:0.88711	eval-mlogloss:0.87826
[6]	train-mlogloss:0.86105	eval-mlogloss:0.85032
[7]	train-mlogloss:0.83719	eval-mlogloss:0.82526
[8]	train-mlogloss:0.81420	eval-mlogloss:0.80115

[I 2025-06-12 19:48:02,417] Trial 46 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.98636	eval-mlogloss:0.98426
[1]	train-mlogloss:0.89220	eval-mlogloss:0.88405

[I 2025-06-12 19:48:02,590] Trial 47 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.97446	eval-mlogloss:0.96995
[1]	train-mlogloss:0.92311	eval-mlogloss:0.90863
[2]	train-mlogloss:0.83775	eval-mlogloss:0.81549

[I 2025-06-12 19:48:02,806] Trial 48 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.01814	eval-mlogloss:1.01905
[1]	train-mlogloss:0.95880	eval-mlogloss:0.95049

[I 2025-06-12 19:48:02,968] Trial 49 pruned. Trial was pruned at iteration 2.

Best trial: {'lambda': 0.0053756740193569574, 'alpha': 2.3961480124483085e-08, 'eta': 0.09531920517143157, 'gamma': 0.11584042713761838, 'max_depth': 9, 'min_child_weight': 5, 'subsample': 0.4928767937806364, 'colsample_bytree': 0.9666856335903532}
Best accuracy: 1.0

In [36]:
! pip install optuna-integration[xgboost]

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.3.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: optuna in c:\users\bhara\anaconda3\lib\site-packages (from optuna-integration[xgboost]) (4.3.0)
Requirement already satisfied: xgboost in c:\users\bhara\anaconda3\lib\site-packages (from optuna-integration[xgboost]) (2.1.3)
Requirement already satisfied: alembic>=1.5.0 in c:\users\bhara\anaconda3\lib\site-packages (from optuna->optuna-integration[xgboost]) (1.16.1)
Requirement already satisfied: colorlog in c:\users\bhara\anaconda3\lib\site-packages (from optuna->optuna-integration[xgboost]) (6.9.0)
Requirement already satisfied: numpy in c:\users\bhara\anaconda3\lib\site-packages (from optuna->optuna-integration[xgboost]) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\bhara\anaconda3\lib\site-packages (from optuna->optuna-integration[xgboost]) (24.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\bhara\anaconda3\lib\site-packages (from optuna->optuna-integration[xgboost]) (2.0.34)
Requirement already satisfied: tqdm in c:\users\bhara\anaconda3\lib\site-packages (from optuna->optuna-integration[xgboost]) (4.66.5)
Requirement already satisfied: PyYAML in c:\users\bhara\anaconda3\lib\site-packages (from optuna->optuna-integration[xgboost]) (6.0.1)
Requirement already satisfied: scipy in c:\users\bhara\anaconda3\lib\site-packages (from xgboost->optuna-integration[xgboost]) (1.13.1)
Requirement already satisfied: Mako in c:\users\bhara\anaconda3\lib\site-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\bhara\anaconda3\lib\site-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\bhara\anaconda3\lib\site-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.0.1)
Requirement already satisfied: colorama in c:\users\bhara\anaconda3\lib\site-packages (from colorlog->optuna->optuna-integration[xgboost]) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\bhara\anaconda3\lib\site-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (2.1.3)
Downloading optuna_integration-4.3.0-py3-none-any.whl (98 kB)
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.3.0

In [38]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()