In [1]:
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('cse',2023),('cse',2020),('ece',2020),('ece',2022),('ece',2021),('ece',2018),('ece',2017)]
a = pd.Series([1,2,3,4,5,6,7,8,9,10,11],index=index_val)
a

(cse, 2019)     1
(cse, 2020)     2
(cse, 2021)     3
(cse, 2022)     4
(cse, 2023)     5
(cse, 2020)     6
(ece, 2020)     7
(ece, 2022)     8
(ece, 2021)     9
(ece, 2018)    10
(ece, 2017)    11
dtype: int64

In [2]:
# problem with this multiindex series is 
# a['cse']

In [3]:
# how to create multiindex dataframe
# 1. pd.MultindexFromtuple
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('cse',2023),('cse',2020),('ece',2020),('ece',2022),('ece',2021),('ece',2018),('ece',2017)]
multiindex= pd.MultiIndex.from_tuples(index_val)
multiindex.levels  # decouple the branch and year 

# 2. pd.multiindex.from_product

multiindex = pd.MultiIndex.from_product([['cse', 'ece'], [2017, 2018, 2019, 2020, 2021, 2022, 2023]])

In [4]:
multiindex.levels[0]

Index(['cse', 'ece'], dtype='object')

In [9]:
a = pd.Series([1,2,3,4,5,6,7,8,9,10,11,12,13,14],index = multiindex)
a

cse  2017     1
     2018     2
     2019     3
     2020     4
     2021     5
     2022     6
     2023     7
ece  2017     8
     2018     9
     2019    10
     2020    11
     2021    12
     2022    13
     2023    14
dtype: int64

In [10]:
# how to fetch the data from multiindex series
a['cse']

2017    1
2018    2
2019    3
2020    4
2021    5
2022    6
2023    7
dtype: int64

In [19]:
#unstack to convert multiindex series to dataframe
df=a.unstack()

In [ ]:
# stack to convert dataframe to multiindex series   
df.stack()

cse  2017     1
     2018     2
     2019     3
     2020     4
     2021     5
     2022     6
     2023     7
ece  2017     8
     2018     9
     2019    10
     2020    11
     2021    12
     2022    13
     2023    14
dtype: int64

# Multiindex DataFrame

In [22]:
from calendar import c


branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
        [17,18],
        [19,20],
        [21,22],
        [23,24],
        [25,26],
        [27,28]
        
    ],
    index=multiindex,
    columns=['avg_package','students']
)

In [23]:
branch_df1

          avg_package  students
cse 2017            1         2
    2018            3         4
    2019            5         6
    2020            7         8
    2021            9        10
    2022           11        12
    2023           13        14
ece 2017           15        16
    2018           17        18
    2019           19        20
    2020           21        22
    2021           23        24
    2022           25        26
    2023           27        28

In [28]:
branch_df1.loc['cse']
branch_df1.loc['ece']
branch_df1['avg_package']
branch_df1['students']

cse  2017     2
     2018     4
     2019     6
     2020     8
     2021    10
     2022    12
     2023    14
ece  2017    16
     2018    18
     2019    20
     2020    22
     2021    24
     2022    26
     2023    28
Name: students, dtype: int64

In [31]:
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0,],
        [3,4,0,0,],
        [5,6,0,0,],
        [7,8,0,0,],
    ]
,
    index=[2019,2020,2021,2022],
    columns=pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

In [32]:
branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [33]:
branch_df2['delhi']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8